var annotated =
[
    [ "Risk1.About", "classRisk1_1_1About.html", "classRisk1_1_1About" ],
    [ "Risk1.AI", "classRisk1_1_1AI.html", "classRisk1_1_1AI" ],
    [ "Risk1.AI2", "classRisk1_1_1AI2.html", "classRisk1_1_1AI2" ],
    [ "Risk1.AI3", "classRisk1_1_1AI3.html", "classRisk1_1_1AI3" ],
    [ "Risk1.AI4", "classRisk1_1_1AI4.html", "classRisk1_1_1AI4" ],
    [ "Risk1.ArmyMove", "classRisk1_1_1ArmyMove.html", "classRisk1_1_1ArmyMove" ],
    [ "Risk1.ArtificalIntelligence", "classRisk1_1_1ArtificalIntelligence.html", "classRisk1_1_1ArtificalIntelligence" ],
    [ "Risk1.Bolge", "classRisk1_1_1Bolge.html", "classRisk1_1_1Bolge" ],
    [ "Risk1.ChangePlayer", "classRisk1_1_1ChangePlayer.html", "classRisk1_1_1ChangePlayer" ],
    [ "Risk1.ChangeStyle", "classRisk1_1_1ChangeStyle.html", "classRisk1_1_1ChangeStyle" ],
    [ "Risk1.Chart", "classRisk1_1_1Chart.html", "classRisk1_1_1Chart" ],
    [ "Risk1.Continent", "classRisk1_1_1Continent.html", "classRisk1_1_1Continent" ],
    [ "Risk1.DistanceCalculator", "classRisk1_1_1DistanceCalculator.html", "classRisk1_1_1DistanceCalculator" ],
    [ "Risk1.Form1", "classRisk1_1_1Form1.html", "classRisk1_1_1Form1" ],
    [ "Risk1.Galibiyet", "classRisk1_1_1Galibiyet.html", "classRisk1_1_1Galibiyet" ],
    [ "Risk1.GameData", "classRisk1_1_1GameData.html", "classRisk1_1_1GameData" ],
    [ "Risk1.Giris", "classRisk1_1_1Giris.html", "classRisk1_1_1Giris" ],
    [ "Risk1.Graph", "classRisk1_1_1Graph.html", "classRisk1_1_1Graph" ],
    [ "Risk1.Loading", "classRisk1_1_1Loading.html", "classRisk1_1_1Loading" ],
    [ "Risk1.Form1.MyListViewSorter", "classRisk1_1_1Form1_1_1MyListViewSorter.html", "classRisk1_1_1Form1_1_1MyListViewSorter" ],
    [ "Risk1.Nokta", "classRisk1_1_1Nokta.html", "classRisk1_1_1Nokta" ],
    [ "Risk1.Ordu", "classRisk1_1_1Ordu.html", "classRisk1_1_1Ordu" ],
    [ "Risk1.Player", "classRisk1_1_1Player.html", "classRisk1_1_1Player" ],
    [ "Risk1.Program", "classRisk1_1_1Program.html", "classRisk1_1_1Program" ],
    [ "Risk1.Rules", "classRisk1_1_1Rules.html", "classRisk1_1_1Rules" ],
    [ "Risk1.SaldiriEkrani", "classRisk1_1_1SaldiriEkrani.html", "classRisk1_1_1SaldiriEkrani" ],
    [ "Risk1.Statistics", "classRisk1_1_1Statistics.html", "classRisk1_1_1Statistics" ]
];