ANKARISK: Risk1.AI4 Class Reference
Risk1.AI4 Class Reference
Public Member Functions
override string getName ()
Bu metod Yapay zekanın ismini döndürmelidir.
override int requestTerritory (GameData f1)
Bu metod bölgeler seçilirken istenen bolgenin indexini dondurmektedir.
override int getTerritoryToPlaceFirstArmies (GameData f1)
İlk başta tüm oyunculara verilen ilk askerler dağıtılırken her oyuncuya tek tek askerlerini nereye koyması gerektiği sorulur bu metod ilk ordunun koyulması gereken bolgenin indexini dondurur.
override List< int > getTerritoriesIndexToPlaceNewArmies (GameData f1)
Oyuncu her turn'de kazandığı yeni askerleri hangi bolgelere yerleştireceğini bu metod sayesinde belirler.
override bool devam (GameData f1)
Kullanıcının hamle yapmaya devam edip etmeyeceğini belirler.
override bool saldiracanMi (GameData f1)
Bu metod kullanıcının saldırı yapmak isteyip istemediğini belirler.
override List< int > getSavasBolgeIndexleri (GameData f1)
Bu metod savaş yapılacak bolgelerin indexlerini belirlemek içindir.
override List< int > divideArmies (int index1, int index2, GameData f1)
Oyuncu bir bölgeyi igal ettikten sonra o bölge ile kendi bölgesi arasındaki askerleri nasıl paylaştıracağına bu metod vasıtasıyla karar verir.
override bool askerTransferiYapacakmisin (GameData f1)
override List< int > askerTransferiYap (GameData f1)
Public Attributes
int saldirmaDurumu = 0
List< int > durum3SaldiriIndexleri = new List<int>(2)
Static Public Attributes
static int aiid = 4
static string name = "Fatih Sultan Mehmet"
static Image resim = Properties.Resources.fatih
Private Member Functions
bool southAmericaBendeMi (GameData f1)
bool southAmericaSinirindaDusmanVarMi (GameData f1)
int dusmanNerede (GameData f1)
int southAmericadaToprakVarMi (GameData f1)
bool buBolgeGuneyAmerikadaMi (Bolge b)
Detailed Description
Definition at line 9 of file AI4.cs.
Member Function Documentation
override List<int> Risk1.AI4.askerTransferiYap (GameData f1) [inline, virtual]
Implements Risk1.ArtificalIntelligence.
Definition at line 478 of file AI4.cs.
References Risk1.Ordu.askerSayisi, Risk1.ArtificalIntelligence.getDostSayisi(), Risk1.ArtificalIntelligence.getKomsuDusmanSayisi(), Risk1.Bolge.index, Risk1.Bolge.komsular, Risk1.Bolge.ordu, and Risk1.Bolge.sahip.
        {
            bool break2 = false;
            List<int> veriler = new List<int>();
            foreach (Bolge b in f1.players[f1.turn].bolgeler)
            {
                if (getKomsuDusmanSayisi(b) == 0)
                {
                    if (b.ordu.askerSayisi > 1)
                    {
                        if (getDostSayisi(b) > 0)
{
                            //Once nereden transfer yapacagimizi belirledik
                            veriler.Add(b.index);
                            foreach (Bolge komsu in b.komsular)
{
                                if (komsu.sahip == b.sahip)
{
                                    veriler.Add(komsu.index);
                                    veriler.Add(1);
                                    veriler.Add(komsu.ordu.askerSayisi + b.ordu.askerSayisi - 1);
                                    break2 = true;
                                    break;
                                }
                            }
                            if (break2)
                                break;
                        }
                    }
                }
            }
            return veriler;
        }
override bool Risk1.AI4.askerTransferiYapacakmisin (GameData f1) [inline, virtual]
Implements Risk1.ArtificalIntelligence.
Definition at line 459 of file AI4.cs.
References Risk1.Ordu.askerSayisi, Risk1.ArtificalIntelligence.getDostSayisi(), Risk1.ArtificalIntelligence.getKomsuDusmanSayisi(), and Risk1.Bolge.ordu.
        {
            foreach (Bolge b in f1.players[f1.turn].bolgeler)
            {
                if (getKomsuDusmanSayisi(b) == 0)
                {
                    if (b.ordu.askerSayisi > 1)
                    {
                        if (getDostSayisi(b) > 0)
{
                            return true;
                        }
                    }
                }
            }
            return false;
        }
bool Risk1.AI4.buBolgeGuneyAmerikadaMi (Bolge b) [inline, private]
Definition at line 362 of file AI4.cs.
References Risk1.Bolge.index.
Referenced by Risk1.AI4.devam(), and Risk1.AI4.getSavasBolgeIndexleri().
        {
            if (b.index == 9)
            {
                return true;
            }
            if (b.index == 10)
            {
                return true;
            }
            if (b.index == 11)
            {
                return true;
            }
            if (b.index == 12)
            {
                return true;
            }
            return false;
        }
override bool Risk1.AI4.devam (GameData form1) [inline, virtual]
Kullanıcının hamle yapmaya devam edip etmeyeceğini belirler.
Parameters:
form1
Returns:
Devam etmek istiyorsa true devam etmek istemiyorsa false.
Implements Risk1.ArtificalIntelligence.
Definition at line 229 of file AI4.cs.
References Risk1.Ordu.askerSayisi, Risk1.GameData.bolgeler, Risk1.AI4.buBolgeGuneyAmerikadaMi(), Risk1.AI4.durum3SaldiriIndexleri, Risk1.ArtificalIntelligence.getEnGucluBolgemIndex(), Risk1.ArtificalIntelligence.getKomsuDusmanSayisi(), Risk1.ArtificalIntelligence.getToplamDusmanSayisi(), Risk1.Bolge.index, Risk1.Bolge.komsular, Risk1.Bolge.ordu, Risk1.GameData.players, Risk1.Bolge.sahip, Risk1.AI4.saldirmaDurumu, Risk1.AI4.southAmericaBendeMi(), Risk1.AI4.southAmericadaToprakVarMi(), and Risk1.GameData.turn.
Referenced by Risk1.AI4.saldiracanMi().
        {
            durum3SaldiriIndexleri.Clear();
            if (southAmericaBendeMi(f1))
            {
                //Ordusu diğerlerinin toplamından buyuk olduğunda her tarafa saldıracak...
                if (getToplamDusmanSayisi(f1)/2 < f1.players[f1.turn].getTotalNumberOfArmies())
                {
                    foreach (Bolge b in f1.players[f1.turn].bolgeler)
                    {
                        foreach (Bolge komsu in b.komsular)
{
                            if (b.ordu.askerSayisi > komsu.ordu.askerSayisi && b.sahip != komsu.sahip)
{
                                return true;
                            }
                        }
                    }
                    return false;
                }
                else
                {
                    return false;
                }
            }
            else//Güney Amerikayı ele geçirmeye çalışacak...
            {
                if (southAmericadaToprakVarMi(f1)!=-1)
                {
                    foreach (Bolge b in f1.players[f1.turn].bolgeler)
                    {
                        if (getKomsuDusmanSayisi(b) > 0)
{
                            foreach (Bolge b2 in b.komsular)
{
                                if (b2.sahip != b.sahip)
{
                                    if (b.ordu.askerSayisi > b2.ordu.askerSayisi+10 && buBolgeGuneyAmerikadaMi(b2))
{
                                        return true;
                                    }
                                }
                            }
                        }
                    }
                }
                else//Guney Amerikada Toprak yoksa...
                {
                    Graph graph = new Graph();
                    foreach (Bolge b in f1.bolgeler)
                    {
                        graph.AddNode(b.index.ToString());
                    }
                    foreach (Bolge b in f1.bolgeler)
                    {
                        foreach (Bolge b2 in b.komsular)
{
                            if (b2.sahip != f1.players[f1.turn])
{
                                graph.AddConnection(b.index.ToString(), b2.index.ToString(), b2.ordu.askerSayisi, false);
                            }
                        }
                    }
                    var calculator = new DistanceCalculator();
                    var distances = calculator.CalculateDistances(graph, getEnGucluBolgemIndex(f1).ToString());  // Start from "G"
                    String temp = "";
                    //SA Sınırları
                    List<int> gaSinirlari = new List<int>();
                    gaSinirlari.Add(0);
                    gaSinirlari.Add(0);
                    foreach (var d in distances)
                    {
                        temp += d.Key + " - " + d.Value + "-";
                        if (d.Key == "9")
{
                            gaSinirlari[0] = (int)d.Value;
                        }
                        if (d.Key == "11")
{
                            gaSinirlari[1] = (int)d.Value;
                        }
                    }
                    int min = gaSinirlari.Min();
                    int minIndex = gaSinirlari.IndexOf(min);
                    int minBolgeIndex = 0;
                    if (minIndex == 0)
                    {
                        minBolgeIndex = 9;
                    }
                    if (minIndex == 1)
                    {
                        minBolgeIndex = 11;
                    }
                    List<String> gidilecekyol = new List<String>();
                    //calculator = new DistanceCalculator();
                    gidilecekyol = calculator.getYol(getEnGucluBolgemIndex(f1).ToString(), minBolgeIndex.ToString(), graph);
                    if (f1.bolgeler[getEnGucluBolgemIndex(f1)].ordu.askerSayisi > min + 10)//Gideceğiz Avrupaya
                    {
                        if (f1.bolgeler[getEnGucluBolgemIndex(f1)].komsular.Contains(f1.bolgeler[Convert.ToInt32(gidilecekyol[gidilecekyol.Count - 1])]))
{
                            saldirmaDurumu = 3;
                            durum3SaldiriIndexleri.Add(getEnGucluBolgemIndex(f1));
                            durum3SaldiriIndexleri.Add(Convert.ToInt32(gidilecekyol[gidilecekyol.Count - 1]));
                            return true;
                        }
                        else
{
                            return false;
                        }
                    }
                    else//Biraz daha büyüyeceğiz...
                    {
                        return false;
                    }
                }
                return false;
            }
        }
override List<int> Risk1.AI4.divideArmies (int index1, int index2, GameData form1) [inline, virtual]
Oyuncu bir bölgeyi igal ettikten sonra o bölge ile kendi bölgesi arasındaki askerleri nasıl paylaştıracağına bu metod vasıtasıyla karar verir.
Parameters:
index1 Saldırının gerçekleştiği bölgenin index'i
index2 İşgal edilen bölgenin index'i
Returns:
Geriye iki elemanlı bir liste döndürülecek birinci eleman index1 ile belirttiğimiz bolgede kalacak asker sayısını ikinci eleman ise index2 ile belirttiğimiz bolgede kalacak eleman sayısını gostermelidir.
Implements Risk1.ArtificalIntelligence.
Definition at line 447 of file AI4.cs.
References Risk1.GameData.bolgeler.
        {
            List<int> sonuc = new List<int>();
            int toplam = f1.bolgeler[index1].ordu.askerSayisi + f1.bolgeler[index2].ordu.askerSayisi;
            sonuc.Add(1);
            sonuc.Add(toplam - 1);
            return sonuc;
        }
int Risk1.AI4.dusmanNerede (GameData f1) [inline, private]
Definition at line 117 of file AI4.cs.
References Risk1.GameData.bolgeler, Risk1.GameData.players, and Risk1.GameData.turn.
Referenced by Risk1.AI4.getTerritoriesIndexToPlaceNewArmies().
        {
            List<int> ikibolge=new List<int>();
            ikibolge.Add(13);
            ikibolge.Add(8);
            if (f1.bolgeler[13].sahip != f1.players[f1.turn] && f1.bolgeler[8].sahip != f1.players[f1.turn])
            {
                Random r = new Random();
                if (r.Next(1, 100) % 2 == 0)
                {
                    return ikibolge[0];
                }
                else
                {
                    return ikibolge[1];
                }
            }
            if (f1.bolgeler[13].sahip != f1.players[f1.turn])
            {
                return 13;
            }
            if (f1.bolgeler[8].sahip != f1.players[f1.turn])
            {
                return 8;
            }
            return -1;
        }
override string Risk1.AI4.getName () [inline, virtual]
Bu metod Yapay zekanın ismini döndürmelidir.
Returns:
name
Implements Risk1.ArtificalIntelligence.
Definition at line 18 of file AI4.cs.
References Risk1.AI4.name.
        {
            return name;
        }
override List<int> Risk1.AI4.getSavasBolgeIndexleri (GameData form1) [inline, virtual]
Bu metod savaş yapılacak bolgelerin indexlerini belirlemek içindir.
Returns:
Metod geriye iki elemanlı bir liste döndürür. Birinci eleman nereden saldırı yapılacağını ikinci eleman ise nereye saldırı yapılacağını gösterir. Burada iki bolgenin komsu olmasına dikkat edilmelidir.
Implements Risk1.ArtificalIntelligence.
Definition at line 389 of file AI4.cs.
References Risk1.Ordu.askerSayisi, Risk1.AI4.buBolgeGuneyAmerikadaMi(), Risk1.AI4.durum3SaldiriIndexleri, Risk1.ArtificalIntelligence.getKomsuDusmanSayisi(), Risk1.ArtificalIntelligence.getToplamDusmanSayisi(), Risk1.Bolge.index, Risk1.Bolge.komsular, Risk1.Bolge.ordu, Risk1.GameData.players, Risk1.Bolge.sahip, Risk1.AI4.saldirmaDurumu, Risk1.AI4.southAmericaBendeMi(), Risk1.AI4.southAmericadaToprakVarMi(), and Risk1.GameData.turn.
        {
            List<int> sonuc = new List<int>();
            if (southAmericaBendeMi(f1))
            {
                //Ordusu diğerlerinin toplamından buyuk olduğunda her tarafa saldıracak...
                if (getToplamDusmanSayisi(f1)/2 < f1.players[f1.turn].getTotalNumberOfArmies())
                {
                    foreach (Bolge b in f1.players[f1.turn].bolgeler)
                    {
                        foreach (Bolge komsu in b.komsular)
{
                            if (b.ordu.askerSayisi > komsu.ordu.askerSayisi && b.sahip != komsu.sahip)
{
                                sonuc.Add(b.index);
                                sonuc.Add(komsu.index);
                            }
                        }
                    }
                }
            }
            else//Güney Amerikayı ele geçirmeye çalışacak...
            {
                if (southAmericadaToprakVarMi(f1) != -1)
                {
                    foreach (Bolge b in f1.players[f1.turn].bolgeler)
                    {
                        if (getKomsuDusmanSayisi(b) > 0)
{
                            foreach (Bolge b2 in b.komsular)
{
                                if (b2.sahip != b.sahip)
{
                                    if (b.ordu.askerSayisi > b2.ordu.askerSayisi+10 && buBolgeGuneyAmerikadaMi(b2))
{
                                        sonuc.Add(b.index);
                                        sonuc.Add(b2.index);
                                    }
                                }
                            }
                        }
                    }
                }
                else//Güney amerikayı ele geçirmeye çalışacak...
                {
                    if (saldirmaDurumu == 3)
                    {
                        saldirmaDurumu = 0;
                        return durum3SaldiriIndexleri;
                    }
                }
            }
            return sonuc;
        }
override List<int> Risk1.AI4.getTerritoriesIndexToPlaceNewArmies (GameData form1) [inline, virtual]
Oyuncu her turn'de kazandığı yeni askerleri hangi bolgelere yerleştireceğini bu metod sayesinde belirler.
Parameters:
form1
Returns:
Askerlerin yerleştirilmek istendiği bolge indexleri
Implements Risk1.ArtificalIntelligence.
Definition at line 171 of file AI4.cs.
References Risk1.ArtificalIntelligence.bolgelerimdenRastgeleSec(), Risk1.AI4.dusmanNerede(), Risk1.ArtificalIntelligence.getEnGucluBolgemIndex(), Risk1.ArtificalIntelligence.getKomsuDusmanSayisi(), Risk1.GameData.players, Risk1.AI4.southAmericaBendeMi(), Risk1.AI4.southAmericadaToprakVarMi(), Risk1.AI4.southAmericaSinirindaDusmanVarMi(), and Risk1.GameData.turn.
        {
            List<int> gonderilecekler = new List<int>();
            int territory=bolgelerimdenRastgeleSec(f1);
            if (southAmericaBendeMi(f1))
            {
                if (southAmericaSinirindaDusmanVarMi(f1))
                {
                    if (dusmanNerede(f1) == 13)
                    {
                        territory = 11;
                    }
                    else if (dusmanNerede(f1) == 8)
                    {
                        territory = 9;
                    }
                }
                else
                {
                    Random r = new Random();
                    List<Bolge> komsuluktaDusmanOlanBolgeler = new List<Bolge>();
                    foreach (Bolge bb in f1.players[f1.turn].bolgeler)
                    {
                        if (getKomsuDusmanSayisi(bb) > 0)
{
                            komsuluktaDusmanOlanBolgeler.Add(bb);
                        }
                    }
                    int z = r.Next(0, komsuluktaDusmanOlanBolgeler.Count - 1);
                    territory = komsuluktaDusmanOlanBolgeler[z].index;
                }
            }
            else
            {
                if (southAmericadaToprakVarMi(f1)!=-1)//Evet var
                {
                    territory = southAmericadaToprakVarMi(f1);
                }
                else//yok
                {
                    territory = getEnGucluBolgemIndex(f1);
                }
            }
            int k = f1.players[f1.turn].yeniAskerler;
            for (int i = 0; i < k; i++)
            {
                gonderilecekler.Add(territory);
            }
            return gonderilecekler;
        }
override int Risk1.AI4.getTerritoryToPlaceFirstArmies (GameData form1) [inline, virtual]
İlk başta tüm oyunculara verilen ilk askerler dağıtılırken her oyuncuya tek tek askerlerini nereye koyması gerektiği sorulur bu metod ilk ordunun koyulması gereken bolgenin indexini dondurur.
Parameters:
form1
Returns:
ilk ordunun koyulması gereken bolgenin indexini dondurur
Implements Risk1.ArtificalIntelligence.
Definition at line 45 of file AI4.cs.
References Risk1.ArtificalIntelligence.getEnGucluBolgemIndex(), and Risk1.Bolge.index.
        {
            List<int> sahipoldugubolgeler = new List<int>();
            foreach (Bolge b in f1.players[f1.turn].bolgeler)
            {
                sahipoldugubolgeler.Add(b.index);
            }
            Random r = new Random();
            int sayi = r.Next(0, sahipoldugubolgeler.Count - 1);
            int index = getEnGucluBolgemIndex(f1);
            if (sahipoldugubolgeler.Contains(9))
            {
                return f1.bolgeler[9].index;
            }
            if (sahipoldugubolgeler.Contains(10))
            {
                return f1.bolgeler[10].index;
            }
            if (sahipoldugubolgeler.Contains(11))
            {
                return f1.bolgeler[11].index;
            }
            if (sahipoldugubolgeler.Contains(12))
            {
                return f1.bolgeler[12].index;
            }
            return f1.bolgeler[index].index;
        }
override int Risk1.AI4.requestTerritory (GameData form1) [inline, virtual]
Bu metod bölgeler seçilirken istenen bolgenin indexini dondurmektedir.
Parameters:
form1
Returns:
istenen bolgenin indexi
Implements Risk1.ArtificalIntelligence.
Definition at line 23 of file AI4.cs.
References Risk1.GameData.bolgeler, and Risk1.ArtificalIntelligence.rastgeleBolgeSec().
        {
            if (!f1.bolgeler[9].sahipli)
            {
                return 9;
            }
            if (!f1.bolgeler[10].sahipli)
            {
                return 10;
            }
            if (!f1.bolgeler[11].sahipli)
            {
                return 11;
            }
            if (!f1.bolgeler[12].sahipli)
            {
                return 12;
            }
            return rastgeleBolgeSec(f1);
        }
override bool Risk1.AI4.saldiracanMi (GameData form1) [inline, virtual]
Bu metod kullanıcının saldırı yapmak isteyip istemediğini belirler.
Parameters:
form1
Returns:
Eğer saldırı yapmak istiyorsa true istemiyorsa false döndürür.
Implements Risk1.ArtificalIntelligence.
Definition at line 383 of file AI4.cs.
References Risk1.AI4.devam().
        {
            return devam(f1);
        }
bool Risk1.AI4.southAmericaBendeMi (GameData f1) [inline, private]
Definition at line 80 of file AI4.cs.
References Risk1.GameData.bolgeler, Risk1.GameData.players, and Risk1.GameData.turn.
Referenced by Risk1.AI4.devam(), Risk1.AI4.getSavasBolgeIndexleri(), and Risk1.AI4.getTerritoriesIndexToPlaceNewArmies().
        {
            if (f1.bolgeler[9].sahip != f1.players[f1.turn])
            {
                return false;
            }
            if (f1.bolgeler[10].sahip != f1.players[f1.turn])
            {
                return false;
            }
            if (f1.bolgeler[11].sahip != f1.players[f1.turn])
            {
                return false;
            }
            if (f1.bolgeler[12].sahip != f1.players[f1.turn])
            {
                return false;
            }
            return true;
        }
int Risk1.AI4.southAmericadaToprakVarMi (GameData f1) [inline, private]
Definition at line 148 of file AI4.cs.
References Risk1.GameData.bolgeler, Risk1.GameData.players, and Risk1.GameData.turn.
Referenced by Risk1.AI4.devam(), Risk1.AI4.getSavasBolgeIndexleri(), and Risk1.AI4.getTerritoriesIndexToPlaceNewArmies().
        {
            //9 10 11 12
            if (f1.bolgeler[9].sahip == f1.players[f1.turn])
            {
                return 9;
            }
            if (f1.bolgeler[10].sahip == f1.players[f1.turn])
            {
                return 10;
            }
            if (f1.bolgeler[11].sahip == f1.players[f1.turn])
            {
                return 11;
            }
            if (f1.bolgeler[12].sahip == f1.players[f1.turn])
            {
                return 12;
            }
            return -1;
        }
bool Risk1.AI4.southAmericaSinirindaDusmanVarMi (GameData f1) [inline, private]
Definition at line 102 of file AI4.cs.
References Risk1.GameData.bolgeler, Risk1.GameData.players, and Risk1.GameData.turn.
Referenced by Risk1.AI4.getTerritoriesIndexToPlaceNewArmies().
        {
            //13 ve 8
            if (f1.bolgeler[13].sahip != f1.players[f1.turn])
            {
                return true;
            }
            if (f1.bolgeler[8].sahip != f1.players[f1.turn])
            {
                return true;
            }
            return false;
        }
Member Data Documentation
int Risk1.AI4.aiid = 4 [static]
Definition at line 11 of file AI4.cs.
Referenced by Risk1.ChangePlayer.HangiYapayZekaSecili().
List<int> Risk1.AI4.durum3SaldiriIndexleri = new List<int>(2)
Definition at line 16 of file AI4.cs.
Referenced by Risk1.AI4.devam(), and Risk1.AI4.getSavasBolgeIndexleri().
string Risk1.AI4.name = "Fatih Sultan Mehmet" [static]
Definition at line 12 of file AI4.cs.
Referenced by Risk1.AI4.getName(), and Risk1.ChangePlayer.HangiYapayZekaSecili().
Image Risk1.AI4.resim = Properties.Resources.fatih [static]
Definition at line 13 of file AI4.cs.
Referenced by Risk1.ChangePlayer.HangiYapayZekaSecili().
int Risk1.AI4.saldirmaDurumu = 0
Definition at line 15 of file AI4.cs.
Referenced by Risk1.AI4.devam(), and Risk1.AI4.getSavasBolgeIndexleri().
The documentation for this class was generated from the following file:
Risk1/AI4.cs