ANKARISK: Risk1.SaldiriEkrani Class Reference
Risk1.SaldiriEkrani Class Reference
Public Member Functions
SaldiriEkrani (Bolge b1, Bolge b2, Form1 f1)
void refreshSaldiriEkrani ()
void warDoORDieForAi ()
void warDoORDie ()
void warAttack ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void SaldiriEkrani_Load (object sender, EventArgs e)
void button1_Click (object sender, EventArgs e)
void button2_Click (object sender, EventArgs e)
void button3_Click (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
Bolge bolge1 = null
Bolge bolge2 = null
Form1 form1 = null
int randomAraligi = 20
Random random = new Random()
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.Panel panel1
System.Windows.Forms.Panel panel2
System.Windows.Forms.Button button1
System.Windows.Forms.Button button2
System.Windows.Forms.Button button3
System.Windows.Forms.TextBox textBox2
System.Windows.Forms.TextBox textBox3
System.Windows.Forms.TextBox textBox4
System.Windows.Forms.TextBox textBox1
Detailed Description
Definition at line 12 of file SaldiriEkrani.cs.
Constructor & Destructor Documentation
Risk1.SaldiriEkrani.SaldiriEkrani (Bolge b1, Bolge b2, Form1 f1) [inline]
Definition at line 19 of file SaldiriEkrani.cs.
References Risk1.SaldiriEkrani.bolge1, Risk1.SaldiriEkrani.bolge2, Risk1.SaldiriEkrani.form1, and Risk1.SaldiriEkrani.InitializeComponent().
        {
            InitializeComponent();
            bolge1 = b1;
            bolge2 = b2;
            form1 = f1;
        }
Member Function Documentation
void Risk1.SaldiriEkrani.button1_Click (object sender, EventArgs e) [inline, private]
Definition at line 44 of file SaldiriEkrani.cs.
References Risk1.SaldiriEkrani.warAttack().
        {
            warAttack();
        }
void Risk1.SaldiriEkrani.button2_Click (object sender, EventArgs e) [inline, private]
Definition at line 237 of file SaldiriEkrani.cs.
References Risk1.SaldiriEkrani.warDoORDie().
        {
            warDoORDie();
        }
void Risk1.SaldiriEkrani.button3_Click (object sender, EventArgs e) [inline, private]
Definition at line 242 of file SaldiriEkrani.cs.
        {
            Close();
        }
override void Risk1.SaldiriEkrani.Dispose (bool disposing) [inline, protected]
Clean up any resources being used.
Parameters:
disposing true if managed resources should be disposed; otherwise, false.
Definition at line 14 of file SaldiriEkrani.Designer.cs.
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }
void Risk1.SaldiriEkrani.InitializeComponent () [inline, private]
Required method for Designer support - do not modify the contents of this method with the code editor.
Definition at line 29 of file SaldiriEkrani.Designer.cs.
Referenced by Risk1.SaldiriEkrani.SaldiriEkrani().
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(SaldiriEkrani));
            this.panel1 = new System.Windows.Forms.Panel();
            this.textBox4 = new System.Windows.Forms.TextBox();
            this.textBox2 = new System.Windows.Forms.TextBox();
            this.panel2 = new System.Windows.Forms.Panel();
            this.textBox1 = new System.Windows.Forms.TextBox();
            this.textBox3 = new System.Windows.Forms.TextBox();
            this.button1 = new System.Windows.Forms.Button();
            this.button2 = new System.Windows.Forms.Button();
            this.button3 = new System.Windows.Forms.Button();
            this.panel1.SuspendLayout();
            this.panel2.SuspendLayout();
            this.SuspendLayout();
            //
            // panel1
            //
            this.panel1.BackColor = System.Drawing.Color.Transparent;
            this.panel1.Controls.Add(this.textBox4);
            this.panel1.Controls.Add(this.textBox2);
            this.panel1.Location = new System.Drawing.Point(31, 23);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(142, 77);
            this.panel1.TabIndex = 0;
            //
            // textBox4
            //
            this.textBox4.BackColor = System.Drawing.Color.Black;
            this.textBox4.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.textBox4.ForeColor = System.Drawing.Color.White;
            this.textBox4.Location = new System.Drawing.Point(0, 15);
            this.textBox4.Name = "textBox4";
            this.textBox4.ReadOnly = true;
            this.textBox4.Size = new System.Drawing.Size(142, 20);
            this.textBox4.TabIndex = 4;
            this.textBox4.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            //
            // textBox2
            //
            this.textBox2.BackColor = System.Drawing.Color.DimGray;
            this.textBox2.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.textBox2.ForeColor = System.Drawing.Color.White;
            this.textBox2.Location = new System.Drawing.Point(40, 46);
            this.textBox2.Name = "textBox2";
            this.textBox2.ReadOnly = true;
            this.textBox2.Size = new System.Drawing.Size(56, 21);
            this.textBox2.TabIndex = 1;
            this.textBox2.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            //
            // panel2
            //
            this.panel2.BackColor = System.Drawing.Color.Transparent;
            this.panel2.Controls.Add(this.textBox1);
            this.panel2.Controls.Add(this.textBox3);
            this.panel2.Location = new System.Drawing.Point(242, 23);
            this.panel2.Name = "panel2";
            this.panel2.Size = new System.Drawing.Size(142, 77);
            this.panel2.TabIndex = 1;
            //
            // textBox1
            //
            this.textBox1.BackColor = System.Drawing.Color.Black;
            this.textBox1.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.textBox1.ForeColor = System.Drawing.Color.White;
            this.textBox1.Location = new System.Drawing.Point(0, 15);
            this.textBox1.Name = "textBox1";
            this.textBox1.ReadOnly = true;
            this.textBox1.Size = new System.Drawing.Size(142, 20);
            this.textBox1.TabIndex = 3;
            this.textBox1.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            //
            // textBox3
            //
            this.textBox3.BackColor = System.Drawing.Color.DimGray;
            this.textBox3.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.textBox3.ForeColor = System.Drawing.Color.White;
            this.textBox3.Location = new System.Drawing.Point(42, 46);
            this.textBox3.Name = "textBox3";
            this.textBox3.ReadOnly = true;
            this.textBox3.Size = new System.Drawing.Size(56, 21);
            this.textBox3.TabIndex = 2;
            this.textBox3.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            //
            // button1
            //
            this.button1.BackColor = System.Drawing.Color.Red;
            this.button1.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.button1.ForeColor = System.Drawing.Color.White;
            this.button1.Location = new System.Drawing.Point(31, 124);
            this.button1.Name = "button1";
            this.button1.Size = new System.Drawing.Size(100, 30);
            this.button1.TabIndex = 2;
            this.button1.Text = "Attack";
            this.button1.UseVisualStyleBackColor = false;
            this.button1.Click += new System.EventHandler(this.button1_Click);
            //
            // button2
            //
            this.button2.BackColor = System.Drawing.Color.DarkRed;
            this.button2.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.button2.ForeColor = System.Drawing.Color.White;
            this.button2.Location = new System.Drawing.Point(155, 124);
            this.button2.Name = "button2";
            this.button2.Size = new System.Drawing.Size(100, 30);
            this.button2.TabIndex = 3;
            this.button2.Text = "Do or Die";
            this.button2.UseVisualStyleBackColor = false;
            this.button2.Click += new System.EventHandler(this.button2_Click);
            //
            // button3
            //
            this.button3.BackColor = System.Drawing.Color.IndianRed;
            this.button3.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.button3.ForeColor = System.Drawing.Color.White;
            this.button3.Location = new System.Drawing.Point(284, 124);
            this.button3.Name = "button3";
            this.button3.Size = new System.Drawing.Size(100, 30);
            this.button3.TabIndex = 4;
            this.button3.Text = "Retreat";
            this.button3.UseVisualStyleBackColor = false;
            this.button3.Click += new System.EventHandler(this.button3_Click);
            //
            // SaldiriEkrani
            //
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.Gainsboro;
            this.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("$this.BackgroundImage")));
            this.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.ClientSize = new System.Drawing.Size(407, 164);
            this.Controls.Add(this.button3);
            this.Controls.Add(this.button2);
            this.Controls.Add(this.button1);
            this.Controls.Add(this.panel2);
            this.Controls.Add(this.panel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "SaldiriEkrani";
            this.Opacity = 0.95D;
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = "WAR";
            this.Load += new System.EventHandler(this.SaldiriEkrani_Load);
            this.panel1.ResumeLayout(false);
            this.panel1.PerformLayout();
            this.panel2.ResumeLayout(false);
            this.panel2.PerformLayout();
            this.ResumeLayout(false);
        }
void Risk1.SaldiriEkrani.refreshSaldiriEkrani () [inline]
Definition at line 27 of file SaldiriEkrani.cs.
References Risk1.SaldiriEkrani.textBox2, and Risk1.SaldiriEkrani.textBox3.
Referenced by Risk1.SaldiriEkrani.warDoORDie(), and Risk1.SaldiriEkrani.warDoORDieForAi().
        {
            textBox2.Refresh();
            textBox3.Refresh();
        }
void Risk1.SaldiriEkrani.SaldiriEkrani_Load (object sender, EventArgs e) [inline, private]
Definition at line 33 of file SaldiriEkrani.cs.
References Risk1.Ordu.askerSayisi, Risk1.SaldiriEkrani.bolge1, Risk1.SaldiriEkrani.bolge2, Risk1.SaldiriEkrani.button1, Risk1.Player.color, Risk1.Bolge.isim, Risk1.Bolge.ordu, Risk1.SaldiriEkrani.panel1, Risk1.SaldiriEkrani.panel2, Risk1.Bolge.sahip, Risk1.SaldiriEkrani.textBox1, Risk1.SaldiriEkrani.textBox2, Risk1.SaldiriEkrani.textBox3, and Risk1.SaldiriEkrani.textBox4.
        {
            panel1.BackColor = bolge1.sahip.color;
            panel2.BackColor = bolge2.sahip.color;
            textBox4.Text = bolge1.isim;
            textBox1.Text = bolge2.isim;
            textBox2.Text = bolge1.ordu.askerSayisi.ToString();
            textBox3.Text = bolge2.ordu.askerSayisi.ToString();
            this.ActiveControl = button1;
        }
void Risk1.SaldiriEkrani.warAttack () [inline]
Definition at line 175 of file SaldiriEkrani.cs.
References Risk1.Ordu.askerSayisi, Risk1.SaldiriEkrani.bolge1, Risk1.SaldiriEkrani.bolge2, Risk1.Player.bolgeler, Risk1.Form1.changeLabel(), Risk1.Form1.changeTerritoryColor(), Risk1.SaldiriEkrani.form1, Risk1.Form1.isArmyMoved, Risk1.Bolge.ordu, Risk1.SaldiriEkrani.random, Risk1.SaldiriEkrani.randomAraligi, Risk1.Bolge.sahip, Risk1.SaldiriEkrani.textBox2, and Risk1.SaldiriEkrani.textBox3.
Referenced by Risk1.SaldiriEkrani.button1_Click().
        {
            if (bolge1.ordu.askerSayisi > 1 && bolge2.ordu.askerSayisi > 0)
            {
                Random random = new Random();
                int bb1;
                int bb2;
                bb1 = random.Next(1, randomAraligi + (bolge1.ordu.askerSayisi / 5));
                bb2 = random.Next(1, randomAraligi + (bolge2.ordu.askerSayisi / 5));
                if (bb1 > bb2)
                {
                    bolge2.ordu.askerSayisi--;
                    form1.changeLabel(bolge2);
                    textBox3.Text = bolge2.ordu.askerSayisi.ToString();
                    if (bolge2.ordu.askerSayisi == 0)
                    {
                        bolge2.sahip.bolgeler.Remove(bolge2);
                        bolge1.sahip.bolgeler.Add(bolge2);
                        bolge2.sahip = bolge1.sahip;
                        bolge1.ordu.askerSayisi--;
                        bolge2.ordu.askerSayisi++;
                        this.Visible = false;
                        int b1 = bolge1.ordu.askerSayisi;
                        int b2 = bolge2.ordu.askerSayisi;
                        ArmyMove am = new ArmyMove(bolge1, bolge2, form1);
                        am.ShowDialog();
                        if (form1.isArmyMoved)
{
                            form1.changeLabel(bolge1);
                            form1.changeLabel(bolge2);
                            form1.isArmyMoved = false;
                        }
                        else
{
                            form1.changeLabel(bolge1);
                            form1.changeLabel(bolge2);
                            bolge1.ordu.askerSayisi = b1;
                            bolge2.ordu.askerSayisi = b2;
                        }
                        form1.changeLabel(bolge1);
                        form1.changeLabel(bolge2);
                        form1.changeTerritoryColor(bolge2, bolge2.sahip);
                    }
                }
                else if (bb1 < bb2)
                {
                    bolge1.ordu.askerSayisi--;
                    form1.changeLabel(bolge1);
                    textBox2.Text = bolge1.ordu.askerSayisi.ToString();
                }
                else
                {
                    //Devam..
                }
            }
        }
void Risk1.SaldiriEkrani.warDoORDie () [inline]
Definition at line 107 of file SaldiriEkrani.cs.
References Risk1.Ordu.askerSayisi, Risk1.SaldiriEkrani.bolge1, Risk1.SaldiriEkrani.bolge2, Risk1.Player.bolgeler, Risk1.Form1.changeLabel(), Risk1.Form1.changeTerritoryColor(), Risk1.SaldiriEkrani.form1, Risk1.Form1.isArmyMoved, Risk1.Bolge.isim, Risk1.Bolge.ordu, Risk1.SaldiriEkrani.random, Risk1.SaldiriEkrani.randomAraligi, Risk1.Form1.refreshGame(), Risk1.SaldiriEkrani.refreshSaldiriEkrani(), Risk1.Bolge.sahip, Risk1.SaldiriEkrani.textBox2, and Risk1.SaldiriEkrani.textBox3.
Referenced by Risk1.SaldiriEkrani.button2_Click().
        {
            string temp = "";
            temp += bolge1.isim + ":" + bolge1.ordu.askerSayisi.ToString() + "\n";
            temp += bolge2.isim + ":" + bolge2.ordu.askerSayisi.ToString() + "\n---------\n";
            while (bolge1.ordu.askerSayisi > 1 && bolge2.ordu.askerSayisi > 0)
            {
                int bb1;
                int bb2;
                bb1 = random.Next(1, randomAraligi + (bolge1.ordu.askerSayisi / 5));
                System.Threading.Thread.Sleep(20);
                for (int i = 1; i <= 11; i++) { random.Next();}
                bb2 = random.Next(1, randomAraligi + (bolge2.ordu.askerSayisi / 5));
                temp += bb1.ToString() + " - " + bb2.ToString() + "\n";
                if (bb1 > bb2)
                {
                    bolge2.ordu.askerSayisi--;
                    form1.changeLabel(bolge2);
                    textBox3.Text=bolge2.ordu.askerSayisi.ToString();
                    if (bolge2.ordu.askerSayisi == 0)
                    {
                        bolge2.sahip.bolgeler.Remove(bolge2);
                        bolge1.sahip.bolgeler.Add(bolge2);
                        bolge2.sahip = bolge1.sahip;
                        bolge1.ordu.askerSayisi--;
                        bolge2.ordu.askerSayisi++;
                        this.Visible = false;
                        int b1 = bolge1.ordu.askerSayisi;
                        int b2 = bolge2.ordu.askerSayisi;
                        ArmyMove am = new ArmyMove(bolge1, bolge2, form1);
                        am.ShowDialog();
                        if (form1.isArmyMoved)
{
                            form1.changeLabel(bolge1);
                            form1.changeLabel(bolge2);
                            form1.isArmyMoved = false;
                        }
                        else
{
                            bolge1.ordu.askerSayisi = b1;
                            bolge2.ordu.askerSayisi = b2;
                            form1.changeLabel(bolge1);
                            form1.changeLabel(bolge2);
                        }
                        form1.changeTerritoryColor(bolge2, bolge2.sahip);
                        break;
                    }
                }
                if (bb1 < bb2)
                {
                    bolge1.ordu.askerSayisi--;
                    form1.changeLabel(bolge1);
                    textBox2.Text = bolge1.ordu.askerSayisi.ToString();
                }
                refreshSaldiriEkrani();
                form1.refreshGame();
            }
            //MessageBox.Show(temp);
        }
void Risk1.SaldiriEkrani.warDoORDieForAi () [inline]
Definition at line 49 of file SaldiriEkrani.cs.
References Risk1.Ordu.askerSayisi, Risk1.SaldiriEkrani.bolge1, Risk1.SaldiriEkrani.bolge2, Risk1.Player.bolgeler, Risk1.Form1.changeLabel(), Risk1.Form1.changeTerritoryColor(), Risk1.SaldiriEkrani.form1, Risk1.Form1.getGameData(), Risk1.Bolge.index, Risk1.Bolge.isim, Risk1.Bolge.ordu, Risk1.Form1.players, Risk1.SaldiriEkrani.random, Risk1.SaldiriEkrani.randomAraligi, Risk1.Form1.refreshGame(), Risk1.SaldiriEkrani.refreshSaldiriEkrani(), Risk1.Bolge.sahip, Risk1.SaldiriEkrani.textBox2, Risk1.SaldiriEkrani.textBox3, Risk1.Form1.turn, and Risk1.Form1.yapayzekalar.
Referenced by Risk1.Form1.changeTurn().
        {
            string temp = "";
            temp += bolge1.isim + ":" + bolge1.ordu.askerSayisi.ToString()+"\n";
            temp += bolge2.isim + ":" + bolge2.ordu.askerSayisi.ToString() + "\n---------\n";
            while (bolge1.ordu.askerSayisi > 1 && bolge2.ordu.askerSayisi > 0)
            {
                int bb1;
                int bb2;
                bb1 = random.Next(1, randomAraligi + (bolge1.ordu.askerSayisi / 5));
                System.Threading.Thread.Sleep(20);
                for (int i = 1; i <= 11; i++) { random.Next(); }
                bb2 = random.Next(1, randomAraligi + (bolge2.ordu.askerSayisi / 5));
                temp += bb1.ToString() + " - " + bb2.ToString() + "\n";
                if (bb1 > bb2)
                {
                    bolge2.ordu.askerSayisi--;
                    form1.changeLabel(bolge2);
                    textBox3.Text = bolge2.ordu.askerSayisi.ToString();
                    if (bolge2.ordu.askerSayisi == 0)
                    {
                        bolge2.sahip.bolgeler.Remove(bolge2);
                        bolge1.sahip.bolgeler.Add(bolge2);
                        bolge2.sahip = bolge1.sahip;
                        bolge1.ordu.askerSayisi--;
                        bolge2.ordu.askerSayisi++;
                        List<int> bolmeTalimati = new List<int>();
                        bolmeTalimati = form1.yapayzekalar[form1.players[form1.turn].aiId - 1].divideArmies(bolge1.index, bolge2.index,form1.getGameData());
                        if ((bolge1.ordu.askerSayisi + bolge2.ordu.askerSayisi) == (bolmeTalimati[0] + bolmeTalimati[1]))
{
                            bolge1.ordu.askerSayisi = bolmeTalimati[0];
                            bolge2.ordu.askerSayisi = bolmeTalimati[1];
                        }
                        form1.changeLabel(bolge1);
                        form1.changeLabel(bolge2);
                        form1.changeTerritoryColor(bolge2, bolge2.sahip);
                        break;
                    }
                }
                if (bb1 < bb2)//Savunma yapan eşitlik durumunda daha üstün
                {
                    bolge1.ordu.askerSayisi--;
                    form1.changeLabel(bolge1);
                    textBox2.Text = bolge1.ordu.askerSayisi.ToString();
                }
                refreshSaldiriEkrani();
                form1.refreshGame();
            }
            //MessageBox.Show(temp);
        }
Member Data Documentation
Bolge Risk1.SaldiriEkrani.bolge1 = null [private]
Definition at line 14 of file SaldiriEkrani.cs.
Referenced by Risk1.SaldiriEkrani.SaldiriEkrani(), Risk1.SaldiriEkrani.SaldiriEkrani_Load(), Risk1.SaldiriEkrani.warAttack(), Risk1.SaldiriEkrani.warDoORDie(), and Risk1.SaldiriEkrani.warDoORDieForAi().
Bolge Risk1.SaldiriEkrani.bolge2 = null [private]
Definition at line 15 of file SaldiriEkrani.cs.
Referenced by Risk1.SaldiriEkrani.SaldiriEkrani(), Risk1.SaldiriEkrani.SaldiriEkrani_Load(), Risk1.SaldiriEkrani.warAttack(), Risk1.SaldiriEkrani.warDoORDie(), and Risk1.SaldiriEkrani.warDoORDieForAi().
System.Windows.Forms.Button Risk1.SaldiriEkrani.button1 [private]
Definition at line 186 of file SaldiriEkrani.Designer.cs.
Referenced by Risk1.SaldiriEkrani.SaldiriEkrani_Load().
System.Windows.Forms.Button Risk1.SaldiriEkrani.button2 [private]
Definition at line 187 of file SaldiriEkrani.Designer.cs.
System.Windows.Forms.Button Risk1.SaldiriEkrani.button3 [private]
Definition at line 188 of file SaldiriEkrani.Designer.cs.
System.ComponentModel.IContainer Risk1.SaldiriEkrani.components = null [private]
Required designer variable.
Definition at line 8 of file SaldiriEkrani.Designer.cs.
Form1 Risk1.SaldiriEkrani.form1 = null [private]
Definition at line 16 of file SaldiriEkrani.cs.
Referenced by Risk1.SaldiriEkrani.SaldiriEkrani(), Risk1.SaldiriEkrani.warAttack(), Risk1.SaldiriEkrani.warDoORDie(), and Risk1.SaldiriEkrani.warDoORDieForAi().
System.Windows.Forms.Panel Risk1.SaldiriEkrani.panel1 [private]
Definition at line 184 of file SaldiriEkrani.Designer.cs.
Referenced by Risk1.SaldiriEkrani.SaldiriEkrani_Load().
System.Windows.Forms.Panel Risk1.SaldiriEkrani.panel2 [private]
Definition at line 185 of file SaldiriEkrani.Designer.cs.
Referenced by Risk1.SaldiriEkrani.SaldiriEkrani_Load().
Random Risk1.SaldiriEkrani.random = new Random() [private]
Definition at line 105 of file SaldiriEkrani.cs.
Referenced by Risk1.SaldiriEkrani.warAttack(), Risk1.SaldiriEkrani.warDoORDie(), and Risk1.SaldiriEkrani.warDoORDieForAi().
int Risk1.SaldiriEkrani.randomAraligi = 20 [private]
Definition at line 17 of file SaldiriEkrani.cs.
Referenced by Risk1.SaldiriEkrani.warAttack(), Risk1.SaldiriEkrani.warDoORDie(), and Risk1.SaldiriEkrani.warDoORDieForAi().
System.Windows.Forms.TextBox Risk1.SaldiriEkrani.textBox1 [private]
Definition at line 192 of file SaldiriEkrani.Designer.cs.
Referenced by Risk1.SaldiriEkrani.SaldiriEkrani_Load().
System.Windows.Forms.TextBox Risk1.SaldiriEkrani.textBox2 [private]
Definition at line 189 of file SaldiriEkrani.Designer.cs.
Referenced by Risk1.SaldiriEkrani.refreshSaldiriEkrani(), Risk1.SaldiriEkrani.SaldiriEkrani_Load(), Risk1.SaldiriEkrani.warAttack(), Risk1.SaldiriEkrani.warDoORDie(), and Risk1.SaldiriEkrani.warDoORDieForAi().
System.Windows.Forms.TextBox Risk1.SaldiriEkrani.textBox3 [private]
Definition at line 190 of file SaldiriEkrani.Designer.cs.
Referenced by Risk1.SaldiriEkrani.refreshSaldiriEkrani(), Risk1.SaldiriEkrani.SaldiriEkrani_Load(), Risk1.SaldiriEkrani.warAttack(), Risk1.SaldiriEkrani.warDoORDie(), and Risk1.SaldiriEkrani.warDoORDieForAi().
System.Windows.Forms.TextBox Risk1.SaldiriEkrani.textBox4 [private]
Definition at line 191 of file SaldiriEkrani.Designer.cs.
Referenced by Risk1.SaldiriEkrani.SaldiriEkrani_Load().
The documentation for this class was generated from the following files:
Risk1/SaldiriEkrani.cs
Risk1/SaldiriEkrani.Designer.cs