ANKARISK: Risk1.Bolge Class Reference
Risk1.Bolge Class Reference
Public Member Functions
Bolge (List< Nokta > nok, String ad)
Bolge ()
Color getColor ()
Public Attributes
List< Nokta > noktalar = new List<Nokta>()
String isim = ""
Bölgenin ismini döndürür.
List< Bolge > komsular = new List<Bolge>()
Komşu bölgelerin listesini tutar.
bool sahipli = false
Bölgenin sahipli olup olmadığını belirtir.
Player sahip
Bölgenin sahibi olan oyuncuyu döndürür.
Ordu ordu = new Ordu()
Asker sayısına Erişmek için kullanılır.
int number
Bölgenin numarasını belirtir.
int index
Bölgenin listedeki yerini belirtir.
Detailed Description
Definition at line 9 of file Bolge.cs.
Constructor & Destructor Documentation
Risk1.Bolge.Bolge (List< Nokta > nok, String ad) [inline]
Definition at line 11 of file Bolge.cs.
References Risk1.Bolge.isim, and Risk1.Bolge.noktalar.
        {
            this.noktalar = nok;
            this.isim = ad;
        }
Risk1.Bolge.Bolge () [inline]
Definition at line 17 of file Bolge.cs.
{}
Member Function Documentation
Color Risk1.Bolge.getColor () [inline]
Definition at line 50 of file Bolge.cs.
References Risk1.Bolge.noktalar.
        {
            if (noktalar.Count > 0)
                return noktalar[0].renk;
            else
                return Color.SaddleBrown;
        }
Member Data Documentation
int Risk1.Bolge.index
Bölgenin listedeki yerini belirtir.
Definition at line 47 of file Bolge.cs.
Referenced by Risk1.AI.askerTransferiYap(), Risk1.AI3.askerTransferiYap(), Risk1.AI4.askerTransferiYap(), Risk1.AI2.askerTransferiYap(), Risk1.AI2.avrupaBendeMi(), Risk1.AI2.avrupadaToprakVarMi(), Risk1.ArtificalIntelligence.bolgelerimdenRastgeleSec(), Risk1.AI2.buBolgeAvrupadaMi(), Risk1.AI4.buBolgeGuneyAmerikadaMi(), Risk1.AI4.devam(), Risk1.AI2.devam(), Risk1.Form1.Form1_Load(), Risk1.ArtificalIntelligence.getEnGucluBolgemIndex(), Risk1.AI.getSavasBolgeIndexleri(), Risk1.AI3.getSavasBolgeIndexleri(), Risk1.AI4.getSavasBolgeIndexleri(), Risk1.AI2.getSavasBolgeIndexleri(), Risk1.AI3.getTerritoriesIndexToPlaceNewArmies(), Risk1.AI2.getTerritoriesIndexToPlaceNewArmies(), Risk1.AI3.getTerritoryToPlaceFirstArmies(), Risk1.AI4.getTerritoryToPlaceFirstArmies(), Risk1.AI2.getTerritoryToPlaceFirstArmies(), Risk1.ArtificalIntelligence.rastgeleBolgeSec(), and Risk1.SaldiriEkrani.warDoORDieForAi().
String Risk1.Bolge.isim = ""
Bölgenin ismini döndürür.
Definition at line 23 of file Bolge.cs.
Referenced by Risk1.ArmyMove.ArmyMove_Load(), Risk1.Bolge.Bolge(), Risk1.Form1.changeTurn(), Risk1.Form1.pictureBox1_Click(), Risk1.SaldiriEkrani.SaldiriEkrani_Load(), Risk1.SaldiriEkrani.warDoORDie(), and Risk1.SaldiriEkrani.warDoORDieForAi().
List<Bolge> Risk1.Bolge.komsular = new List<Bolge>()
Komşu bölgelerin listesini tutar.
Definition at line 27 of file Bolge.cs.
Referenced by Risk1.AI.askerTransferiYap(), Risk1.AI3.askerTransferiYap(), Risk1.AI4.askerTransferiYap(), Risk1.AI2.askerTransferiYap(), Risk1.AI.devam(), Risk1.AI3.devam(), Risk1.AI4.devam(), Risk1.AI2.devam(), Risk1.AI3.getDahaGucluDusmanSayisi(), Risk1.AI2.getDahaGucluDusmanSayisi(), Risk1.ArtificalIntelligence.getDostSayisi(), Risk1.ArtificalIntelligence.getKomsuDusmanSayisi(), Risk1.AI.getSavasBolgeIndexleri(), Risk1.AI3.getSavasBolgeIndexleri(), Risk1.AI4.getSavasBolgeIndexleri(), Risk1.AI2.getSavasBolgeIndexleri(), and Risk1.Form1.pictureBox1_Click().
List<Nokta> Risk1.Bolge.noktalar = new List<Nokta>()
Definition at line 19 of file Bolge.cs.
Referenced by Risk1.Bolge.Bolge(), Risk1.Form1.Form1_Load(), Risk1.Bolge.getColor(), and Risk1.Form1.pictureBox1_Click().
int Risk1.Bolge.number
Bölgenin numarasını belirtir.
Definition at line 43 of file Bolge.cs.
Referenced by Risk1.Form1.changeLabel(), and Risk1.Form1.Form1_Load().
Ordu Risk1.Bolge.ordu = new Ordu()
Asker sayısına Erişmek için kullanılır.
Definition at line 39 of file Bolge.cs.
Referenced by Risk1.ArmyMove.ArmyMove_Load(), Risk1.AI.askerTransferiYap(), Risk1.AI3.askerTransferiYap(), Risk1.AI4.askerTransferiYap(), Risk1.AI2.askerTransferiYap(), Risk1.AI.askerTransferiYapacakmisin(), Risk1.AI3.askerTransferiYapacakmisin(), Risk1.AI4.askerTransferiYapacakmisin(), Risk1.AI2.askerTransferiYapacakmisin(), Risk1.ArmyMove.bolge1Azalt(), Risk1.ArmyMove.bolge2Azalt(), Risk1.ArmyMove.button1_Click(), Risk1.ArmyMove.button2_Click(), Risk1.Form1.changeLabel(), Risk1.Form1.changeTurn(), Risk1.AI.devam(), Risk1.AI3.devam(), Risk1.AI4.devam(), Risk1.AI2.devam(), Risk1.AI2.getAvrupadakiAskerSayisi(), Risk1.AI2.getAvrupadakiDusmanSayisi(), Risk1.AI3.getDahaGucluDusmanSayisi(), Risk1.AI2.getDahaGucluDusmanSayisi(), Risk1.ArtificalIntelligence.getEnGucluBolgemIndex(), Risk1.AI.getSavasBolgeIndexleri(), Risk1.AI3.getSavasBolgeIndexleri(), Risk1.AI4.getSavasBolgeIndexleri(), Risk1.AI2.getSavasBolgeIndexleri(), Risk1.Player.getTotalNumberOfArmies(), Risk1.Form1.pictureBox1_Click(), Risk1.SaldiriEkrani.SaldiriEkrani_Load(), Risk1.SaldiriEkrani.warAttack(), Risk1.SaldiriEkrani.warDoORDie(), and Risk1.SaldiriEkrani.warDoORDieForAi().
Player Risk1.Bolge.sahip
Bölgenin sahibi olan oyuncuyu döndürür.
Definition at line 35 of file Bolge.cs.
Referenced by Risk1.ArmyMove.ArmyMove_Load(), Risk1.AI.askerTransferiYap(), Risk1.AI3.askerTransferiYap(), Risk1.AI4.askerTransferiYap(), Risk1.AI2.askerTransferiYap(), Risk1.ArtificalIntelligence.bolgelerimdenRastgeleSec(), Risk1.AI.devam(), Risk1.AI3.devam(), Risk1.AI4.devam(), Risk1.AI2.devam(), Risk1.AI2.getAvrupadakiAskerSayisi(), Risk1.AI2.getAvrupadakiDusmanSayisi(), Risk1.AI3.getDahaGucluDusmanSayisi(), Risk1.AI2.getDahaGucluDusmanSayisi(), Risk1.ArtificalIntelligence.getDostSayisi(), Risk1.ArtificalIntelligence.getKomsuDusmanSayisi(), Risk1.AI.getSavasBolgeIndexleri(), Risk1.AI3.getSavasBolgeIndexleri(), Risk1.AI4.getSavasBolgeIndexleri(), Risk1.AI2.getSavasBolgeIndexleri(), Risk1.Form1.pictureBox1_Click(), Risk1.SaldiriEkrani.SaldiriEkrani_Load(), Risk1.SaldiriEkrani.warAttack(), Risk1.SaldiriEkrani.warDoORDie(), and Risk1.SaldiriEkrani.warDoORDieForAi().
bool Risk1.Bolge.sahipli = false
Bölgenin sahipli olup olmadığını belirtir.
Definition at line 31 of file Bolge.cs.
Referenced by Risk1.Form1.butunBolgelerSecildiMi(), Risk1.Form1.pictureBox1_Click(), and Risk1.ArtificalIntelligence.rastgeleBolgeSec().
The documentation for this class was generated from the following file:
Risk1/Bolge.cs