ANKARISK: Risk1.ArtificalIntelligence Class Reference
Risk1.ArtificalIntelligence Class Reference
Public Member Functions
abstract string getName ()
Bu metod Yapay zekanın ismini döndürmelidir.
abstract int requestTerritory (GameData form1)
Bu metod bölgeler seçilirken istenen bolgenin indexini dondurmektedir.
abstract int getTerritoryToPlaceFirstArmies (GameData form1)
İlk başta tüm oyunculara verilen ilk askerler dağıtılırken her oyuncuya tek tek askerlerini nereye koyması gerektiği sorulur bu metod ilk ordunun koyulması gereken bolgenin indexini dondurur.
abstract List< int > getTerritoriesIndexToPlaceNewArmies (GameData form1)
Oyuncu her turn'de kazandığı yeni askerleri hangi bolgelere yerleştireceğini bu metod sayesinde belirler.
abstract bool devam (GameData form1)
Kullanıcının hamle yapmaya devam edip etmeyeceğini belirler.
abstract bool saldiracanMi (GameData form1)
Bu metod kullanıcının saldırı yapmak isteyip istemediğini belirler.
abstract List< int > getSavasBolgeIndexleri (GameData form1)
Bu metod savaş yapılacak bolgelerin indexlerini belirlemek içindir.
abstract List< int > divideArmies (int index1, int index2, GameData form1)
Oyuncu bir bölgeyi igal ettikten sonra o bölge ile kendi bölgesi arasındaki askerleri nasıl paylaştıracağına bu metod vasıtasıyla karar verir.
abstract bool askerTransferiYapacakmisin (GameData form1)
abstract List< int > askerTransferiYap (GameData form1)
int getKomsuDusmanSayisi (Bolge b)
int getDostSayisi (Bolge b)
int rastgeleBolgeSec (GameData f1)
Bölgelerden sahipsiz olanlarından rastgele birisinin indexini döndürür.
int getEnGucluBolgemIndex (GameData f1)
Oyuncunun sahip olduğu bölgeler içinden en fazla sayıda asker bulunduran bölgenin indexini gönderir.
int bolgelerimdenRastgeleSec (GameData f1)
Oyuncunun bölgeleri içinden rastgele seçilen bölgenin indexini gönderir.
int getToplamDusmanSayisi (GameData f1)
Oyunda bulunan bütün düşmanların toplam asker sayısını döndürür.
Detailed Description
Definition at line 8 of file ArtificalIntelligence.cs.
Member Function Documentation
abstract List<int> Risk1.ArtificalIntelligence.askerTransferiYap (GameData form1) [pure virtual]
Implemented in Risk1.AI2, Risk1.AI4, Risk1.AI3, and Risk1.AI.
Referenced by Risk1.Form1.changeTurn().
abstract bool Risk1.ArtificalIntelligence.askerTransferiYapacakmisin (GameData form1) [pure virtual]
Implemented in Risk1.AI2, Risk1.AI4, Risk1.AI3, and Risk1.AI.
Referenced by Risk1.Form1.changeTurn().
int Risk1.ArtificalIntelligence.bolgelerimdenRastgeleSec (GameData f1) [inline]
Oyuncunun bölgeleri içinden rastgele seçilen bölgenin indexini gönderir.
Parameters:
f1 Oyun Verisi
Returns:
Rastgele Bölge İndexi
Definition at line 150 of file ArtificalIntelligence.cs.
References Risk1.Bolge.index, and Risk1.Bolge.sahip.
Referenced by Risk1.AI4.getTerritoriesIndexToPlaceNewArmies().
        {
            List<int> benimBolgeIndexleri = new List<int>();
            foreach (Bolge b in f1.bolgeler)
            {
                if (b.sahip==f1.players[f1.turn])
                {
                    benimBolgeIndexleri.Add(b.index);
                }
            }
            Random r = new Random();
            return benimBolgeIndexleri[r.Next(0, benimBolgeIndexleri.Count - 1)];
        }
abstract bool Risk1.ArtificalIntelligence.devam (GameData form1) [pure virtual]
Kullanıcının hamle yapmaya devam edip etmeyeceğini belirler.
Parameters:
form1
Returns:
Devam etmek istiyorsa true devam etmek istemiyorsa false.
Implemented in Risk1.AI2, Risk1.AI4, Risk1.AI3, and Risk1.AI.
Referenced by Risk1.Form1.changeTurn().
abstract List<int> Risk1.ArtificalIntelligence.divideArmies (int index1, int index2, GameData form1) [pure virtual]
Oyuncu bir bölgeyi igal ettikten sonra o bölge ile kendi bölgesi arasındaki askerleri nasıl paylaştıracağına bu metod vasıtasıyla karar verir.
Parameters:
index1 Saldırının gerçekleştiği bölgenin index'i
index2 İşgal edilen bölgenin index'i
Returns:
Geriye iki elemanlı bir liste döndürülecek birinci eleman index1 ile belirttiğimiz bolgede kalacak asker sayısını ikinci eleman ise index2 ile belirttiğimiz bolgede kalacak eleman sayısını gostermelidir.
Implemented in Risk1.AI2, Risk1.AI4, Risk1.AI3, and Risk1.AI.
int Risk1.ArtificalIntelligence.getDostSayisi (Bolge b) [inline]
Definition at line 90 of file ArtificalIntelligence.cs.
References Risk1.Bolge.komsular, and Risk1.Bolge.sahip.
Referenced by Risk1.AI.askerTransferiYap(), Risk1.AI3.askerTransferiYap(), Risk1.AI4.askerTransferiYap(), Risk1.AI2.askerTransferiYap(), Risk1.AI.askerTransferiYapacakmisin(), Risk1.AI3.askerTransferiYapacakmisin(), Risk1.AI4.askerTransferiYapacakmisin(), and Risk1.AI2.askerTransferiYapacakmisin().
        {
            int toplam = 0;
            foreach (Bolge bb in b.komsular)
            {
                if (bb.sahip == b.sahip)
                {
                    toplam++;
                }
            }
            return toplam;
        }
int Risk1.ArtificalIntelligence.getEnGucluBolgemIndex (GameData f1) [inline]
Oyuncunun sahip olduğu bölgeler içinden en fazla sayıda asker bulunduran bölgenin indexini gönderir.
Parameters:
f1 Oyun Verisi
Returns:
En Güçlü Bölge İndexi
Definition at line 130 of file ArtificalIntelligence.cs.
References Risk1.Ordu.askerSayisi, Risk1.Bolge.index, and Risk1.Bolge.ordu.
Referenced by Risk1.AI4.devam(), Risk1.AI2.devam(), Risk1.AI3.getTerritoriesIndexToPlaceNewArmies(), Risk1.AI2.getTerritoriesIndexToPlaceNewArmies(), Risk1.AI4.getTerritoriesIndexToPlaceNewArmies(), Risk1.AI4.getTerritoryToPlaceFirstArmies(), and Risk1.AI2.getTerritoryToPlaceFirstArmies().
        {
            int max = 0;
            Bolge bolge = null;
            foreach (Bolge b in f1.players[f1.turn].bolgeler)
            {
                if (b.ordu.askerSayisi >= max)
                {
                    max = b.ordu.askerSayisi;
                    bolge = b;
                }
            }
            return bolge.index;
        }
int Risk1.ArtificalIntelligence.getKomsuDusmanSayisi (Bolge b) [inline]
Definition at line 76 of file ArtificalIntelligence.cs.
References Risk1.Bolge.komsular, and Risk1.Bolge.sahip.
Referenced by Risk1.AI.askerTransferiYap(), Risk1.AI3.askerTransferiYap(), Risk1.AI4.askerTransferiYap(), Risk1.AI2.askerTransferiYap(), Risk1.AI.askerTransferiYapacakmisin(), Risk1.AI3.askerTransferiYapacakmisin(), Risk1.AI4.askerTransferiYapacakmisin(), Risk1.AI2.askerTransferiYapacakmisin(), Risk1.AI4.devam(), Risk1.AI2.devam(), Risk1.AI4.getSavasBolgeIndexleri(), Risk1.AI2.getSavasBolgeIndexleri(), Risk1.AI.getTerritoriesIndexToPlaceNewArmies(), Risk1.AI3.getTerritoriesIndexToPlaceNewArmies(), Risk1.AI2.getTerritoriesIndexToPlaceNewArmies(), Risk1.AI4.getTerritoriesIndexToPlaceNewArmies(), and Risk1.AI3.getTerritoryToPlaceFirstArmies().
        {
            int toplam = 0;
            foreach (Bolge bb in b.komsular)
            {
                if (bb.sahip != b.sahip)
                {
                    toplam++;
                }
            }
            return toplam;
        }
abstract string Risk1.ArtificalIntelligence.getName () [pure virtual]
Bu metod Yapay zekanın ismini döndürmelidir.
Returns:
name
Implemented in Risk1.AI2, Risk1.AI, Risk1.AI4, and Risk1.AI3.
abstract List<int> Risk1.ArtificalIntelligence.getSavasBolgeIndexleri (GameData form1) [pure virtual]
Bu metod savaş yapılacak bolgelerin indexlerini belirlemek içindir.
Returns:
Metod geriye iki elemanlı bir liste döndürür. Birinci eleman nereden saldırı yapılacağını ikinci eleman ise nereye saldırı yapılacağını gösterir. Burada iki bolgenin komsu olmasına dikkat edilmelidir.
Implemented in Risk1.AI2, Risk1.AI4, Risk1.AI3, and Risk1.AI.
Referenced by Risk1.Form1.changeTurn().
abstract List<int> Risk1.ArtificalIntelligence.getTerritoriesIndexToPlaceNewArmies (GameData form1) [pure virtual]
Oyuncu her turn'de kazandığı yeni askerleri hangi bolgelere yerleştireceğini bu metod sayesinde belirler.
Parameters:
form1
Returns:
Askerlerin yerleştirilmek istendiği bolge indexleri
Implemented in Risk1.AI4, Risk1.AI2, Risk1.AI3, and Risk1.AI.
Referenced by Risk1.Form1.changeTurn().
abstract int Risk1.ArtificalIntelligence.getTerritoryToPlaceFirstArmies (GameData form1) [pure virtual]
İlk başta tüm oyunculara verilen ilk askerler dağıtılırken her oyuncuya tek tek askerlerini nereye koyması gerektiği sorulur bu metod ilk ordunun koyulması gereken bolgenin indexini dondurur.
Parameters:
form1
Returns:
ilk ordunun koyulması gereken bolgenin indexini dondurur
Implemented in Risk1.AI2, Risk1.AI4, Risk1.AI, and Risk1.AI3.
Referenced by Risk1.Form1.changeTurn().
int Risk1.ArtificalIntelligence.getToplamDusmanSayisi (GameData f1) [inline]
Oyunda bulunan bütün düşmanların toplam asker sayısını döndürür.
Parameters:
f1 Oyun Verisi
Returns:
Oyundaki Toplam Düşman Asker Sayısı
Definition at line 172 of file ArtificalIntelligence.cs.
References Risk1.Player.getTotalNumberOfArmies().
Referenced by Risk1.AI4.devam(), and Risk1.AI4.getSavasBolgeIndexleri().
        {
            int toplam = 0;
            foreach (Player p in f1.players)
            {
                if (p != f1.players[f1.turn])
                {
                    toplam += p.getTotalNumberOfArmies();
                }
            }
            return toplam;
        }
int Risk1.ArtificalIntelligence.rastgeleBolgeSec (GameData f1) [inline]
Bölgelerden sahipsiz olanlarından rastgele birisinin indexini döndürür.
Parameters:
f1 Oyun Verisi
Returns:
Rastgele Seçilen Bölge İndexi
Definition at line 108 of file ArtificalIntelligence.cs.
References Risk1.Bolge.index, and Risk1.Bolge.sahipli.
Referenced by Risk1.AI3.requestTerritory(), Risk1.AI4.requestTerritory(), Risk1.AI.requestTerritory(), and Risk1.AI2.requestTerritory().
        {
            List<int> sahipsizBolgeIndexleri = new List<int>();
            foreach (Bolge b in f1.bolgeler)
            {
                if (!b.sahipli)
                {
                    sahipsizBolgeIndexleri.Add(b.index);
                }
            }
            Random r = new Random();
            return sahipsizBolgeIndexleri[r.Next(0, sahipsizBolgeIndexleri.Count - 1)];
        }
abstract int Risk1.ArtificalIntelligence.requestTerritory (GameData form1) [pure virtual]
Bu metod bölgeler seçilirken istenen bolgenin indexini dondurmektedir.
Parameters:
form1
Returns:
istenen bolgenin indexi
Implemented in Risk1.AI2, Risk1.AI, Risk1.AI4, and Risk1.AI3.
Referenced by Risk1.Form1.changeTurn().
abstract bool Risk1.ArtificalIntelligence.saldiracanMi (GameData form1) [pure virtual]
Bu metod kullanıcının saldırı yapmak isteyip istemediğini belirler.
Parameters:
form1
Returns:
Eğer saldırı yapmak istiyorsa true istemiyorsa false döndürür.
Implemented in Risk1.AI2, Risk1.AI4, Risk1.AI3, and Risk1.AI.
Referenced by Risk1.Form1.changeTurn().
The documentation for this class was generated from the following file:
Risk1/ArtificalIntelligence.cs