ANKARISK: Risk1.AI2 Class Reference
Risk1.AI2 Class Reference
Public Member Functions
AI2 ()
override string getName ()
Bu metod Yapay zekanın ismini döndürmelidir.
override int requestTerritory (GameData f1)
Bu metod bölgeler seçilirken istenen bolgenin indexini dondurmektedir.
override int getTerritoryToPlaceFirstArmies (GameData f1)
İlk başta tüm oyunculara verilen ilk askerler dağıtılırken her oyuncuya tek tek askerlerini nereye koyması gerektiği sorulur bu metod ilk ordunun koyulması gereken bolgenin indexini dondurur.
override List< int > getTerritoriesIndexToPlaceNewArmies (GameData f1)
Oyuncu her turn'de kazandığı yeni askerleri hangi bolgelere yerleştireceğini bu metod sayesinde belirler.
bool avrupaBendeMi (GameData f1)
override bool devam (GameData f1)
Kullanıcının hamle yapmaya devam edip etmeyeceğini belirler.
override List< int > getSavasBolgeIndexleri (GameData f1)
Bu metod savaş yapılacak bolgelerin indexlerini belirlemek içindir.
override bool saldiracanMi (GameData f1)
Bu metod kullanıcının saldırı yapmak isteyip istemediğini belirler.
int getDahaGucluDusmanSayisi (Bolge b)
override List< int > divideArmies (int index1, int index2, GameData f1)
Oyuncu bir bölgeyi igal ettikten sonra o bölge ile kendi bölgesi arasındaki askerleri nasıl paylaştıracağına bu metod vasıtasıyla karar verir.
override bool askerTransferiYapacakmisin (GameData f1)
override List< int > askerTransferiYap (GameData f1)
Public Attributes
int saldirmaDurumu = 0
List< int > durum3SaldiriIndexleri = new List<int>(2)
Static Public Attributes
static int aiId = 2
static string name = "Hitler"
static Image resim = Properties.Resources.hitler
Private Member Functions
bool avrupadaToprakVarMi (GameData f1)
int getAvrupadakiDusmanSayisi (GameData f1)
int getAvrupadakiAskerSayisi (GameData f1)
bool buBolgeAvrupadaMi (Bolge b)
int getAvrupadakiToprakSayisi (GameData f1)
Detailed Description
Definition at line 12 of file AI2.cs.
Constructor & Destructor Documentation
Risk1.AI2.AI2 () [inline]
Definition at line 14 of file AI2.cs.
        {
        }
Member Function Documentation
override List<int> Risk1.AI2.askerTransferiYap (GameData f1) [inline, virtual]
Implements Risk1.ArtificalIntelligence.
Definition at line 664 of file AI2.cs.
References Risk1.Ordu.askerSayisi, Risk1.ArtificalIntelligence.getDostSayisi(), Risk1.ArtificalIntelligence.getKomsuDusmanSayisi(), Risk1.Bolge.index, Risk1.Bolge.komsular, Risk1.Bolge.ordu, and Risk1.Bolge.sahip.
        {
            bool break2 = false;
            List<int> veriler = new List<int>();
            foreach (Bolge b in f1.players[f1.turn].bolgeler)
            {
                if (getKomsuDusmanSayisi(b) == 0)
                {
                    if (b.ordu.askerSayisi > 1)
                    {
                        if (getDostSayisi(b) > 0)
{
                            //Once nereden transfer yapacagimizi belirledik
                            veriler.Add(b.index);
                            foreach (Bolge komsu in b.komsular)
{
                                if (komsu.sahip == b.sahip)
{
                                    veriler.Add(komsu.index);
                                    veriler.Add(1);
                                    veriler.Add(komsu.ordu.askerSayisi + b.ordu.askerSayisi - 1);
                                    break2 = true;
                                    break;
                                }
                            }
                            if (break2)
                                break;
                        }
                    }
                }
            }
            return veriler;
        }
override bool Risk1.AI2.askerTransferiYapacakmisin (GameData f1) [inline, virtual]
Implements Risk1.ArtificalIntelligence.
Definition at line 646 of file AI2.cs.
References Risk1.Ordu.askerSayisi, Risk1.ArtificalIntelligence.getDostSayisi(), Risk1.ArtificalIntelligence.getKomsuDusmanSayisi(), and Risk1.Bolge.ordu.
        {
            foreach (Bolge b in f1.players[f1.turn].bolgeler)
            {
                if (getKomsuDusmanSayisi(b) == 0)
                {
                    if (b.ordu.askerSayisi > 1)
                    {
                        if (getDostSayisi(b) > 0)
{
                            return true;
                        }
                    }
                }
            }
            return false;
        }
bool Risk1.AI2.avrupaBendeMi (GameData f1) [inline]
Definition at line 219 of file AI2.cs.
References Risk1.Bolge.index.
Referenced by Risk1.AI2.devam().
        {
            //19-25 arası
            List<int> bolgeler=new List<int>();
            foreach (Bolge b in f1.players[f1.turn].bolgeler)
            {
                bolgeler.Add(b.index);
            }
            if (!bolgeler.Contains(19))
            {
                return false;
            }
            if (!bolgeler.Contains(20))
            {
                return false;
            }
            if (!bolgeler.Contains(21))
            {
                return false;
            }
            if (!bolgeler.Contains(22))
            {
                return false;
            }
            if (!bolgeler.Contains(23))
            {
                return false;
            }
            if (!bolgeler.Contains(24))
            {
                return false;
            }
            if (!bolgeler.Contains(25))
            {
                return false;
            }
            return true;
        }
bool Risk1.AI2.avrupadaToprakVarMi (GameData f1) [inline, private]
Definition at line 261 of file AI2.cs.
References Risk1.Bolge.index.
Referenced by Risk1.AI2.devam(), and Risk1.AI2.getTerritoriesIndexToPlaceNewArmies().
        {
            List<int> bolgeler = new List<int>();
            foreach (Bolge b in f1.players[f1.turn].bolgeler)
            {
                bolgeler.Add(b.index);
            }
            if (bolgeler.Contains(19))
            {
                return true;
            }
            if (bolgeler.Contains(20))
            {
                return true;
            }
            if (bolgeler.Contains(21))
            {
                return true;
            }
            if (bolgeler.Contains(22))
            {
                return true;
            }
            if (bolgeler.Contains(23))
            {
                return true;
            }
            if (bolgeler.Contains(24))
            {
                return true;
            }
            if (bolgeler.Contains(25))
            {
                return true;
            }
            return false;
        }
bool Risk1.AI2.buBolgeAvrupadaMi (Bolge b) [inline, private]
Definition at line 487 of file AI2.cs.
References Risk1.Bolge.index.
Referenced by Risk1.AI2.devam(), Risk1.AI2.getAvrupadakiToprakSayisi(), and Risk1.AI2.getSavasBolgeIndexleri().
        {
            if (b.index == 19)
            {
                return true;
            }
            if (b.index == 20)
            {
                return true;
            }
            if (b.index == 21)
            {
                return true;
            }
            if (b.index == 22)
            {
                return true;
            }
            if (b.index == 23)
            {
                return true;
            }
            if (b.index == 24)
            {
                return true;
            }
            if (b.index == 25)
            {
                return true;
            }
            return false;
        }
override bool Risk1.AI2.devam (GameData form1) [inline, virtual]
Kullanıcının hamle yapmaya devam edip etmeyeceğini belirler.
Parameters:
form1
Returns:
Devam etmek istiyorsa true devam etmek istemiyorsa false.
Implements Risk1.ArtificalIntelligence.
Definition at line 330 of file AI2.cs.
References Risk1.Ordu.askerSayisi, Risk1.AI2.avrupaBendeMi(), Risk1.AI2.avrupadaToprakVarMi(), Risk1.GameData.bolgeler, Risk1.AI2.buBolgeAvrupadaMi(), Risk1.AI2.durum3SaldiriIndexleri, Risk1.AI2.getAvrupadakiAskerSayisi(), Risk1.AI2.getAvrupadakiDusmanSayisi(), Risk1.ArtificalIntelligence.getEnGucluBolgemIndex(), Risk1.ArtificalIntelligence.getKomsuDusmanSayisi(), Risk1.Bolge.index, Risk1.Bolge.komsular, Risk1.Bolge.ordu, Risk1.GameData.players, Risk1.Bolge.sahip, Risk1.AI2.saldirmaDurumu, and Risk1.GameData.turn.
Referenced by Risk1.AI2.saldiracanMi().
        {
            durum3SaldiriIndexleri.Clear();
            saldirmaDurumu = 0;
            //19-25 arasını almak amaç öncelikle
            if (avrupaBendeMi(f1))//avrupa onda
            {
                foreach (Bolge b in f1.players[f1.turn].bolgeler)
                {
                    foreach (Bolge komsu in b.komsular)
                    {
                        if (b.ordu.askerSayisi > komsu.ordu.askerSayisi + 10 && b.sahip != komsu.sahip)
{
                            saldirmaDurumu = 1;
                            return true;
                        }
                    }
                }
                return false;
            }
            else if (avrupadaToprakVarMi(f1))//avrupada toprağm var sadece
            {
                if (getAvrupadakiAskerSayisi(f1) > getAvrupadakiDusmanSayisi(f1))//Toplam Düşmandan daha fazlaysa Saldırıya geçer //Avrupaya karşı
                {
                    //Eğer Avrupada tek başına komsusundan güçlü olan varsa saldırırız
                    //Toplamımız daha büyük olabilir ama tek tek hiçbir bölgemiz daha güçlü olmayabilir
                    foreach (Bolge b in f1.players[f1.turn].bolgeler)
                    {
                        if (getKomsuDusmanSayisi(b) > 0)
{
                            foreach (Bolge b2 in b.komsular)
{
                                if (b2.sahip != b.sahip)
{
                                    if (b.ordu.askerSayisi > b2.ordu.askerSayisi && buBolgeAvrupadaMi(b2))
{
                                        saldirmaDurumu = 2;
                                        return true;
                                    }
                                }
                            }
                        }
                    }
                    return false;
                }
                else//Düşman daha fazlaysa bekler devam etmez
                {
                    return false;
                }
            }
            else//Avrupayla alakamız yoksa Avrupaya ulaşmaya çalışacağız.
            {
                Graph graph = new Graph();
                foreach (Bolge b in f1.bolgeler)
                {
                    graph.AddNode(b.index.ToString());
                }
                foreach (Bolge b in f1.bolgeler)
                {
                    foreach (Bolge b2 in b.komsular)
                    {
                        if (b2.sahip != f1.players[f1.turn])
{
                            graph.AddConnection(b.index.ToString(), b2.index.ToString(), b2.ordu.askerSayisi, false);
                        }
                    }
                }
                var calculator = new DistanceCalculator();
                var distances = calculator.CalculateDistances(graph, getEnGucluBolgemIndex(f1).ToString());  // Start from "G"
                String temp="";
                //Avrupa Sınırları
                List<int> avrupaSinirlari = new List<int>();
                avrupaSinirlari.Add(0);
                avrupaSinirlari.Add(0);
                avrupaSinirlari.Add(0);
                avrupaSinirlari.Add(0);
                foreach (var d in distances)
                {
                    temp+= d.Key+" - "+d.Value+"-";
                    if (d.Key == "19")
                    {
                        avrupaSinirlari[0] =(int)d.Value;
                    }
                    if (d.Key == "21")
                    {
                        avrupaSinirlari[1] = (int)d.Value;
                    }
                    if (d.Key == "24")
                    {
                        avrupaSinirlari[2] = (int)d.Value;
                    }
                    if (d.Key == "25")
                    {
                        avrupaSinirlari[3] = (int)d.Value;
                    }
                }
                int min = avrupaSinirlari.Min();
                int minIndex = avrupaSinirlari.IndexOf(min);
                int minBolgeIndex = 0;
                if (minIndex == 0)
                {
                    minBolgeIndex = 19;
                }
                if (minIndex == 1)
                {
                    minBolgeIndex = 21;
                }
                if (minIndex == 2)
                {
                    minBolgeIndex = 24;
                }
                if (minIndex == 3)
                {
                    minBolgeIndex = 25;
                }
                List<String> gidilecekyol = new List<String>();
                //calculator = new DistanceCalculator();
                gidilecekyol = calculator.getYol(getEnGucluBolgemIndex(f1).ToString(),minBolgeIndex.ToString(), graph);
                if (f1.bolgeler[getEnGucluBolgemIndex(f1)].ordu.askerSayisi > min + 10)//Gideceğiz Avrupaya
                {
                    if (f1.bolgeler[getEnGucluBolgemIndex(f1)].komsular.Contains(f1.bolgeler[Convert.ToInt32(gidilecekyol[gidilecekyol.Count - 1])]))
                    {
                        saldirmaDurumu = 3;
                        durum3SaldiriIndexleri.Add(getEnGucluBolgemIndex(f1));
                        durum3SaldiriIndexleri.Add(Convert.ToInt32(gidilecekyol[gidilecekyol.Count - 1]));
                        return true;
                    }
                    else
                    {
                        return false;
                    }
                }
                else//Biraz daha büyüyeceğiz...
                {
                    return false;
                }
            }
        }
override List<int> Risk1.AI2.divideArmies (int index1, int index2, GameData form1) [inline, virtual]
Oyuncu bir bölgeyi igal ettikten sonra o bölge ile kendi bölgesi arasındaki askerleri nasıl paylaştıracağına bu metod vasıtasıyla karar verir.
Parameters:
index1 Saldırının gerçekleştiği bölgenin index'i
index2 İşgal edilen bölgenin index'i
Returns:
Geriye iki elemanlı bir liste döndürülecek birinci eleman index1 ile belirttiğimiz bolgede kalacak asker sayısını ikinci eleman ise index2 ile belirttiğimiz bolgede kalacak eleman sayısını gostermelidir.
Implements Risk1.ArtificalIntelligence.
Definition at line 616 of file AI2.cs.
References Risk1.GameData.bolgeler, and Risk1.AI2.getAvrupadakiToprakSayisi().
        {
            List<int> sonuc = new List<int>();
            if (getAvrupadakiToprakSayisi(f1)>1)
            {
                int toplam = f1.bolgeler[index1].ordu.askerSayisi + f1.bolgeler[index2].ordu.askerSayisi;
                if ((toplam % 2) == 0)
                {
                    sonuc.Add(toplam / 2);
                    sonuc.Add(toplam / 2);
                }
                else
                {
                    sonuc.Add(toplam / 2);
                    sonuc.Add((toplam / 2) + 1);
                }
            }
            else
            {
                int toplam = f1.bolgeler[index1].ordu.askerSayisi + f1.bolgeler[index2].ordu.askerSayisi;
                sonuc.Add(1);
                sonuc.Add(toplam - 1);
            }
            return sonuc;
        }
int Risk1.AI2.getAvrupadakiAskerSayisi (GameData f1) [inline, private]
Definition at line 316 of file AI2.cs.
References Risk1.Ordu.askerSayisi, Risk1.Bolge.ordu, and Risk1.Bolge.sahip.
Referenced by Risk1.AI2.devam().
        {
            int toplamAskerSayisi = 0;
            foreach (Bolge b in f1.kitalar[4].bolgeler)
            {
                if (b.sahip == f1.players[f1.turn])
                {
                    toplamAskerSayisi += b.ordu.askerSayisi;
                }
            }
            return toplamAskerSayisi;
        }
int Risk1.AI2.getAvrupadakiDusmanSayisi (GameData f1) [inline, private]
Definition at line 301 of file AI2.cs.
References Risk1.Ordu.askerSayisi, Risk1.Bolge.ordu, and Risk1.Bolge.sahip.
Referenced by Risk1.AI2.devam().
        {
            int toplamDusmanSayisi = 0;
            foreach (Bolge b in f1.kitalar[4].bolgeler)
            {
                if (b.sahip != f1.players[f1.turn])
                {
                    toplamDusmanSayisi += b.ordu.askerSayisi;
                }
            }
            return toplamDusmanSayisi;
        }
int Risk1.AI2.getAvrupadakiToprakSayisi (GameData f1) [inline, private]
Definition at line 588 of file AI2.cs.
References Risk1.AI2.buBolgeAvrupadaMi().
Referenced by Risk1.AI2.divideArmies().
        {
            //19-25
            int sonuc = 0;
            foreach (Bolge b in f1.players[f1.turn].bolgeler)
            {
                if (buBolgeAvrupadaMi(b))
                {
                    sonuc++;
                }
            }
            return sonuc;
        }
int Risk1.AI2.getDahaGucluDusmanSayisi (Bolge b) [inline]
Definition at line 602 of file AI2.cs.
References Risk1.Ordu.askerSayisi, Risk1.Bolge.komsular, Risk1.Bolge.ordu, and Risk1.Bolge.sahip.
Referenced by Risk1.AI2.getTerritoriesIndexToPlaceNewArmies().
        {
            int toplam = 0;
            foreach (Bolge bb in b.komsular)
            {
                if (bb.sahip != b.sahip && b.ordu.askerSayisi < bb.ordu.askerSayisi)
                {
                    toplam++;
                }
            }
            return toplam;
        }
override string Risk1.AI2.getName () [inline, virtual]
Bu metod Yapay zekanın ismini döndürmelidir.
Returns:
name
Implements Risk1.ArtificalIntelligence.
Definition at line 22 of file AI2.cs.
References Risk1.AI2.name.
        {
            return name;
        }
override List<int> Risk1.AI2.getSavasBolgeIndexleri (GameData form1) [inline, virtual]
Bu metod savaş yapılacak bolgelerin indexlerini belirlemek içindir.
Returns:
Metod geriye iki elemanlı bir liste döndürür. Birinci eleman nereden saldırı yapılacağını ikinci eleman ise nereye saldırı yapılacağını gösterir. Burada iki bolgenin komsu olmasına dikkat edilmelidir.
Implements Risk1.ArtificalIntelligence.
Definition at line 521 of file AI2.cs.
References Risk1.Ordu.askerSayisi, Risk1.AI2.buBolgeAvrupadaMi(), Risk1.AI2.durum3SaldiriIndexleri, Risk1.ArtificalIntelligence.getKomsuDusmanSayisi(), Risk1.Bolge.index, Risk1.Bolge.komsular, Risk1.Bolge.ordu, Risk1.GameData.players, Risk1.Bolge.sahip, Risk1.AI2.saldirmaDurumu, and Risk1.GameData.turn.
        {
            List<int> savasBolgeleri = new List<int>();
            //19-25 arasını almak amaç öncelikle
            //if saldiriDurumu ==1 yani avrupanın bende olma durumu için kod sonra yazılacak
            if (saldirmaDurumu == 1)
            {
                List<int> sonuc = new List<int>();
                foreach (Bolge b in f1.players[f1.turn].bolgeler)
                {
                    foreach (Bolge komsu in b.komsular)
                    {
                        if (b.ordu.askerSayisi > komsu.ordu.askerSayisi + 10 && b.sahip != komsu.sahip)
{
                            sonuc.Add(b.index);
                            sonuc.Add(komsu.index);
                        }
                    }
                }
                return sonuc;
            }
            else if (saldirmaDurumu==2)//avrupada toprağm var sadece
            {
                bool break2 = false;
                foreach (Bolge b in f1.players[f1.turn].bolgeler)
                {
                    if (getKomsuDusmanSayisi(b) > 0)
                    {
                        foreach (Bolge b2 in b.komsular)
{
                            if (b2.sahip != b.sahip)
{
                                if (b.ordu.askerSayisi > b2.ordu.askerSayisi  && buBolgeAvrupadaMi(b2))
{
                                    savasBolgeleri.Add(b.index);
                                    savasBolgeleri.Add(b2.index);
                                    break2 = true;
                                    break;
                                }
                            }
                        }
                    }
                    if (break2) break;
                }
                return savasBolgeleri;
            }
            else if (saldirmaDurumu == 3)//Avrupayla alakamız yoksa...
            {
                return durum3SaldiriIndexleri;
            }
            else
            {
                //oylesine
                return savasBolgeleri;
            }
        }
override List<int> Risk1.AI2.getTerritoriesIndexToPlaceNewArmies (GameData form1) [inline, virtual]
Oyuncu her turn'de kazandığı yeni askerleri hangi bolgelere yerleştireceğini bu metod sayesinde belirler.
Parameters:
form1
Returns:
Askerlerin yerleştirilmek istendiği bolge indexleri
Implements Risk1.ArtificalIntelligence.
Definition at line 111 of file AI2.cs.
References Risk1.AI2.avrupadaToprakVarMi(), Risk1.GameData.bolgeler, Risk1.AI2.getDahaGucluDusmanSayisi(), Risk1.ArtificalIntelligence.getEnGucluBolgemIndex(), Risk1.ArtificalIntelligence.getKomsuDusmanSayisi(), Risk1.Bolge.index, Risk1.GameData.players, and Risk1.GameData.turn.
        {
            Random r = new Random();
            List<int> gonderilecekler = new List<int>();
            int orduyuNereyeKoyalim=-1;
            //Avrupadan bir yeri varsa oraya koyar
            if (!avrupadaToprakVarMi(f1))
            {
                if (getKomsuDusmanSayisi(f1.bolgeler[getEnGucluBolgemIndex(f1)]) > 0)
                {
                    orduyuNereyeKoyalim = getEnGucluBolgemIndex(f1);
                }
                else
                {
                    foreach (Bolge b in f1.players[f1.turn].bolgeler)
                    {
                        if (getDahaGucluDusmanSayisi(b) > 0)
{
                            orduyuNereyeKoyalim = b.index;
                        }
                    }
                }
                if (orduyuNereyeKoyalim == -1)
                {
                    foreach (Bolge b in f1.players[f1.turn].bolgeler)
                    {
                        if (getKomsuDusmanSayisi(b) > 0)
{
                            orduyuNereyeKoyalim = b.index;
                        }
                    }
                }
            }
            else
            {
                List<int> sahipoldugubolgeler = new List<int>();
                List<int> orduyuKoyabilecegimizBolgeler = new List<int>();
                foreach (Bolge b in f1.players[f1.turn].bolgeler)
                {
                    sahipoldugubolgeler.Add(b.index);
                }
                //Orduyu avrupada toprağımız varsa burada düşman olan herhangi bölgeye koyabilir...
                if (sahipoldugubolgeler.Contains(22) && getKomsuDusmanSayisi(f1.bolgeler[22]) > 0)
                {
                    orduyuKoyabilecegimizBolgeler.Add(22);
                }
                if (sahipoldugubolgeler.Contains(23) && getKomsuDusmanSayisi(f1.bolgeler[23]) > 0)
                {
                    orduyuKoyabilecegimizBolgeler.Add(23);
                }
                if (sahipoldugubolgeler.Contains(20) && getKomsuDusmanSayisi(f1.bolgeler[20]) > 0)
                {
                    orduyuKoyabilecegimizBolgeler.Add(20);
                }
                if (sahipoldugubolgeler.Contains(21) && getKomsuDusmanSayisi(f1.bolgeler[21]) > 0)
                {
                    orduyuKoyabilecegimizBolgeler.Add(21);
                }
                if (sahipoldugubolgeler.Contains(19) && getKomsuDusmanSayisi(f1.bolgeler[19]) > 0)
                {
                    orduyuKoyabilecegimizBolgeler.Add(19);
                }
                if (sahipoldugubolgeler.Contains(24) && getKomsuDusmanSayisi(f1.bolgeler[24]) > 0)
                {
                    orduyuKoyabilecegimizBolgeler.Add(24);
                }
                if (sahipoldugubolgeler.Contains(25) && getKomsuDusmanSayisi(f1.bolgeler[25]) > 0)
                {
                    orduyuKoyabilecegimizBolgeler.Add(25);
                }
                if (orduyuKoyabilecegimizBolgeler.Count != 0)
                {
                    int a = r.Next(0, orduyuKoyabilecegimizBolgeler.Count - 1);
                    orduyuNereyeKoyalim = orduyuKoyabilecegimizBolgeler[a];
                }
                else//Avrupanın zaten tamamı bizde ve etrafta komsulukta dusman yoksa
                {
                    List<int> etraftaDusmanOlanBolgelerim = new List<int>();
                    foreach (Bolge b in f1.players[f1.turn].bolgeler)
                    {
                        if (getKomsuDusmanSayisi(b) > 0)
{
                            etraftaDusmanOlanBolgelerim.Add(b.index);
                        }
                    }
                    int a = r.Next(0, etraftaDusmanOlanBolgelerim.Count - 1);
                    orduyuNereyeKoyalim = etraftaDusmanOlanBolgelerim[a];
                }
            }
            int k = f1.players[f1.turn].yeniAskerler;
            for (int i = 0; i < k; i++)
            {
                gonderilecekler.Add(orduyuNereyeKoyalim);
            }
            return gonderilecekler;
        }
override int Risk1.AI2.getTerritoryToPlaceFirstArmies (GameData form1) [inline, virtual]
İlk başta tüm oyunculara verilen ilk askerler dağıtılırken her oyuncuya tek tek askerlerini nereye koyması gerektiği sorulur bu metod ilk ordunun koyulması gereken bolgenin indexini dondurur.
Parameters:
form1
Returns:
ilk ordunun koyulması gereken bolgenin indexini dondurur
Implements Risk1.ArtificalIntelligence.
Definition at line 65 of file AI2.cs.
References Risk1.ArtificalIntelligence.getEnGucluBolgemIndex(), and Risk1.Bolge.index.
        {
            List<int> sahipoldugubolgeler = new List<int>();
            foreach (Bolge b in f1.players[f1.turn].bolgeler)
            {
                sahipoldugubolgeler.Add(b.index);
            }
            Random r = new Random();
            int sayi = r.Next(0, sahipoldugubolgeler.Count - 1);
            int index = getEnGucluBolgemIndex(f1);
            if (sahipoldugubolgeler.Contains(22))
            {
                return f1.bolgeler[22].index;
            }
            if (sahipoldugubolgeler.Contains(23))
            {
                return f1.bolgeler[23].index;
            }
            if (sahipoldugubolgeler.Contains(20))
            {
                return f1.bolgeler[20].index;
            }
            if (sahipoldugubolgeler.Contains(21))
            {
                return f1.bolgeler[21].index;
            }
            if (sahipoldugubolgeler.Contains(19))
            {
                return f1.bolgeler[19].index;
            }
            if (sahipoldugubolgeler.Contains(24))
            {
                return f1.bolgeler[24].index;
            }
            if (sahipoldugubolgeler.Contains(25))
            {
                return f1.bolgeler[25].index;
            }
            return f1.bolgeler[index].index;
        }
override int Risk1.AI2.requestTerritory (GameData form1) [inline, virtual]
Bu metod bölgeler seçilirken istenen bolgenin indexini dondurmektedir.
Parameters:
form1
Returns:
istenen bolgenin indexi
Implements Risk1.ArtificalIntelligence.
Definition at line 30 of file AI2.cs.
References Risk1.GameData.bolgeler, and Risk1.ArtificalIntelligence.rastgeleBolgeSec().
        {
            if (!f1.bolgeler[22].sahipli)
            {
                return 22;
            }
            if (!f1.bolgeler[20].sahipli)
            {
                return 20;
            }
            if (!f1.bolgeler[21].sahipli)
            {
                return 21;
            }
            if (!f1.bolgeler[19].sahipli)
            {
                return 19;
            }
            if (!f1.bolgeler[23].sahipli)
            {
                return 23;
            }
            if (!f1.bolgeler[24].sahipli)
            {
                return 24;
            }
            if (!f1.bolgeler[25].sahipli)
            {
                return 25;
            }
            return rastgeleBolgeSec(f1);
        }
override bool Risk1.AI2.saldiracanMi (GameData form1) [inline, virtual]
Bu metod kullanıcının saldırı yapmak isteyip istemediğini belirler.
Parameters:
form1
Returns:
Eğer saldırı yapmak istiyorsa true istemiyorsa false döndürür.
Implements Risk1.ArtificalIntelligence.
Definition at line 581 of file AI2.cs.
References Risk1.AI2.devam().
        {
            return devam(f1);
        }
Member Data Documentation
int Risk1.AI2.aiId = 2 [static]
Definition at line 18 of file AI2.cs.
Referenced by Risk1.ChangePlayer.HangiYapayZekaSecili().
List<int> Risk1.AI2.durum3SaldiriIndexleri = new List<int>(2)
Definition at line 28 of file AI2.cs.
Referenced by Risk1.AI2.devam(), and Risk1.AI2.getSavasBolgeIndexleri().
string Risk1.AI2.name = "Hitler" [static]
Definition at line 19 of file AI2.cs.
Referenced by Risk1.AI2.getName(), and Risk1.ChangePlayer.HangiYapayZekaSecili().
Image Risk1.AI2.resim = Properties.Resources.hitler [static]
Definition at line 20 of file AI2.cs.
Referenced by Risk1.ChangePlayer.HangiYapayZekaSecili().
int Risk1.AI2.saldirmaDurumu = 0
Definition at line 27 of file AI2.cs.
Referenced by Risk1.AI2.devam(), and Risk1.AI2.getSavasBolgeIndexleri().
The documentation for this class was generated from the following file:
Risk1/AI2.cs