ANKARISK: Risk1.GameData Class Reference
Risk1.GameData Class Reference
Public Attributes
List< Bolge > bolgeler = new List<Bolge>()
Oyundaki bölgelerin listesini tutar.
List< Player > players = new List<Player>()
Oyunda bulunan oyuncuların listesini tutar.
List< Continent > kitalar = new List<Continent>()
Oyunda bulunan kıtaların listesini tutar.
int turn
players listesindeki oyuncular arasında sıranın kimde olduğunu belirtir.
int ganimetBolgesi
Ganimet bölgesinin index değerine bu değişken sayesinde erişilir.
int ganimetKazanci
Ganimet bölgesinin oyuncuya kazandırdığı asker sayısıdır.
Detailed Description
Definition at line 8 of file GameData.cs.
Member Data Documentation
List<Bolge> Risk1.GameData.bolgeler = new List<Bolge>()
Oyundaki bölgelerin listesini tutar.
Definition at line 13 of file GameData.cs.
Referenced by Risk1.AI4.devam(), Risk1.AI2.devam(), Risk1.AI.divideArmies(), Risk1.AI3.divideArmies(), Risk1.AI4.divideArmies(), Risk1.AI2.divideArmies(), Risk1.AI4.dusmanNerede(), Risk1.AI3.getTerritoriesIndexToPlaceNewArmies(), Risk1.AI2.getTerritoriesIndexToPlaceNewArmies(), Risk1.AI4.requestTerritory(), Risk1.AI2.requestTerritory(), Risk1.AI4.southAmericaBendeMi(), Risk1.AI4.southAmericadaToprakVarMi(), Risk1.AI4.southAmericaSinirindaDusmanVarMi(), and Risk1.Form1.updateGameData().
int Risk1.GameData.ganimetBolgesi
Ganimet bölgesinin index değerine bu değişken sayesinde erişilir.
Definition at line 29 of file GameData.cs.
Referenced by Risk1.Form1.updateGameData().
int Risk1.GameData.ganimetKazanci
Ganimet bölgesinin oyuncuya kazandırdığı asker sayısıdır.
Varsayılan değeri 1 dir.
Definition at line 33 of file GameData.cs.
Referenced by Risk1.Form1.updateGameData().
List<Continent> Risk1.GameData.kitalar = new List<Continent>()
Oyunda bulunan kıtaların listesini tutar.
Definition at line 21 of file GameData.cs.
Referenced by Risk1.Form1.updateGameData().
List<Player> Risk1.GameData.players = new List<Player>()
Oyunda bulunan oyuncuların listesini tutar.
Definition at line 17 of file GameData.cs.
Referenced by Risk1.AI4.devam(), Risk1.AI2.devam(), Risk1.AI4.dusmanNerede(), Risk1.AI4.getSavasBolgeIndexleri(), Risk1.AI2.getSavasBolgeIndexleri(), Risk1.AI3.getTerritoriesIndexToPlaceNewArmies(), Risk1.AI2.getTerritoriesIndexToPlaceNewArmies(), Risk1.AI4.getTerritoriesIndexToPlaceNewArmies(), Risk1.AI.getTerritoryToPlaceFirstArmies(), Risk1.AI4.southAmericaBendeMi(), Risk1.AI4.southAmericadaToprakVarMi(), Risk1.AI4.southAmericaSinirindaDusmanVarMi(), and Risk1.Form1.updateGameData().
int Risk1.GameData.turn
players listesindeki oyuncular arasında sıranın kimde olduğunu belirtir.
Definition at line 25 of file GameData.cs.
Referenced by Risk1.AI4.devam(), Risk1.AI2.devam(), Risk1.AI4.dusmanNerede(), Risk1.AI4.getSavasBolgeIndexleri(), Risk1.AI2.getSavasBolgeIndexleri(), Risk1.AI3.getTerritoriesIndexToPlaceNewArmies(), Risk1.AI2.getTerritoriesIndexToPlaceNewArmies(), Risk1.AI4.getTerritoriesIndexToPlaceNewArmies(), Risk1.AI.getTerritoryToPlaceFirstArmies(), Risk1.AI4.southAmericaBendeMi(), Risk1.AI4.southAmericadaToprakVarMi(), Risk1.AI4.southAmericaSinirindaDusmanVarMi(), and Risk1.Form1.updateGameData().
The documentation for this class was generated from the following file:
Risk1/GameData.cs