ANKARISK: Risk1.AI3 Class Reference
Risk1.AI3 Class Reference
Public Member Functions
override string getName ()
Bu metod Yapay zekanın ismini döndürmelidir.
override int requestTerritory (GameData f1)
Bu metod bölgeler seçilirken istenen bolgenin indexini dondurmektedir.
override int getTerritoryToPlaceFirstArmies (GameData f1)
İlk başta tüm oyunculara verilen ilk askerler dağıtılırken her oyuncuya tek tek askerlerini nereye koyması gerektiği sorulur bu metod ilk ordunun koyulması gereken bolgenin indexini dondurur.
override List< int > getTerritoriesIndexToPlaceNewArmies (GameData f1)
Oyuncu her turn'de kazandığı yeni askerleri hangi bolgelere yerleştireceğini bu metod sayesinde belirler.
override bool devam (GameData f1)
Kullanıcının hamle yapmaya devam edip etmeyeceğini belirler.
override bool saldiracanMi (GameData f1)
Bu metod kullanıcının saldırı yapmak isteyip istemediğini belirler.
int getDahaGucluDusmanSayisi (Bolge b)
override List< int > getSavasBolgeIndexleri (GameData f1)
Bu metod savaş yapılacak bolgelerin indexlerini belirlemek içindir.
override List< int > divideArmies (int index1, int index2, GameData f1)
Oyuncu bir bölgeyi igal ettikten sonra o bölge ile kendi bölgesi arasındaki askerleri nasıl paylaştıracağına bu metod vasıtasıyla karar verir.
override bool askerTransferiYapacakmisin (GameData f1)
override List< int > askerTransferiYap (GameData f1)
Static Public Attributes
static int aiid = 3
static string name = "Babak"
static Image resim = Properties.Resources.babek
Detailed Description
Definition at line 9 of file AI3.cs.
Member Function Documentation
override List<int> Risk1.AI3.askerTransferiYap (GameData f1) [inline, virtual]
Implements Risk1.ArtificalIntelligence.
Definition at line 165 of file AI3.cs.
References Risk1.Ordu.askerSayisi, Risk1.ArtificalIntelligence.getDostSayisi(), Risk1.ArtificalIntelligence.getKomsuDusmanSayisi(), Risk1.Bolge.index, Risk1.Bolge.komsular, Risk1.Bolge.ordu, and Risk1.Bolge.sahip.
        {
            bool break2 = false;
            List<int> veriler = new List<int>();
            foreach (Bolge b in f1.players[f1.turn].bolgeler)
            {
                if (getKomsuDusmanSayisi(b) == 0)
                {
                    if (b.ordu.askerSayisi > 1)
                    {
                        if (getDostSayisi(b) > 0)
{
                            //Once nereden transfer yapacagimizi belirledik
                            veriler.Add(b.index);
                            foreach (Bolge komsu in b.komsular)
{
                                if (komsu.sahip == b.sahip)
{
                                    veriler.Add(komsu.index);
                                    veriler.Add(1);
                                    veriler.Add(komsu.ordu.askerSayisi + b.ordu.askerSayisi - 1);
                                    break2 = true;
                                    break;
                                }
                            }
                            if (break2)
                                break;
                        }
                    }
                }
            }
            return veriler;
        }
override bool Risk1.AI3.askerTransferiYapacakmisin (GameData f1) [inline, virtual]
Implements Risk1.ArtificalIntelligence.
Definition at line 146 of file AI3.cs.
References Risk1.Ordu.askerSayisi, Risk1.ArtificalIntelligence.getDostSayisi(), Risk1.ArtificalIntelligence.getKomsuDusmanSayisi(), and Risk1.Bolge.ordu.
        {
            foreach (Bolge b in f1.players[f1.turn].bolgeler)
            {
                if (getKomsuDusmanSayisi(b) == 0)
                {
                    if (b.ordu.askerSayisi > 1)
                    {
                        if (getDostSayisi(b) > 0)
{
                            return true;
                        }
                    }
                }
            }
            return false;
        }
override bool Risk1.AI3.devam (GameData form1) [inline, virtual]
Kullanıcının hamle yapmaya devam edip etmeyeceğini belirler.
Parameters:
form1
Returns:
Devam etmek istiyorsa true devam etmek istemiyorsa false.
Implements Risk1.ArtificalIntelligence.
Definition at line 80 of file AI3.cs.
References Risk1.Ordu.askerSayisi, Risk1.Bolge.komsular, Risk1.Bolge.ordu, and Risk1.Bolge.sahip.
Referenced by Risk1.AI3.saldiracanMi().
        {
            List<int> sonuc = new List<int>();
            foreach (Bolge b in f1.players[f1.turn].bolgeler)
            {
                foreach (Bolge komsu in b.komsular)
                {
                    if (b.ordu.askerSayisi > komsu.ordu.askerSayisi+30 && b.sahip!=komsu.sahip)
                    {
                        return true;
                    }
                }
            }
            return false;
        }
override List<int> Risk1.AI3.divideArmies (int index1, int index2, GameData form1) [inline, virtual]
Oyuncu bir bölgeyi igal ettikten sonra o bölge ile kendi bölgesi arasındaki askerleri nasıl paylaştıracağına bu metod vasıtasıyla karar verir.
Parameters:
index1 Saldırının gerçekleştiği bölgenin index'i
index2 İşgal edilen bölgenin index'i
Returns:
Geriye iki elemanlı bir liste döndürülecek birinci eleman index1 ile belirttiğimiz bolgede kalacak asker sayısını ikinci eleman ise index2 ile belirttiğimiz bolgede kalacak eleman sayısını gostermelidir.
Implements Risk1.ArtificalIntelligence.
Definition at line 134 of file AI3.cs.
References Risk1.GameData.bolgeler.
        {
            List<int> sonuc = new List<int>();
            int toplam = f1.bolgeler[index1].ordu.askerSayisi + f1.bolgeler[index2].ordu.askerSayisi;
            sonuc.Add(1);
            sonuc.Add(toplam - 1);
            return sonuc;
        }
int Risk1.AI3.getDahaGucluDusmanSayisi (Bolge b) [inline]
Definition at line 102 of file AI3.cs.
References Risk1.Ordu.askerSayisi, Risk1.Bolge.komsular, Risk1.Bolge.ordu, and Risk1.Bolge.sahip.
Referenced by Risk1.AI3.getTerritoriesIndexToPlaceNewArmies().
        {
            int toplam = 0;
            foreach (Bolge bb in b.komsular)
            {
                if (bb.sahip != b.sahip && b.ordu.askerSayisi<bb.ordu.askerSayisi)
                {
                    toplam++;
                }
            }
            return toplam;
        }
override string Risk1.AI3.getName () [inline, virtual]
Bu metod Yapay zekanın ismini döndürmelidir.
Returns:
name
Implements Risk1.ArtificalIntelligence.
Definition at line 15 of file AI3.cs.
References Risk1.AI3.name.
        {
            return name;
        }
override List<int> Risk1.AI3.getSavasBolgeIndexleri (GameData form1) [inline, virtual]
Bu metod savaş yapılacak bolgelerin indexlerini belirlemek içindir.
Returns:
Metod geriye iki elemanlı bir liste döndürür. Birinci eleman nereden saldırı yapılacağını ikinci eleman ise nereye saldırı yapılacağını gösterir. Burada iki bolgenin komsu olmasına dikkat edilmelidir.
Implements Risk1.ArtificalIntelligence.
Definition at line 116 of file AI3.cs.
References Risk1.Ordu.askerSayisi, Risk1.Bolge.index, Risk1.Bolge.komsular, Risk1.Bolge.ordu, and Risk1.Bolge.sahip.
        {
            List<int> sonuc = new List<int>();
            foreach (Bolge b in f1.players[f1.turn].bolgeler)
            {
                foreach (Bolge komsu in b.komsular)
                {
                    if (b.ordu.askerSayisi > komsu.ordu.askerSayisi+30 && b.sahip != komsu.sahip)
                    {
                        sonuc.Add(b.index);
                        sonuc.Add(komsu.index);
                    }
                }
            }
            return sonuc;
        }
override List<int> Risk1.AI3.getTerritoriesIndexToPlaceNewArmies (GameData form1) [inline, virtual]
Oyuncu her turn'de kazandığı yeni askerleri hangi bolgelere yerleştireceğini bu metod sayesinde belirler.
Parameters:
form1
Returns:
Askerlerin yerleştirilmek istendiği bolge indexleri
Implements Risk1.ArtificalIntelligence.
Definition at line 40 of file AI3.cs.
References Risk1.GameData.bolgeler, Risk1.AI3.getDahaGucluDusmanSayisi(), Risk1.ArtificalIntelligence.getEnGucluBolgemIndex(), Risk1.ArtificalIntelligence.getKomsuDusmanSayisi(), Risk1.Bolge.index, Risk1.GameData.players, and Risk1.GameData.turn.
        {
            List<int> gonderilecekler = new List<int>();
            int orduyuNereyeKoyalim = -1;
            if (getKomsuDusmanSayisi(f1.bolgeler[getEnGucluBolgemIndex(f1)]) > 0)
            {
                orduyuNereyeKoyalim = getEnGucluBolgemIndex(f1);
            }
            else
            {
                foreach (Bolge b in f1.players[f1.turn].bolgeler)
                {
                    if (getDahaGucluDusmanSayisi(b) > 0)
                    {
                        orduyuNereyeKoyalim = b.index;
                    }
                }
            }
            if (orduyuNereyeKoyalim == -1)
            {
                foreach (Bolge b in f1.players[f1.turn].bolgeler)
                {
                    if (getKomsuDusmanSayisi(b) > 0)
                    {
                        orduyuNereyeKoyalim = b.index;
                    }
                }
            }
            int k=f1.players[f1.turn].yeniAskerler;
            for (int i = 0; i <k ; i++)
            {
                gonderilecekler.Add(orduyuNereyeKoyalim);
            }
            return gonderilecekler;
        }
override int Risk1.AI3.getTerritoryToPlaceFirstArmies (GameData form1) [inline, virtual]
İlk başta tüm oyunculara verilen ilk askerler dağıtılırken her oyuncuya tek tek askerlerini nereye koyması gerektiği sorulur bu metod ilk ordunun koyulması gereken bolgenin indexini dondurur.
Parameters:
form1
Returns:
ilk ordunun koyulması gereken bolgenin indexini dondurur
Implements Risk1.ArtificalIntelligence.
Definition at line 26 of file AI3.cs.
References Risk1.ArtificalIntelligence.getKomsuDusmanSayisi(), and Risk1.Bolge.index.
        {
            foreach (Bolge b in f1.players[f1.turn].bolgeler)
            {
                if (getKomsuDusmanSayisi(b) > 0)
                {
                    return b.index;
                }
            }
            return f1.players[f1.turn].bolgeler[0].index;
        }
override int Risk1.AI3.requestTerritory (GameData form1) [inline, virtual]
Bu metod bölgeler seçilirken istenen bolgenin indexini dondurmektedir.
Parameters:
form1
Returns:
istenen bolgenin indexi
Implements Risk1.ArtificalIntelligence.
Definition at line 21 of file AI3.cs.
References Risk1.ArtificalIntelligence.rastgeleBolgeSec().
        {
            return rastgeleBolgeSec(f1);
        }
override bool Risk1.AI3.saldiracanMi (GameData form1) [inline, virtual]
Bu metod kullanıcının saldırı yapmak isteyip istemediğini belirler.
Parameters:
form1
Returns:
Eğer saldırı yapmak istiyorsa true istemiyorsa false döndürür.
Implements Risk1.ArtificalIntelligence.
Definition at line 97 of file AI3.cs.
References Risk1.AI3.devam().
        {
            return devam(f1);
        }
Member Data Documentation
int Risk1.AI3.aiid = 3 [static]
Definition at line 11 of file AI3.cs.
Referenced by Risk1.ChangePlayer.HangiYapayZekaSecili().
string Risk1.AI3.name = "Babak" [static]
Definition at line 12 of file AI3.cs.
Referenced by Risk1.AI3.getName(), and Risk1.ChangePlayer.HangiYapayZekaSecili().
Image Risk1.AI3.resim = Properties.Resources.babek [static]
Definition at line 13 of file AI3.cs.
Referenced by Risk1.ChangePlayer.HangiYapayZekaSecili().
The documentation for this class was generated from the following file:
Risk1/AI3.cs