ANKARISK: Risk1.DistanceCalculator Class Reference
Risk1.DistanceCalculator Class Reference
Public Member Functions
IDictionary< string, double > CalculateDistances (Graph graph, string startingNode)
List< String > getYol (string basalangic, string bitis, Graph graph)
Private Member Functions
void InitialiseGraph (Graph graph, string startingNode)
void ProcessGraph (Graph graph, string startingNode)
void ProcessNode (Node node, List< Node > queue)
IDictionary< string, double > ExtractDistances (Graph graph)
Detailed Description
Definition at line 8 of file DistanceCalculator.cs.
Member Function Documentation
IDictionary<string, double> Risk1.DistanceCalculator.CalculateDistances (Graph graph, string startingNode) [inline]
Definition at line 10 of file DistanceCalculator.cs.
References Risk1.DistanceCalculator.ExtractDistances(), Risk1.DistanceCalculator.InitialiseGraph(), and Risk1.DistanceCalculator.ProcessGraph().
        {
            if (!graph.Nodes.Any(n => n.Key == startingNode))
                throw new ArgumentException("Starting node must be in graph.");
            InitialiseGraph(graph, startingNode);
            ProcessGraph(graph, startingNode);
            return ExtractDistances(graph);
        }
IDictionary<string, double> Risk1.DistanceCalculator.ExtractDistances (Graph graph) [inline, private]
Definition at line 87 of file DistanceCalculator.cs.
Referenced by Risk1.DistanceCalculator.CalculateDistances().
        {
            return graph.Nodes.ToDictionary(n => n.Key, n => n.Value.DistanceFromStart);
        }
List<String> Risk1.DistanceCalculator.getYol (string basalangic, string bitis, Graph graph) [inline]
Definition at line 61 of file DistanceCalculator.cs.
        {
            List<String> yol = new List<String>();
            yol.Add(bitis);
            foreach (Node n in graph.Nodes.Values)
            {
                if (n.parent != null)
                {
                    if (n.Name == bitis)
                    {
                        Node temp = n;
                        while (temp.parent.Name != basalangic)
{
                            yol.Add(temp.parent.Name);
                            temp = temp.parent;
                        }
                        break;
                    }
                }
            }
            return yol;
        }
void Risk1.DistanceCalculator.InitialiseGraph (Graph graph, string startingNode) [inline, private]
Definition at line 20 of file DistanceCalculator.cs.
Referenced by Risk1.DistanceCalculator.CalculateDistances().
        {
            foreach (Node node in graph.Nodes.Values)
                node.DistanceFromStart = double.PositiveInfinity;
            graph.Nodes[startingNode].DistanceFromStart = 0;
        }
void Risk1.DistanceCalculator.ProcessGraph (Graph graph, string startingNode) [inline, private]
Definition at line 28 of file DistanceCalculator.cs.
References Risk1.DistanceCalculator.ProcessNode().
Referenced by Risk1.DistanceCalculator.CalculateDistances().
        {
            bool finished = false;
            var queue = graph.Nodes.Values.ToList();
            while (!finished)
            {
                Node nextNode = queue.OrderBy(n => n.DistanceFromStart).FirstOrDefault(n => !double.IsPositiveInfinity(n.DistanceFromStart));
                if (nextNode != null)
                {
                    ProcessNode(nextNode, queue);
                    queue.Remove(nextNode);
                }
                else
                {
                    finished = true;
                }
            }
        }
void Risk1.DistanceCalculator.ProcessNode (Node node, List< Node > queue) [inline, private]
Definition at line 47 of file DistanceCalculator.cs.
Referenced by Risk1.DistanceCalculator.ProcessGraph().
        {
            var connections = node.Connections.Where(c => queue.Contains(c.Target));
            foreach (var connection in connections)
            {
                double distance = node.DistanceFromStart + connection.Distance;
                if (distance < connection.Target.DistanceFromStart)
                {
                    connection.Target.DistanceFromStart = distance;
                    connection.Target.parent = node;
                }
            }
        }
The documentation for this class was generated from the following file:
Risk1/DistanceCalculator.cs