ANKARISK: Risk1.Form1 Class Reference
Risk1.Form1 Class Reference
Classes
class MyListViewSorter
Public Member Functions
Form1 ()
void endGame ()
void updateGameData ()
GameData getGameData ()
void changeInfo (String s)
void changeLabel (Bolge bol)
void changeTerritoryColor (Bolge b, Player p)
void changeDenizColor (Color c)
void changeSinirColor (Color c)
void refreshGame ()
void hideStatistics ()
void changeTurn ()
void olduMu ()
int getNextTurn ()
void changeStatistics ()
void ganimetBolgseiniBildir ()
void changePanel ()
Public Attributes
List< Bolge > bolgeler = new List<Bolge>()
List< Player > players = new List<Player>()
List< Continent > kitalar = new List<Continent>()
int turn = 0
int ilkAskerler = 0
int ilkAskerSayisi = 15
bool isArmyMoved = false
bool isRandom = true
int ganimetKazanci = 1
AI ai = new AI()
AI2 ai2 = new AI2()
AI3 ai3 = new AI3()
AI4 ai4 = new AI4()
List< ArtificalIntelligence > yapayzekalar = new List<ArtificalIntelligence>()
List< Nokta > deniz = new List<Nokta>()
List< Nokta > sinirlar = new List<Nokta>()
List< List< int > > history = new List<List<int>>()
GameData gameData = new GameData()
Statistics statistics = new Statistics()
bool yeniOyunIptal = false
System.Windows.Forms.ColumnHeader player
System.Windows.Forms.ColumnHeader territories
System.Windows.Forms.ColumnHeader continents
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void pictureBox1_Click (object sender, EventArgs e)
ArtificalIntelligence yapayzeka ()
int kitaKazanci (Player p)
void hangiKitalaraSahip ()
bool kuzeyAmerika (List< Bolge > sahipOlduguBolgeler)
bool guneyAmerika (List< Bolge > sahipOlduguBolgeler)
bool afrika (List< Bolge > sahipOlduguBolgeler)
bool asya (List< Bolge > sahipOlduguBolgeler)
bool avrupa (List< Bolge > sahipOlduguBolgeler)
bool avustralya (List< Bolge > sahipOlduguBolgeler)
bool butunBolgelerSecildiMi ()
void Form1_Load (object sender, EventArgs e)
void button2_Click (object sender, EventArgs e)
void newGameToolStripMenuItem_Click (object sender, EventArgs e)
void endGameToolStripMenuItem_Click (object sender, EventArgs e)
void Form1_KeyDown (object sender, KeyEventArgs e)
void aboutToolStripMenuItem_Click (object sender, EventArgs e)
void rulesToolStripMenuItem_Click (object sender, EventArgs e)
void webSiteToolStripMenuItem_Click (object sender, EventArgs e)
void exitToolStripMenuItem_Click (object sender, EventArgs e)
void showStatisticsToolStripMenuItem_Click (object sender, EventArgs e)
void hideStatisticsToolStripMenuItem_Click (object sender, EventArgs e)
void pictureBox1_MouseMove (object sender, MouseEventArgs e)
void facebookPageToolStripMenuItem_Click (object sender, EventArgs e)
void pictureBox2_Click (object sender, EventArgs e)
void pictureBox3_Click (object sender, EventArgs e)
void label1_Click (object sender, EventArgs e)
void label2_Click (object sender, EventArgs e)
void label3_Click (object sender, EventArgs e)
void label4_Click (object sender, EventArgs e)
void label5_Click (object sender, EventArgs e)
void label6_Click (object sender, EventArgs e)
void label7_Click (object sender, EventArgs e)
void label8_Click (object sender, EventArgs e)
void label9_Click (object sender, EventArgs e)
void label10_Click (object sender, EventArgs e)
void label11_Click (object sender, EventArgs e)
void label12_Click (object sender, EventArgs e)
void label13_Click (object sender, EventArgs e)
void label14_Click (object sender, EventArgs e)
void label15_Click (object sender, EventArgs e)
void label16_Click (object sender, EventArgs e)
void label17_Click (object sender, EventArgs e)
void label18_Click (object sender, EventArgs e)
void label19_Click (object sender, EventArgs e)
void label20_Click (object sender, EventArgs e)
void label21_Click (object sender, EventArgs e)
void label22_Click (object sender, EventArgs e)
void label26_Click (object sender, EventArgs e)
void label25_Click (object sender, EventArgs e)
void label24_Click (object sender, EventArgs e)
void label23_Click (object sender, EventArgs e)
void label41_Click (object sender, EventArgs e)
void label40_Click (object sender, EventArgs e)
void label42_Click (object sender, EventArgs e)
void label39_Click (object sender, EventArgs e)
void label31_Click (object sender, EventArgs e)
void label30_Click (object sender, EventArgs e)
void label27_Click (object sender, EventArgs e)
void label29_Click (object sender, EventArgs e)
void label28_Click (object sender, EventArgs e)
void label34_Click (object sender, EventArgs e)
void label35_Click (object sender, EventArgs e)
void label37_Click (object sender, EventArgs e)
void label38_Click (object sender, EventArgs e)
void label33_Click (object sender, EventArgs e)
void label36_Click (object sender, EventArgs e)
void label32_Click (object sender, EventArgs e)
void changeStyleToolStripMenuItem_Click (object sender, EventArgs e)
void showHistoryToolStripMenuItem_Click (object sender, EventArgs e)
void followUsOnTwitterToolStripMenuItem_Click (object sender, EventArgs e)
void timer1_Tick (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Static Private Member Functions
static bool Find1 (Nokta n)
static bool Find2 (Nokta n)
static bool Find3 (Nokta n)
static bool Find4 (Nokta n)
static bool Find5 (Nokta n)
static bool Find6 (Nokta n)
static bool Find7 (Nokta n)
static bool Find8 (Nokta n)
static bool Find9 (Nokta n)
static bool Find10 (Nokta n)
static bool Find11 (Nokta n)
static bool Find12 (Nokta n)
static bool Find13 (Nokta n)
static bool Find14 (Nokta n)
static bool Find15 (Nokta n)
static bool Find16 (Nokta n)
static bool Find17 (Nokta n)
static bool Find18 (Nokta n)
static bool Find19 (Nokta n)
static bool Find20 (Nokta n)
static bool Find21 (Nokta n)
static bool Find22 (Nokta n)
static bool Find23 (Nokta n)
static bool Find24 (Nokta n)
static bool Find25 (Nokta n)
static bool Find26 (Nokta n)
static bool Find27 (Nokta n)
static bool Find28 (Nokta n)
static bool Find29 (Nokta n)
static bool Find30 (Nokta n)
static bool Find31 (Nokta n)
static bool Find32 (Nokta n)
static bool Find33 (Nokta n)
static bool Find34 (Nokta n)
static bool Find35 (Nokta n)
static bool Find36 (Nokta n)
static bool Find37 (Nokta n)
static bool Find38 (Nokta n)
static bool Find39 (Nokta n)
static bool Find40 (Nokta n)
static bool Find41 (Nokta n)
static bool Find42 (Nokta n)
static bool FindDeniz (Nokta n)
static bool FindSinir (Nokta n)
Private Attributes
List< Nokta > noktalar = new List<Nokta>()
Bolge ilkTiklananBolge = null
int ganimetBolgesi
List< Label > labels = new List<Label>()
int state = 0
Label label = null
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.PictureBox pictureBox1
System.Windows.Forms.Panel panel1
System.Windows.Forms.Button button2
System.Windows.Forms.TextBox txtInfo
System.Windows.Forms.TextBox txtPlayer
System.Windows.Forms.Label label1
System.Windows.Forms.Label label2
System.Windows.Forms.Label label3
System.Windows.Forms.Label label4
System.Windows.Forms.Label label5
System.Windows.Forms.Label label6
System.Windows.Forms.Label label7
System.Windows.Forms.Label label8
System.Windows.Forms.Label label9
System.Windows.Forms.Label label10
System.Windows.Forms.Label label11
System.Windows.Forms.Label label12
System.Windows.Forms.Label label13
System.Windows.Forms.Label label14
System.Windows.Forms.Label label15
System.Windows.Forms.Label label16
System.Windows.Forms.Label label17
System.Windows.Forms.Label label18
System.Windows.Forms.Label label19
System.Windows.Forms.Label label20
System.Windows.Forms.Label label21
System.Windows.Forms.Label label22
System.Windows.Forms.Label label23
System.Windows.Forms.Label label24
System.Windows.Forms.Label label25
System.Windows.Forms.Label label26
System.Windows.Forms.Label label27
System.Windows.Forms.Label label28
System.Windows.Forms.Label label29
System.Windows.Forms.Label label30
System.Windows.Forms.Label label31
System.Windows.Forms.Label label32
System.Windows.Forms.Label label33
System.Windows.Forms.Label label34
System.Windows.Forms.Label label35
System.Windows.Forms.Label label36
System.Windows.Forms.Label label37
System.Windows.Forms.Label label38
System.Windows.Forms.Label label39
System.Windows.Forms.Label label40
System.Windows.Forms.Label label41
System.Windows.Forms.Label label42
System.Windows.Forms.ToolStripMenuItem gameToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem newGameToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem endGameToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem exitToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem optionsToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem rulesToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem statisticsToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem helpToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem aboutToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem webSiteToolStripMenuItem
System.Windows.Forms.MenuStrip menuStrip1
System.Windows.Forms.ToolStripMenuItem showStatisticsToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem hideStatisticsToolStripMenuItem
System.Windows.Forms.ListView listView1
System.Windows.Forms.ColumnHeader armies
System.Windows.Forms.ToolStripMenuItem facebookPageToolStripMenuItem
System.Windows.Forms.PictureBox pictureBox2
System.Windows.Forms.PictureBox pictureBox3
System.Windows.Forms.ToolStripMenuItem changeStyleToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem showHistoryToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem followUsOnTwitterToolStripMenuItem
System.Windows.Forms.Timer timer1
System.Windows.Forms.PictureBox pictureBox4
Detailed Description
Definition at line 15 of file Form1.cs.
Constructor & Destructor Documentation
Risk1.Form1.Form1 () [inline]
Definition at line 17 of file Form1.cs.
References Risk1.Form1.InitializeComponent().
        {
            this.KeyPreview = true;
            InitializeComponent();
        }
Member Function Documentation
void Risk1.Form1.aboutToolStripMenuItem_Click (object sender, EventArgs e) [inline, private]
Definition at line 2585 of file Form1.cs.
        {
            About a = new About();
            a.ShowDialog();
        }
bool Risk1.Form1.afrika (List< Bolge > sahipOlduguBolgeler) [inline, private]
Definition at line 974 of file Form1.cs.
References Risk1.Form1.bolgeler, and Risk1.Form1.kitalar.
Referenced by Risk1.Form1.hangiKitalaraSahip(), and Risk1.Form1.kitaKazanci().
        {
            foreach (Bolge b in kitalar[2].bolgeler)
            {
                if (!sahipOlduguBolgeler.Contains(b))
                {
                    return false;
                }
            }
            return true;
        }
bool Risk1.Form1.asya (List< Bolge > sahipOlduguBolgeler) [inline, private]
Definition at line 986 of file Form1.cs.
References Risk1.Form1.bolgeler, and Risk1.Form1.kitalar.
Referenced by Risk1.Form1.hangiKitalaraSahip(), and Risk1.Form1.kitaKazanci().
        {
            foreach (Bolge b in kitalar[3].bolgeler)
            {
                if (!sahipOlduguBolgeler.Contains(b))
                {
                    return false;
                }
            }
            return true;
        }
bool Risk1.Form1.avrupa (List< Bolge > sahipOlduguBolgeler) [inline, private]
Definition at line 998 of file Form1.cs.
References Risk1.Form1.bolgeler, and Risk1.Form1.kitalar.
Referenced by Risk1.Form1.hangiKitalaraSahip(), and Risk1.Form1.kitaKazanci().
        {
            foreach (Bolge b in kitalar[4].bolgeler)
            {
                if (!sahipOlduguBolgeler.Contains(b))
                {
                    return false;
                }
            }
            return true;
        }
bool Risk1.Form1.avustralya (List< Bolge > sahipOlduguBolgeler) [inline, private]
Definition at line 1010 of file Form1.cs.
References Risk1.Form1.bolgeler, and Risk1.Form1.kitalar.
Referenced by Risk1.Form1.hangiKitalaraSahip(), and Risk1.Form1.kitaKazanci().
        {
            foreach (Bolge b in kitalar[5].bolgeler)
            {
                if (!sahipOlduguBolgeler.Contains(b))
                {
                    return false;
                }
            }
            return true;
        }
void Risk1.Form1.button2_Click (object sender, EventArgs e) [inline, private]
Definition at line 2443 of file Form1.cs.
References Risk1.Form1.changeTurn(), Risk1.Form1.ilkTiklananBolge, and Risk1.Form1.state.
        {
            changeTurn();
            ilkTiklananBolge = null;
            state = 0;
        }
bool Risk1.Form1.butunBolgelerSecildiMi () [inline, private]
Definition at line 1036 of file Form1.cs.
References Risk1.Form1.bolgeler, and Risk1.Bolge.sahipli.
Referenced by Risk1.Form1.changePanel(), Risk1.Form1.changeTurn(), and Risk1.Form1.pictureBox1_Click().
        {
            foreach (Bolge b in bolgeler)
            {
                if (b.sahipli == false)
                {
                    return false;
                }
            }
            return true;
        }
void Risk1.Form1.changeDenizColor (Color c) [inline]
Definition at line 490 of file Form1.cs.
References Risk1.Form1.deniz, Risk1.Form1.pictureBox1, Risk1.Nokta.point, and Risk1.Nokta.renk.
Referenced by Risk1.ChangeStyle.button2_Click(), and Risk1.Form1.Form1_Load().
        {
            Bitmap bitmap = new Bitmap(pictureBox1.Image);
            foreach (Nokta n in deniz)
            {
                n.renk = c;
                bitmap.SetPixel(n.point.X, n.point.Y, c);
                pictureBox1.Image = bitmap;
            }
        }
void Risk1.Form1.changeInfo (String s) [inline]
Definition at line 260 of file Form1.cs.
References Risk1.Form1.txtInfo.
Referenced by Risk1.Form1.changeTurn(), and Risk1.Form1.pictureBox1_Click().
        {
            txtInfo.Text = s;
        }
void Risk1.Form1.changeLabel (Bolge bol) [inline]
Definition at line 265 of file Form1.cs.
References Risk1.Ordu.askerSayisi, Risk1.Form1.label1, Risk1.Form1.label10, Risk1.Form1.label11, Risk1.Form1.label12, Risk1.Form1.label13, Risk1.Form1.label14, Risk1.Form1.label15, Risk1.Form1.label16, Risk1.Form1.label17, Risk1.Form1.label18, Risk1.Form1.label19, Risk1.Form1.label2, Risk1.Form1.label20, Risk1.Form1.label21, Risk1.Form1.label22, Risk1.Form1.label23, Risk1.Form1.label24, Risk1.Form1.label25, Risk1.Form1.label26, Risk1.Form1.label27, Risk1.Form1.label28, Risk1.Form1.label29, Risk1.Form1.label3, Risk1.Form1.label30, Risk1.Form1.label31, Risk1.Form1.label32, Risk1.Form1.label33, Risk1.Form1.label34, Risk1.Form1.label35, Risk1.Form1.label36, Risk1.Form1.label37, Risk1.Form1.label38, Risk1.Form1.label39, Risk1.Form1.label4, Risk1.Form1.label40, Risk1.Form1.label41, Risk1.Form1.label42, Risk1.Form1.label5, Risk1.Form1.label6, Risk1.Form1.label7, Risk1.Form1.label8, Risk1.Form1.label9, Risk1.Bolge.number, and Risk1.Bolge.ordu.
Referenced by Risk1.Form1.changeTurn(), Risk1.Form1.newGameToolStripMenuItem_Click(), Risk1.Form1.pictureBox1_Click(), Risk1.SaldiriEkrani.warAttack(), Risk1.SaldiriEkrani.warDoORDie(), and Risk1.SaldiriEkrani.warDoORDieForAi().
        {
            if (bol.number == 1)
            {
                label1.Text = bol.ordu.askerSayisi.ToString();
                label1.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            }
            if (bol.number == 2)
            {
                label2.Text = bol.ordu.askerSayisi.ToString();
                label2.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            }
            if (bol.number == 3)
            {
                label3.Text = bol.ordu.askerSayisi.ToString();
                label3.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            }
            if (bol.number == 4)
            {
                label4.Text = bol.ordu.askerSayisi.ToString();
                label4.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            }
            if (bol.number == 5)
            {
                label5.Text = bol.ordu.askerSayisi.ToString();
                label5.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            }
            if (bol.number == 6)
            {
                label6.Text = bol.ordu.askerSayisi.ToString();
                label6.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            }
            if (bol.number == 7)
            {
                label7.Text = bol.ordu.askerSayisi.ToString();
                label7.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            }
            if (bol.number == 8)
            {
                label8.Text = bol.ordu.askerSayisi.ToString();
                label8.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            }
            if (bol.number == 9)
            {
                label9.Text = bol.ordu.askerSayisi.ToString();
                label9.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            }
            if (bol.number == 10)
            {
                label10.Text = bol.ordu.askerSayisi.ToString();
                label10.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            }
            if (bol.number == 11)
            {
                label11.Text = bol.ordu.askerSayisi.ToString();
                label11.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            }
            if (bol.number == 12)
            {
                label12.Text = bol.ordu.askerSayisi.ToString();
                label12.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            }
            if (bol.number == 13)
            {
                label13.Text = bol.ordu.askerSayisi.ToString();
                label13.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            }
            if (bol.number == 14)
            {
                label14.Text = bol.ordu.askerSayisi.ToString();
                label14.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            }
            if (bol.number == 15)
            {
                label15.Text = bol.ordu.askerSayisi.ToString();
                label15.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            }
            if (bol.number == 16)
            {
                label16.Text = bol.ordu.askerSayisi.ToString();
                label16.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            }
            if (bol.number == 17)
            {
                label17.Text = bol.ordu.askerSayisi.ToString();
                label17.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            }
            if (bol.number == 18)
            {
                label18.Text = bol.ordu.askerSayisi.ToString();
                label18.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            }
            if (bol.number == 19)
            {
                label19.Text = bol.ordu.askerSayisi.ToString();
                label19.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            }
            if (bol.number == 20)
            {
                label20.Text = bol.ordu.askerSayisi.ToString();
                label20.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            }
            if (bol.number == 21)
            {
                label21.Text = bol.ordu.askerSayisi.ToString();
                label21.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            }
            if (bol.number == 22)
            {
                label22.Text = bol.ordu.askerSayisi.ToString();
                label22.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            }
            if (bol.number == 23)
            {
                label23.Text = bol.ordu.askerSayisi.ToString();
                label23.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            }
            if (bol.number == 24)
            {
                label24.Text = bol.ordu.askerSayisi.ToString();
                label24.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            }
            if (bol.number == 25)
            {
                label25.Text = bol.ordu.askerSayisi.ToString();
                label25.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            }
            if (bol.number == 26)
            {
                label26.Text = bol.ordu.askerSayisi.ToString();
                label26.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            }
            if (bol.number == 27)
            {
                label27.Text = bol.ordu.askerSayisi.ToString();
                label27.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            }
            if (bol.number == 28)
            {
                label28.Text = bol.ordu.askerSayisi.ToString();
                label28.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            }
            if (bol.number == 29)
            {
                label29.Text = bol.ordu.askerSayisi.ToString();
                label29.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            }
            if (bol.number == 30)
            {
                label30.Text = bol.ordu.askerSayisi.ToString();
                label30.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            }
            if (bol.number == 31)
            {
                label31.Text = bol.ordu.askerSayisi.ToString();
                label31.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            }
            if (bol.number == 32)
            {
                label32.Text = bol.ordu.askerSayisi.ToString();
                label32.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            }
            if (bol.number == 33)
            {
                label33.Text = bol.ordu.askerSayisi.ToString();
                label33.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            }
            if (bol.number == 34)
            {
                label34.Text = bol.ordu.askerSayisi.ToString();
                label34.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            }
            if (bol.number == 35)
            {
                label35.Text = bol.ordu.askerSayisi.ToString();
                label35.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            }
            if (bol.number == 36)
            {
                label36.Text = bol.ordu.askerSayisi.ToString();
                label36.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            }
            if (bol.number == 37)
            {
                label37.Text = bol.ordu.askerSayisi.ToString();
                label37.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            }
            if (bol.number == 38)
            {
                label38.Text = bol.ordu.askerSayisi.ToString();
                label38.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            }
            if (bol.number == 39)
            {
                label39.Text = bol.ordu.askerSayisi.ToString();
                label39.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            }
            if (bol.number == 40)
            {
                label40.Text = bol.ordu.askerSayisi.ToString();
                label40.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            }
            if (bol.number == 41)
            {
                label41.Text = bol.ordu.askerSayisi.ToString();
                label41.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            }
            if (bol.number == 42)
            {
                label42.Text = bol.ordu.askerSayisi.ToString();
                label42.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            }
        }
void Risk1.Form1.changePanel () [inline]
Definition at line 2410 of file Form1.cs.
References Risk1.Form1.butunBolgelerSecildiMi(), Risk1.Form1.ilkAskerler, Risk1.Form1.players, Risk1.Form1.turn, Risk1.Form1.txtInfo, and Risk1.Form1.txtPlayer.
Referenced by Risk1.Form1.changeTurn().
        {
            txtPlayer.Text = players[turn].name;
            txtPlayer.BackColor = players[turn].color;
            if (ilkAskerler == 0  && players[turn].isHuman)
            {
                txtInfo.Text = "You have " + players[turn].yeniAskerler.ToString() + " armies left to place [+SHIFT=place all]";
            }
            if (!players[turn].isHuman)
            {
                txtInfo.Text = "is playing...";
            }
            else
            {
                if (players[turn].isHuman)
                {
                    if (!butunBolgelerSecildiMi())
                    {
                        txtInfo.Text = "Please claim a territory";
                    }
                    else if (ilkAskerler > 0)
                    {
                        txtInfo.Text = "You have " + players[turn].ilkAskerSayisi + " armies left to place. Please place an army";
                    }
                }
            }
            txtPlayer.Refresh();
            txtInfo.Refresh();
        }
void Risk1.Form1.changeSinirColor (Color c) [inline]
Definition at line 501 of file Form1.cs.
References Risk1.Form1.pictureBox1, Risk1.Nokta.point, Risk1.Nokta.renk, and Risk1.Form1.sinirlar.
Referenced by Risk1.Form1.Form1_Load().
        {
            Bitmap bitmap = new Bitmap(pictureBox1.Image);
            foreach (Nokta n in sinirlar)
            {
                n.renk = c;
                bitmap.SetPixel(n.point.X, n.point.Y, c);
                pictureBox1.Image = bitmap;
            }
        }
void Risk1.Form1.changeStatistics () [inline]
Definition at line 1048 of file Form1.cs.
References Risk1.Player.color, Risk1.Player.getNumberOfTerritories(), Risk1.Player.getTotalNumberOfArmies(), Risk1.Form1.hangiKitalaraSahip(), Risk1.Player.kitalar, Risk1.Form1.listView1, Risk1.Player.name, and Risk1.Form1.players.
Referenced by Risk1.Form1.changeTurn(), Risk1.Form1.newGameToolStripMenuItem_Click(), Risk1.Form1.olduMu(), and Risk1.Form1.pictureBox1_Click().
        {
            try
            {
                if (this.Width == 1053)
                {
                    hangiKitalaraSahip();
                    listView1.Items.Clear();
                    int k = 0;
                    foreach (Player p in players)
                    {
                        ListViewItem lvitem = new ListViewItem();
                        lvitem.Text = p.name;
                        lvitem.BackColor = p.color;
                        lvitem.SubItems.Add(p.getNumberOfTerritories().ToString());
                        lvitem.SubItems.Add(p.getTotalNumberOfArmies().ToString());
                        lvitem.SubItems.Add(p.kitalar);
                        listView1.Items.Add(lvitem);
                        k++;
                    }
                    this.listView1.ListViewItemSorter = new MyListViewSorter(2);
                    this.listView1.Sort();
                }
            }
            catch
            {
            }
        }
void Risk1.Form1.changeStyleToolStripMenuItem_Click (object sender, EventArgs e) [inline, private]
Definition at line 2863 of file Form1.cs.
        {
            ChangeStyle cs = new ChangeStyle(this);
            cs.ShowDialog();
        }
void Risk1.Form1.changeTerritoryColor (Bolge b, Player p) [inline]
Definition at line 480 of file Form1.cs.
References Risk1.Form1.pictureBox1, and Risk1.Nokta.point.
Referenced by Risk1.Form1.changeTurn(), Risk1.Form1.newGameToolStripMenuItem_Click(), Risk1.Form1.pictureBox1_Click(), Risk1.SaldiriEkrani.warAttack(), Risk1.SaldiriEkrani.warDoORDie(), and Risk1.SaldiriEkrani.warDoORDieForAi().
        {
            Bitmap bitmap = new Bitmap(pictureBox1.Image);
            foreach (Nokta n in b.noktalar)
            {
                bitmap.SetPixel(n.point.X, n.point.Y, p.color);
                pictureBox1.Image = bitmap;
            }
        }
void Risk1.Form1.changeTurn () [inline]
Definition at line 581 of file Form1.cs.
References Risk1.Ordu.askerSayisi, Risk1.ArtificalIntelligence.askerTransferiYap(), Risk1.ArtificalIntelligence.askerTransferiYapacakmisin(), Risk1.Form1.bolgeler, Risk1.Form1.button2, Risk1.Form1.butunBolgelerSecildiMi(), Risk1.Form1.changeInfo(), Risk1.Form1.changeLabel(), Risk1.Form1.changePanel(), Risk1.Form1.changeStatistics(), Risk1.Form1.changeTerritoryColor(), Risk1.ArtificalIntelligence.devam(), Risk1.Form1.ganimetBolgseiniBildir(), Risk1.Form1.getGameData(), Risk1.Form1.getNextTurn(), Risk1.ArtificalIntelligence.getSavasBolgeIndexleri(), Risk1.ArtificalIntelligence.getTerritoriesIndexToPlaceNewArmies(), Risk1.ArtificalIntelligence.getTerritoryToPlaceFirstArmies(), Risk1.Form1.ilkAskerler, Risk1.Player.isHuman, Risk1.Bolge.isim, Risk1.Form1.isRandom, Risk1.Form1.kitaKazanci(), Risk1.Form1.olduMu(), Risk1.Bolge.ordu, Risk1.Form1.pictureBox1, Risk1.Form1.players, Risk1.Form1.refreshGame(), Risk1.ArtificalIntelligence.requestTerritory(), Risk1.ArtificalIntelligence.saldiracanMi(), Risk1.Form1.showHistoryToolStripMenuItem, Risk1.Form1.turn, Risk1.Form1.txtInfo, Risk1.SaldiriEkrani.warDoORDieForAi(), and Risk1.Form1.yapayzeka().
Referenced by Risk1.Form1.button2_Click(), Risk1.Form1.Form1_KeyDown(), Risk1.Form1.newGameToolStripMenuItem_Click(), and Risk1.Form1.pictureBox1_Click().
        {
            int toplamInsan = 0;
            foreach (Player p in players)
            {
                if (p.isHuman)
                {
                    toplamInsan++;
                }
            }
            if (toplamInsan == 0)
            {
                button2.Enabled = false;
                pictureBox1.Enabled = false;
                //if (this.Height != 602)
                //{
                //    this.Height = 602;
                //}
                //if (listView1.Enabled)
                //{
                //    hideStatistics();
                //}
                refreshGame();
                showHistoryToolStripMenuItem.Enabled = true;
                Application.DoEvents();
            }
            if ((turn + 1) < players.Count)
            {
                turn++;
            }
            else
            {
                turn = 0;
            }
            if (ilkAskerler == 0)
            {
                players[turn].yeniAskerler = (3 + kitaKazanci(players[turn]));
            }
            changePanel();
            players[turn].askerSayisiTarihi.Add(players[turn].getTotalNumberOfArmies());
            if (players[turn].isHuman)//insansa
            {
                button2.Enabled = false;
            }
            else//Bilgisayarda oynama sras//////////////////////////////////////////////////////////////////////////////////////
            {
                changePanel();
                if (players.Count == 1)
                {
                    return;
                }
                changeStatistics();
                if (!butunBolgelerSecildiMi()  && !isRandom)//butun bolgeler seimemise bilgisayar bolge seecek
                {
                    int index = 0;
                    index = yapayzeka().requestTerritory(getGameData());
                    if (index < 0 || index > 41)
                    {
                        MessageBox.Show(yapayzeka().getName() + " blge isteme ilemi zaman kural ihlali yapt. Index:" + index);
                    }
                    if (bolgeler[index].sahipli)
                    {
                        MessageBox.Show("Yapay Zeka Sahipli bir blge istedi");
                    }
                    if (!bolgeler[index].sahipli)
                    {
                        bolgeler[index].sahip = players[turn];
                        bolgeler[index].sahipli = true;
                        players[turn].bolgeler.Add(bolgeler[index]);
                        changeTerritoryColor(bolgeler[index], players[turn]);
                        txtInfo.Text = players[getNextTurn()].name + " please choose a territory";
                        changeLabel(bolgeler[index]);
                        changeTurn();
                        return;
                    }
                    if (butunBolgelerSecildiMi())
                    {
                        changeInfo(players[turn].name + " please place your army. [" + Math.Floor((double)(ilkAskerler / players.Count)).ToString() + "]");
                        showHistoryToolStripMenuItem.Enabled = true;
                    }
                }
                else
                {
                    if (ilkAskerler > 0)//lk Askerleri Datlmasmas bitene kadar
                    {
                        Bolge bol=null;
                        bol = bolgeler[yapayzeka().getTerritoryToPlaceFirstArmies(getGameData())];
                        if (bolgeler[ yapayzeka().getTerritoryToPlaceFirstArmies(getGameData())].sahip!=players[turn])
{
                            MessageBox.Show(yapayzeka().getName() + " kendine ait olmayan yere asker koymak istedi");
                            MessageBox.Show("Bolge ad:" + bol.isim);
                        }
                        ilkAskerler--;
                        if (ilkAskerler == 0)
{
                            changeInfo(players[turn].name + " please place your army. [" + players[turn].yeniAskerler + "]");
                            ganimetBolgseiniBildir();
                        }
                        players[turn].ilkAskerSayisi--;
                        bol.ordu.askerSayisi++;
                        changeLabel(bol);
                        changeTurn();
                        return;
                    }//ilk Askerlerin Datlmas Bittikten Sonra
                    else
                    {
                        //ncelikle her turn de verilen askerlerin yerine yerletirilmesi lazm
                        List<int> nereyekoyalim = new List<int>();
                        nereyekoyalim = yapayzeka().getTerritoriesIndexToPlaceNewArmies(getGameData());
                        foreach (int i in nereyekoyalim)
{
                            if (bolgeler[i].sahip != players[turn])
{
                                MessageBox.Show("Yapay zeka kendine ait olmayan yere asker koymak istedi");
                            }
                        }
                        int nereye = 0;
                        while (players[turn].yeniAskerler > 0)
{
                            players[turn].yeniAskerler--;
                            bolgeler[nereyekoyalim[nereye]].ordu.askerSayisi++;
                            changeLabel(bolgeler[nereyekoyalim[nereye]]);
                            if (players[turn].yeniAskerler == 0)
{
                                button2.Enabled = true;
                            }
                            nereye++;
                        }
                        //Askerler Datld imdi hucum yaplabilir
                        bool birSeyYapacanMi = true;
                        while (birSeyYapacanMi)
{
                            refreshGame();
                            birSeyYapacanMi = yapayzeka().devam(getGameData());
                            if (birSeyYapacanMi)
{
                                //Yapacaklar...
                                bool saldiracakMi = false;
                                saldiracakMi = yapayzeka().saldiracanMi(getGameData());
                                if (saldiracakMi)
{
                                    List<int> savasBolgeIndexleri = new List<int>();
                                    savasBolgeIndexleri = yapayzeka().getSavasBolgeIndexleri(getGameData());
                                    if (bolgeler[savasBolgeIndexleri[0]].sahip == bolgeler[savasBolgeIndexleri[1]].sahip)
{
                                        MessageBox.Show("Yapay zeka kendi bolgesine saldr yapmak istiyor...");
                                    }
                                    if (bolgeler[savasBolgeIndexleri[0]].komsular.Contains(bolgeler[savasBolgeIndexleri[1]]))
{
                                        SaldiriEkrani se = new SaldiriEkrani(bolgeler[savasBolgeIndexleri[0]], bolgeler[savasBolgeIndexleri[1]], this);
                                        se.warDoORDieForAi();
                                        olduMu();
                                    }
                                    else
{
                                        MessageBox.Show("Yapay Zeka Komusu olmad blgeye saldrma isteinde bulundu");
                                        MessageBox.Show(bolgeler[savasBolgeIndexleri[0]].isim + " ve " + bolgeler[savasBolgeIndexleri[1]].isim + " komu deil");
                                    }
                                }
                            }
                            else
{
                                bool transferVarMi = yapayzeka().askerTransferiYapacakmisin(getGameData());
                                if (transferVarMi)
{
                                    List<int> transferVerileri = new List<int>();
                                    transferVerileri= yapayzeka().askerTransferiYap(getGameData());
                                    if ((bolgeler[transferVerileri[0]].ordu.askerSayisi + bolgeler[transferVerileri[1]].ordu.askerSayisi) == (transferVerileri[2] + transferVerileri[3]))
{
                                        bolgeler[transferVerileri[0]].ordu.askerSayisi = transferVerileri[2];
                                        bolgeler[transferVerileri[1]].ordu.askerSayisi = transferVerileri[3];
                                        changeLabel(bolgeler[transferVerileri[0]]);
                                        changeLabel(bolgeler[transferVerileri[1]]);
                                    }
                                    else
{
                                        MessageBox.Show(players[turn].name + " isimli yapay zeka illegal aktarm denemesinde bulundu");
                                    }
                                }
                                changeTurn();
                                return;
                            }
                        }
                    }
                }
            }
        }
override void Risk1.Form1.Dispose (bool disposing) [inline, protected]
Clean up any resources being used.
Parameters:
disposing true if managed resources should be disposed; otherwise, false.
Definition at line 14 of file Form1.Designer.cs.
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }
void Risk1.Form1.endGame () [inline]
Definition at line 48 of file Form1.cs.
References Risk1.Form1.history, Risk1.Form1.ilkAskerler, Risk1.Form1.ilkAskerSayisi, Risk1.Form1.ilkTiklananBolge, Risk1.Form1.isArmyMoved, Risk1.Form1.labels, Risk1.Form1.players, Risk1.Form1.turn, and Risk1.Form1.yapayzekalar.
        {
            players.Clear();
            ilkTiklananBolge = null;
            turn = 0;
            ilkAskerler = 0;
            ilkAskerSayisi = 15;
            isArmyMoved = false;
            yapayzekalar.Clear();
            foreach (Label l in labels)
            {
                l.Text = "0";
            }
            history.Clear();
        }
void Risk1.Form1.endGameToolStripMenuItem_Click (object sender, EventArgs e) [inline, private]
Definition at line 2555 of file Form1.cs.
        {
            Application.Restart();
        }
void Risk1.Form1.exitToolStripMenuItem_Click (object sender, EventArgs e) [inline, private]
Definition at line 2606 of file Form1.cs.
        {
            this.Close();
        }
void Risk1.Form1.facebookPageToolStripMenuItem_Click (object sender, EventArgs e) [inline, private]
Definition at line 2638 of file Form1.cs.
        {
            System.Diagnostics.Process.Start("https://www.facebook.com/pages/Risk-Game/256463171079345");
        }
static bool Risk1.Form1.Find1 (Nokta n) [inline, static, private]
Definition at line 1880 of file Form1.cs.
References Risk1.Nokta.renk.
Referenced by Risk1.Form1.Form1_Load().
        {
            if (n.renk.Name == "ff006000")
            {
                return true;
            }
            else
            {
                return false;
            }
        }
static bool Risk1.Form1.Find10 (Nokta n) [inline, static, private]
Definition at line 1988 of file Form1.cs.
References Risk1.Nokta.renk.
Referenced by Risk1.Form1.Form1_Load().
        {
            if (n.renk.Name == "ffa00040")
            {
                return true;
            }
            else
            {
                return false;
            }
        }
static bool Risk1.Form1.Find11 (Nokta n) [inline, static, private]
Definition at line 2000 of file Form1.cs.
References Risk1.Nokta.renk.
Referenced by Risk1.Form1.Form1_Load().
        {
            if (n.renk.Name == "ffe06040")
            {
                return true;
            }
            else
            {
                return false;
            }
        }
static bool Risk1.Form1.Find12 (Nokta n) [inline, static, private]
Definition at line 2012 of file Form1.cs.
References Risk1.Nokta.renk.
Referenced by Risk1.Form1.Form1_Load().
        {
            if (n.renk.Name == "ffe00040")
            {
                return true;
            }
            else
            {
                return false;
            }
        }
static bool Risk1.Form1.Find13 (Nokta n) [inline, static, private]
Definition at line 2024 of file Form1.cs.
References Risk1.Nokta.renk.
Referenced by Risk1.Form1.Form1_Load().
        {
            if (n.renk.Name == "ffe0a040")
            {
                return true;
            }
            else
            {
                return false;
            }
        }
static bool Risk1.Form1.Find14 (Nokta n) [inline, static, private]
Definition at line 2036 of file Form1.cs.
References Risk1.Nokta.renk.
Referenced by Risk1.Form1.Form1_Load().
        {
            if (n.renk.Name == "ffc00080")
            {
                return true;
            }
            else
            {
                return false;
            }
        }
static bool Risk1.Form1.Find15 (Nokta n) [inline, static, private]
Definition at line 2048 of file Form1.cs.
References Risk1.Nokta.renk.
Referenced by Risk1.Form1.Form1_Load().
        {
            if (n.renk.Name == "ff006080")
            {
                return true;
            }
            else
            {
                return false;
            }
        }
static bool Risk1.Form1.Find16 (Nokta n) [inline, static, private]
Definition at line 2060 of file Form1.cs.
References Risk1.Nokta.renk.
Referenced by Risk1.Form1.Form1_Load().
        {
            if (n.renk.Name == "ffe00080")
            {
                return true;
            }
            else
            {
                return false;
            }
        }
static bool Risk1.Form1.Find17 (Nokta n) [inline, static, private]
Definition at line 2072 of file Form1.cs.
References Risk1.Nokta.renk.
Referenced by Risk1.Form1.Form1_Load().
        {
            if (n.renk.Name == "ff004080")
            {
                return true;
            }
            else
            {
                return false;
            }
        }
static bool Risk1.Form1.Find18 (Nokta n) [inline, static, private]
Definition at line 2084 of file Form1.cs.
References Risk1.Nokta.renk.
Referenced by Risk1.Form1.Form1_Load().
        {
            if (n.renk.Name == "ff604080")
            {
                return true;
            }
            else
            {
                return false;
            }
        }
static bool Risk1.Form1.Find19 (Nokta n) [inline, static, private]
Definition at line 2096 of file Form1.cs.
References Risk1.Nokta.renk.
Referenced by Risk1.Form1.Form1_Load().
        {
            if (n.renk.Name == "ffc06080")
            {
                return true;
            }
            else
            {
                return false;
            }
        }
static bool Risk1.Form1.Find2 (Nokta n) [inline, static, private]
Definition at line 1892 of file Form1.cs.
References Risk1.Nokta.renk.
Referenced by Risk1.Form1.Form1_Load().
        {
            if (n.renk.Name == "ffe04000")
            {
                return true;
            }
            else
            {
                return false;
            }
        }
static bool Risk1.Form1.Find20 (Nokta n) [inline, static, private]
Definition at line 2108 of file Form1.cs.
References Risk1.Nokta.renk.
Referenced by Risk1.Form1.Form1_Load().
        {
            if (n.renk.Name == "ff40c080")
            {
                return true;
            }
            else
            {
                return false;
            }
        }
static bool Risk1.Form1.Find21 (Nokta n) [inline, static, private]
Definition at line 2120 of file Form1.cs.
References Risk1.Nokta.renk.
Referenced by Risk1.Form1.Form1_Load().
        {
            if (n.renk.Name == "ffc0c080")
            {
                return true;
            }
            else
            {
                return false;
            }
        }
static bool Risk1.Form1.Find22 (Nokta n) [inline, static, private]
Definition at line 2132 of file Form1.cs.
References Risk1.Nokta.renk.
Referenced by Risk1.Form1.Form1_Load().
        {
            if (n.renk.Name == "ffc0a080")
            {
                return true;
            }
            else
            {
                return false;
            }
        }
static bool Risk1.Form1.Find23 (Nokta n) [inline, static, private]
Definition at line 2144 of file Form1.cs.
References Risk1.Nokta.renk.
Referenced by Risk1.Form1.Form1_Load().
        {
            if (n.renk.Name == "ff00a080")
            {
                return true;
            }
            else
            {
                return false;
            }
        }
static bool Risk1.Form1.Find24 (Nokta n) [inline, static, private]
Definition at line 2156 of file Form1.cs.
References Risk1.Nokta.renk.
Referenced by Risk1.Form1.Form1_Load().
        {
            if (n.renk.Name == "ffe0c080")
            {
                return true;
            }
            else
            {
                return false;
            }
        }
static bool Risk1.Form1.Find25 (Nokta n) [inline, static, private]
Definition at line 2168 of file Form1.cs.
References Risk1.Nokta.renk.
Referenced by Risk1.Form1.Form1_Load().
        {
            if (n.renk.Name == "ffa0c080")
            {
                return true;
            }
            else
            {
                return false;
            }
        }
static bool Risk1.Form1.Find26 (Nokta n) [inline, static, private]
Definition at line 2180 of file Form1.cs.
References Risk1.Nokta.renk.
Referenced by Risk1.Form1.Form1_Load().
        {
            if (n.renk.Name == "ffa0e080")
            {
                return true;
            }
            else
            {
                return false;
            }
        }
static bool Risk1.Form1.Find27 (Nokta n) [inline, static, private]
Definition at line 2192 of file Form1.cs.
References Risk1.Nokta.renk.
Referenced by Risk1.Form1.Form1_Load().
        {
            if (n.renk.Name == "ffc000c0")
            {
                return true;
            }
            else
            {
                return false;
            }
        }
static bool Risk1.Form1.Find28 (Nokta n) [inline, static, private]
Definition at line 2204 of file Form1.cs.
References Risk1.Nokta.renk.
Referenced by Risk1.Form1.Form1_Load().
        {
            if (n.renk.Name == "ff8020c0")
            {
                return true;
            }
            else
            {
                return false;
            }
        }
static bool Risk1.Form1.Find29 (Nokta n) [inline, static, private]
Definition at line 2216 of file Form1.cs.
References Risk1.Nokta.renk.
Referenced by Risk1.Form1.Form1_Load().
        {
            if (n.renk.Name == "ff0000c0")
            {
                return true;
            }
            else
            {
                return false;
            }
        }
static bool Risk1.Form1.Find3 (Nokta n) [inline, static, private]
Definition at line 1904 of file Form1.cs.
References Risk1.Nokta.renk.
Referenced by Risk1.Form1.Form1_Load().
        {
            if (n.renk.Name == "ffc0dcc0")
            {
                return true;
            }
            else
            {
                return false;
            }
        }
static bool Risk1.Form1.Find30 (Nokta n) [inline, static, private]
Definition at line 2228 of file Form1.cs.
References Risk1.Nokta.renk.
Referenced by Risk1.Form1.Form1_Load().
        {
            if (n.renk.Name == "ffe040c0")
            {
                return true;
            }
            else
            {
                return false;
            }
        }
static bool Risk1.Form1.Find31 (Nokta n) [inline, static, private]
Definition at line 2240 of file Form1.cs.
References Risk1.Nokta.renk.
Referenced by Risk1.Form1.Form1_Load().
        {
            if (n.renk.Name == "ffc0c0c0")
            {
                return true;
            }
            else
            {
                return false;
            }
        }
static bool Risk1.Form1.Find32 (Nokta n) [inline, static, private]
Definition at line 2252 of file Form1.cs.
References Risk1.Nokta.renk.
Referenced by Risk1.Form1.Form1_Load().
        {
            if (n.renk.Name == "ffa000c0")
            {
                return true;
            }
            else
            {
                return false;
            }
        }
static bool Risk1.Form1.Find33 (Nokta n) [inline, static, private]
Definition at line 2264 of file Form1.cs.
References Risk1.Nokta.renk.
Referenced by Risk1.Form1.Form1_Load().
        {
            if (n.renk.Name == "ffe06080")
            {
                return true;
            }
            else
            {
                return false;
            }
        }
static bool Risk1.Form1.Find34 (Nokta n) [inline, static, private]
Definition at line 2276 of file Form1.cs.
References Risk1.Nokta.renk.
Referenced by Risk1.Form1.Form1_Load().
        {
            if (n.renk.Name == "ff40c0c0")
            {
                return true;
            }
            else
            {
                return false;
            }
        }
static bool Risk1.Form1.Find35 (Nokta n) [inline, static, private]
Definition at line 2288 of file Form1.cs.
References Risk1.Nokta.renk.
Referenced by Risk1.Form1.Form1_Load().
        {
            if (n.renk.Name == "ffe080c0")
            {
                return true;
            }
            else
            {
                return false;
            }
        }
static bool Risk1.Form1.Find36 (Nokta n) [inline, static, private]
Definition at line 2300 of file Form1.cs.
References Risk1.Nokta.renk.
Referenced by Risk1.Form1.Form1_Load().
        {
            if (n.renk.Name == "ff40a0c0")
            {
                return true;
            }
            else
            {
                return false;
            }
        }
static bool Risk1.Form1.Find37 (Nokta n) [inline, static, private]
Definition at line 2312 of file Form1.cs.
References Risk1.Nokta.renk.
Referenced by Risk1.Form1.Form1_Load().
        {
            if (n.renk.Name == "ff80a0c0")
            {
                return true;
            }
            else
            {
                return false;
            }
        }
static bool Risk1.Form1.Find38 (Nokta n) [inline, static, private]
Definition at line 2324 of file Form1.cs.
References Risk1.Nokta.renk.
Referenced by Risk1.Form1.Form1_Load().
        {
            if (n.renk.Name == "ffe0a0c0")
            {
                return true;
            }
            else
            {
                return false;
            }
        }
static bool Risk1.Form1.Find39 (Nokta n) [inline, static, private]
Definition at line 2336 of file Form1.cs.
References Risk1.Nokta.renk.
Referenced by Risk1.Form1.Form1_Load().
        {
            if (n.renk.Name == "ff6000c0")
            {
                return true;
            }
            else
            {
                return false;
            }
        }
static bool Risk1.Form1.Find4 (Nokta n) [inline, static, private]
Definition at line 1916 of file Form1.cs.
References Risk1.Nokta.renk.
Referenced by Risk1.Form1.Form1_Load().
        {
            if (n.renk.Name == "ffc06000")
            {
                return true;
            }
            else
            {
                return false;
            }
        }
static bool Risk1.Form1.Find40 (Nokta n) [inline, static, private]
Definition at line 2348 of file Form1.cs.
References Risk1.Nokta.renk.
Referenced by Risk1.Form1.Form1_Load().
        {
            if (n.renk.Name == "ff0060c0")
            {
                return true;
            }
            else
            {
                return false;
            }
        }
static bool Risk1.Form1.Find41 (Nokta n) [inline, static, private]
Definition at line 2360 of file Form1.cs.
References Risk1.Nokta.renk.
Referenced by Risk1.Form1.Form1_Load().
        {
            if (n.renk.Name == "ffa6caf0")
            {
                return true;
            }
            else
            {
                return false;
            }
        }
static bool Risk1.Form1.Find42 (Nokta n) [inline, static, private]
Definition at line 2372 of file Form1.cs.
References Risk1.Nokta.renk.
Referenced by Risk1.Form1.Form1_Load().
        {
            if (n.renk.Name == "ffc060c0")
            {
                return true;
            }
            else
            {
                return false;
            }
        }
static bool Risk1.Form1.Find5 (Nokta n) [inline, static, private]
Definition at line 1928 of file Form1.cs.
References Risk1.Nokta.renk.
Referenced by Risk1.Form1.Form1_Load().
        {
            if (n.renk.Name == "ff604000")
            {
                return true;
            }
            else
            {
                return false;
            }
        }
static bool Risk1.Form1.Find6 (Nokta n) [inline, static, private]
Definition at line 1940 of file Form1.cs.
References Risk1.Nokta.renk.
Referenced by Risk1.Form1.Form1_Load().
        {
            if (n.renk.Name == "ffe06000")
            {
                return true;
            }
            else
            {
                return false;
            }
        }
static bool Risk1.Form1.Find7 (Nokta n) [inline, static, private]
Definition at line 1952 of file Form1.cs.
References Risk1.Nokta.renk.
Referenced by Risk1.Form1.Form1_Load().
        {
            if (n.renk.Name == "ff606000")
            {
                return true;
            }
            else
            {
                return false;
            }
        }
static bool Risk1.Form1.Find8 (Nokta n) [inline, static, private]
Definition at line 1964 of file Form1.cs.
References Risk1.Nokta.renk.
Referenced by Risk1.Form1.Form1_Load().
        {
            if (n.renk.Name == "ff00c000")
            {
                return true;
            }
            else
            {
                return false;
            }
        }
static bool Risk1.Form1.Find9 (Nokta n) [inline, static, private]
Definition at line 1976 of file Form1.cs.
References Risk1.Nokta.renk.
Referenced by Risk1.Form1.Form1_Load().
        {
            if (n.renk.Name == "ffc0e000")
            {
                return true;
            }
            else
            {
                return false;
            }
        }
static bool Risk1.Form1.FindDeniz (Nokta n) [inline, static, private]
Definition at line 2384 of file Form1.cs.
References Risk1.Nokta.renk.
Referenced by Risk1.Form1.Form1_Load().
        {
            if (n.renk.Name == "ff000080")
            {
                return true;
            }
            else
            {
                return false;
            }
        }
static bool Risk1.Form1.FindSinir (Nokta n) [inline, static, private]
Definition at line 2396 of file Form1.cs.
References Risk1.Nokta.renk.
Referenced by Risk1.Form1.Form1_Load().
        {
            if (n.renk.Name == "ff000000")
            {
                return true;
            }
            else
            {
                return false;
            }
        }
void Risk1.Form1.followUsOnTwitterToolStripMenuItem_Click (object sender, EventArgs e) [inline, private]
Definition at line 2875 of file Form1.cs.
        {
            System.Diagnostics.Process.Start("http://twitter.com/#!/RISKGAMEWAR");
        }
void Risk1.Form1.Form1_KeyDown (object sender, KeyEventArgs e) [inline, private]
Definition at line 2562 of file Form1.cs.
References Risk1.Form1.button2, Risk1.Form1.changeTurn(), Risk1.Form1.ilkTiklananBolge, and Risk1.Form1.state.
        {
            if (e.KeyCode==Keys.Space)
            {
                if (button2.Enabled)
                {
                    changeTurn();
                    ilkTiklananBolge = null;
                    state = 0;
                }
            }
        //    if ((e.Modifiers & Keys.Shift) == Keys.Shift)
        //    {
        //    }
        //    else
        //    {
        //        MessageBox.Show("Shift basl deil");
        //    }
        }
void Risk1.Form1.Form1_Load (object sender, EventArgs e) [inline, private]
Definition at line 1326 of file Form1.cs.
References Risk1.Form1.ai, Risk1.Form1.ai2, Risk1.Form1.ai3, Risk1.Form1.ai4, Risk1.Player.aiId, Risk1.Continent.bolgeler, Risk1.Form1.bolgeler, Risk1.Form1.changeDenizColor(), Risk1.Form1.changeSinirColor(), Risk1.Form1.deniz, Risk1.Form1.endGameToolStripMenuItem, Risk1.Form1.Find1(), Risk1.Form1.Find10(), Risk1.Form1.Find11(), Risk1.Form1.Find12(), Risk1.Form1.Find13(), Risk1.Form1.Find14(), Risk1.Form1.Find15(), Risk1.Form1.Find16(), Risk1.Form1.Find17(), Risk1.Form1.Find18(), Risk1.Form1.Find19(), Risk1.Form1.Find2(), Risk1.Form1.Find20(), Risk1.Form1.Find21(), Risk1.Form1.Find22(), Risk1.Form1.Find23(), Risk1.Form1.Find24(), Risk1.Form1.Find25(), Risk1.Form1.Find26(), Risk1.Form1.Find27(), Risk1.Form1.Find28(), Risk1.Form1.Find29(), Risk1.Form1.Find3(), Risk1.Form1.Find30(), Risk1.Form1.Find31(), Risk1.Form1.Find32(), Risk1.Form1.Find33(), Risk1.Form1.Find34(), Risk1.Form1.Find35(), Risk1.Form1.Find36(), Risk1.Form1.Find37(), Risk1.Form1.Find38(), Risk1.Form1.Find39(), Risk1.Form1.Find4(), Risk1.Form1.Find40(), Risk1.Form1.Find41(), Risk1.Form1.Find42(), Risk1.Form1.Find5(), Risk1.Form1.Find6(), Risk1.Form1.Find7(), Risk1.Form1.Find8(), Risk1.Form1.Find9(), Risk1.Form1.FindDeniz(), Risk1.Form1.FindSinir(), Risk1.Form1.ilkAskerSayisi, Risk1.Player.ilkAskerSayisi, Risk1.Bolge.index, Risk1.Player.isActive, Risk1.Player.isHuman, Risk1.Form1.kitalar, Risk1.Form1.label1, Risk1.Form1.label10, Risk1.Form1.label11, Risk1.Form1.label12, Risk1.Form1.label13, Risk1.Form1.label14, Risk1.Form1.label15, Risk1.Form1.label16, Risk1.Form1.label17, Risk1.Form1.label18, Risk1.Form1.label19, Risk1.Form1.label2, Risk1.Form1.label20, Risk1.Form1.label21, Risk1.Form1.label22, Risk1.Form1.label23, Risk1.Form1.label24, Risk1.Form1.label25, Risk1.Form1.label26, Risk1.Form1.label27, Risk1.Form1.label28, Risk1.Form1.label29, Risk1.Form1.label3, Risk1.Form1.label30, Risk1.Form1.label31, Risk1.Form1.label32, Risk1.Form1.label33, Risk1.Form1.label34, Risk1.Form1.label35, Risk1.Form1.label36, Risk1.Form1.label37, Risk1.Form1.label38, Risk1.Form1.label39, Risk1.Form1.label4, Risk1.Form1.label40, Risk1.Form1.label41, Risk1.Form1.label42, Risk1.Form1.label5, Risk1.Form1.label6, Risk1.Form1.label7, Risk1.Form1.label8, Risk1.Form1.label9, Risk1.Form1.labels, Risk1.Form1.listView1, Risk1.Bolge.noktalar, Risk1.Form1.noktalar, Risk1.Bolge.number, Risk1.Player.number, Risk1.Form1.pictureBox1, Risk1.Form1.players, Risk1.Nokta.point, Risk1.Nokta.renk, Risk1.Form1.showStatisticsToolStripMenuItem_Click(), Risk1.Form1.sinirlar, Risk1.Form1.timer1, and Risk1.Form1.yapayzekalar.
        {
            Loading loading = new Loading();
            loading.Show();
            endGameToolStripMenuItem.Enabled = false;
            listView1.Visible = false;
            pictureBox1.Enabled = false;
            //ncelikle her bir pixelin bilgisini
            //noktalar isimli listeye atyoruz.
            Bitmap bm = new Bitmap(pictureBox1.Image);
            for (int i = 0; i < 535; i++)
            {
                for (int j = 0; j < 776; j++)
                {
                    Color col = bm.GetPixel(j, i);
                    Nokta n = new Nokta();
                    n.point.X = j;
                    n.point.Y = i;
                    n.renk = col;
                    noktalar.Add(n);
                }
            }
            List<Nokta> b1 = noktalar.FindAll(Find1);
            List<Nokta> b2 = noktalar.FindAll(Find2);
            List<Nokta> b3 = noktalar.FindAll(Find3);
            List<Nokta> b4 = noktalar.FindAll(Find4);
            List<Nokta> b5 = noktalar.FindAll(Find5);
            List<Nokta> b6 = noktalar.FindAll(Find6);
            List<Nokta> b7 = noktalar.FindAll(Find7);
            List<Nokta> b8 = noktalar.FindAll(Find8);
            List<Nokta> b9 = noktalar.FindAll(Find9);
            List<Nokta> b10 = noktalar.FindAll(Find10);
            List<Nokta> b11 = noktalar.FindAll(Find11);
            List<Nokta> b12 = noktalar.FindAll(Find12);
            List<Nokta> b13 = noktalar.FindAll(Find13);
            List<Nokta> b14 = noktalar.FindAll(Find14);
            List<Nokta> b15 = noktalar.FindAll(Find15);
            List<Nokta> b16 = noktalar.FindAll(Find16);
            List<Nokta> b17 = noktalar.FindAll(Find17);
            List<Nokta> b18 = noktalar.FindAll(Find18);
            List<Nokta> b19 = noktalar.FindAll(Find19);
            List<Nokta> b20 = noktalar.FindAll(Find20);
            List<Nokta> b21 = noktalar.FindAll(Find21);
            List<Nokta> b22 = noktalar.FindAll(Find22);
            List<Nokta> b23 = noktalar.FindAll(Find23);
            List<Nokta> b24 = noktalar.FindAll(Find24);
            List<Nokta> b25 = noktalar.FindAll(Find25);
            List<Nokta> b26 = noktalar.FindAll(Find26);
            List<Nokta> b27 = noktalar.FindAll(Find27);
            List<Nokta> b28 = noktalar.FindAll(Find28);
            List<Nokta> b29 = noktalar.FindAll(Find29);
            List<Nokta> b30 = noktalar.FindAll(Find30);
            List<Nokta> b31 = noktalar.FindAll(Find31);
            List<Nokta> b32 = noktalar.FindAll(Find32);
            List<Nokta> b33 = noktalar.FindAll(Find33);
            List<Nokta> b34 = noktalar.FindAll(Find34);
            List<Nokta> b35 = noktalar.FindAll(Find35);
            List<Nokta> b36 = noktalar.FindAll(Find36);
            List<Nokta> b37 = noktalar.FindAll(Find37);
            List<Nokta> b38 = noktalar.FindAll(Find38);
            List<Nokta> b39 = noktalar.FindAll(Find39);
            List<Nokta> b40 = noktalar.FindAll(Find40);
            List<Nokta> b41 = noktalar.FindAll(Find41);
            List<Nokta> b42 = noktalar.FindAll(Find42);
            deniz=noktalar.FindAll(FindDeniz);
            sinirlar = noktalar.FindAll(FindSinir);
            Bolge tempBolge1 = new Bolge(b1, "Alaska");
            Bolge tempBolge2 = new Bolge(b2, "Northwest Territory");
            Bolge tempBolge3 = new Bolge(b3, "Greenland");
            Bolge tempBolge4 = new Bolge(b4, "Alberta");
            Bolge tempBolge5 = new Bolge(b5, "Ontario");
            Bolge tempBolge6 = new Bolge(b6, "Quebec");
            Bolge tempBolge7 = new Bolge(b7, "Western US");
            Bolge tempBolge8 = new Bolge(b8, "Estern US");
            Bolge tempBolge9 = new Bolge(b9, "Central America");
            Bolge tempBolge10 = new Bolge(b10, "Venezuela");
            Bolge tempBolge11 = new Bolge(b11, "Peru");
            Bolge tempBolge12 = new Bolge(b12, "Brazil");
            Bolge tempBolge13 = new Bolge(b13, "Argentina");
            Bolge tempBolge14 = new Bolge(b14, "North Africa");
            Bolge tempBolge15 = new Bolge(b15, "Egypt");
            Bolge tempBolge16 = new Bolge(b16, "East Africa");
            Bolge tempBolge17 = new Bolge(b17, "Congo");
            Bolge tempBolge18 = new Bolge(b18, "South Africa");
            Bolge tempBolge19 = new Bolge(b19, "Madagascar");
            Bolge tempBolge20 = new Bolge(b20, "Iceland");
            Bolge tempBolge21 = new Bolge(b21, "Scandinavia");
            Bolge tempBolge22 = new Bolge(b22, "Azerbaijan");
            Bolge tempBolge23 = new Bolge(b23, "Northern Europe");
            Bolge tempBolge24 = new Bolge(b24, "Great Britain");
            Bolge tempBolge25 = new Bolge(b25, "Western Europe");
            Bolge tempBolge26 = new Bolge(b26, "Southern Europe");
            Bolge tempBolge27 = new Bolge(b27, "Middle East");
            Bolge tempBolge28 = new Bolge(b28, "Yamal-Nemets");
            Bolge tempBolge29 = new Bolge(b29, "Kazakhstan");
            Bolge tempBolge30 = new Bolge(b30, "India");
            Bolge tempBolge31 = new Bolge(b31, "Siam");
            Bolge tempBolge32 = new Bolge(b32, "China");
            Bolge tempBolge33 = new Bolge(b33, "Mongolia");
            Bolge tempBolge34 = new Bolge(b34, "Taymyr");
            Bolge tempBolge35 = new Bolge(b35, "Yakut");
            Bolge tempBolge36 = new Bolge(b36, "Burgat");
            Bolge tempBolge37 = new Bolge(b37, "Koryak");
            Bolge tempBolge38 = new Bolge(b38, "Japan");
            Bolge tempBolge39 = new Bolge(b39, "Indonesia");
            Bolge tempBolge40 = new Bolge(b40, "Western Australia");
            Bolge tempBolge41 = new Bolge(b41, "Estern Australia");
            Bolge tempBolge42 = new Bolge(b42, "New Guinea");
            bolgeler.Add(tempBolge1);
            bolgeler.Add(tempBolge2);
            bolgeler.Add(tempBolge3);
            bolgeler.Add(tempBolge4);
            bolgeler.Add(tempBolge5);
            bolgeler.Add(tempBolge6);
            bolgeler.Add(tempBolge7);
            bolgeler.Add(tempBolge8);
            bolgeler.Add(tempBolge9);
            bolgeler.Add(tempBolge10);
            bolgeler.Add(tempBolge11);
            bolgeler.Add(tempBolge12);
            bolgeler.Add(tempBolge13);
            bolgeler.Add(tempBolge14);
            bolgeler.Add(tempBolge15);
            bolgeler.Add(tempBolge16);
            bolgeler.Add(tempBolge17);
            bolgeler.Add(tempBolge18);
            bolgeler.Add(tempBolge19);
            bolgeler.Add(tempBolge20);
            bolgeler.Add(tempBolge21);
            bolgeler.Add(tempBolge22);
            bolgeler.Add(tempBolge23);
            bolgeler.Add(tempBolge24);
            bolgeler.Add(tempBolge25);
            bolgeler.Add(tempBolge26);
            bolgeler.Add(tempBolge27);
            bolgeler.Add(tempBolge28);
            bolgeler.Add(tempBolge29);
            bolgeler.Add(tempBolge30);
            bolgeler.Add(tempBolge31);
            bolgeler.Add(tempBolge32);
            bolgeler.Add(tempBolge33);
            bolgeler.Add(tempBolge34);
            bolgeler.Add(tempBolge35);
            bolgeler.Add(tempBolge36);
            bolgeler.Add(tempBolge37);
            bolgeler.Add(tempBolge38);
            bolgeler.Add(tempBolge39);
            bolgeler.Add(tempBolge40);
            bolgeler.Add(tempBolge41);
            bolgeler.Add(tempBolge42);
            //Her Blgenin tek tek komular tantlacak
            bolgeler[0].komsular.Add(bolgeler[1]);
            bolgeler[0].komsular.Add(bolgeler[3]);
            bolgeler[0].komsular.Add(bolgeler[36]);
            bolgeler[1].komsular.Add(bolgeler[0]);
            bolgeler[1].komsular.Add(bolgeler[3]);
            bolgeler[1].komsular.Add(bolgeler[4]);
            bolgeler[1].komsular.Add(bolgeler[2]);
            bolgeler[2].komsular.Add(bolgeler[1]);
            bolgeler[2].komsular.Add(bolgeler[4]);
            bolgeler[2].komsular.Add(bolgeler[5]);
            bolgeler[2].komsular.Add(bolgeler[19]);
            bolgeler[3].komsular.Add(bolgeler[0]);
            bolgeler[3].komsular.Add(bolgeler[1]);
            bolgeler[3].komsular.Add(bolgeler[4]);
            bolgeler[3].komsular.Add(bolgeler[6]);
            bolgeler[4].komsular.Add(bolgeler[1]);
            bolgeler[4].komsular.Add(bolgeler[3]);
            bolgeler[4].komsular.Add(bolgeler[5]);
            bolgeler[4].komsular.Add(bolgeler[7]);
            bolgeler[4].komsular.Add(bolgeler[6]);
            bolgeler[4].komsular.Add(bolgeler[2]);
            bolgeler[5].komsular.Add(bolgeler[4]);
            bolgeler[5].komsular.Add(bolgeler[7]);
            bolgeler[5].komsular.Add(bolgeler[2]);
            bolgeler[6].komsular.Add(bolgeler[3]);
            bolgeler[6].komsular.Add(bolgeler[4]);
            bolgeler[6].komsular.Add(bolgeler[7]);
            bolgeler[6].komsular.Add(bolgeler[8]);
            bolgeler[7].komsular.Add(bolgeler[5]);
            bolgeler[7].komsular.Add(bolgeler[4]);
            bolgeler[7].komsular.Add(bolgeler[8]);
            bolgeler[7].komsular.Add(bolgeler[6]);
            bolgeler[8].komsular.Add(bolgeler[7]);
            bolgeler[8].komsular.Add(bolgeler[6]);
            bolgeler[8].komsular.Add(bolgeler[9]);
            bolgeler[9].komsular.Add(bolgeler[8]);
            bolgeler[9].komsular.Add(bolgeler[11]);
            bolgeler[9].komsular.Add(bolgeler[10]);
            bolgeler[10].komsular.Add(bolgeler[9]);
            bolgeler[10].komsular.Add(bolgeler[11]);
            bolgeler[10].komsular.Add(bolgeler[12]);
            bolgeler[11].komsular.Add(bolgeler[9]);
            bolgeler[11].komsular.Add(bolgeler[10]);
            bolgeler[11].komsular.Add(bolgeler[12]);
            bolgeler[11].komsular.Add(bolgeler[13]);
            bolgeler[12].komsular.Add(bolgeler[10]);
            bolgeler[12].komsular.Add(bolgeler[11]);
            bolgeler[13].komsular.Add(bolgeler[11]);
            bolgeler[13].komsular.Add(bolgeler[25]);
            bolgeler[13].komsular.Add(bolgeler[14]);
            bolgeler[13].komsular.Add(bolgeler[15]);
            bolgeler[13].komsular.Add(bolgeler[16]);
            bolgeler[13].komsular.Add(bolgeler[24]);
            bolgeler[14].komsular.Add(bolgeler[25]);
            bolgeler[14].komsular.Add(bolgeler[15]);
            bolgeler[14].komsular.Add(bolgeler[26]);
            bolgeler[14].komsular.Add(bolgeler[13]);
            bolgeler[15].komsular.Add(bolgeler[16]);
            bolgeler[15].komsular.Add(bolgeler[18]);
            bolgeler[15].komsular.Add(bolgeler[13]);
            bolgeler[15].komsular.Add(bolgeler[14]);
            bolgeler[15].komsular.Add(bolgeler[26]);
            bolgeler[15].komsular.Add(bolgeler[17]);
            bolgeler[16].komsular.Add(bolgeler[13]);
            bolgeler[16].komsular.Add(bolgeler[15]);
            bolgeler[16].komsular.Add(bolgeler[17]);
            bolgeler[17].komsular.Add(bolgeler[16]);
            bolgeler[17].komsular.Add(bolgeler[15]);
            bolgeler[17].komsular.Add(bolgeler[18]);
            bolgeler[18].komsular.Add(bolgeler[15]);
            bolgeler[18].komsular.Add(bolgeler[17]);
            bolgeler[19].komsular.Add(bolgeler[2]);
            bolgeler[19].komsular.Add(bolgeler[20]);
            bolgeler[19].komsular.Add(bolgeler[23]);
            bolgeler[20].komsular.Add(bolgeler[21]);
            bolgeler[20].komsular.Add(bolgeler[22]);
            bolgeler[20].komsular.Add(bolgeler[23]);
            bolgeler[20].komsular.Add(bolgeler[19]);
            bolgeler[21].komsular.Add(bolgeler[27]);
            bolgeler[21].komsular.Add(bolgeler[28]);
            bolgeler[21].komsular.Add(bolgeler[26]);
            bolgeler[21].komsular.Add(bolgeler[25]);
            bolgeler[21].komsular.Add(bolgeler[22]);
            bolgeler[21].komsular.Add(bolgeler[20]);
            bolgeler[22].komsular.Add(bolgeler[21]);
            bolgeler[22].komsular.Add(bolgeler[20]);
            bolgeler[22].komsular.Add(bolgeler[23]);
            bolgeler[22].komsular.Add(bolgeler[24]);
            bolgeler[22].komsular.Add(bolgeler[25]);
            bolgeler[23].komsular.Add(bolgeler[19]);
            bolgeler[23].komsular.Add(bolgeler[20]);
            bolgeler[23].komsular.Add(bolgeler[22]);
            bolgeler[23].komsular.Add(bolgeler[24]);
            bolgeler[24].komsular.Add(bolgeler[23]);
            bolgeler[24].komsular.Add(bolgeler[22]);
            bolgeler[24].komsular.Add(bolgeler[25]);
            bolgeler[24].komsular.Add(bolgeler[13]);
            bolgeler[25].komsular.Add(bolgeler[14]);
            bolgeler[25].komsular.Add(bolgeler[26]);
            bolgeler[25].komsular.Add(bolgeler[24]);
            bolgeler[25].komsular.Add(bolgeler[13]);
            bolgeler[25].komsular.Add(bolgeler[22]);
            bolgeler[25].komsular.Add(bolgeler[21]);
            bolgeler[26].komsular.Add(bolgeler[14]);
            bolgeler[26].komsular.Add(bolgeler[15]);
            bolgeler[26].komsular.Add(bolgeler[25]);
            bolgeler[26].komsular.Add(bolgeler[21]);
            bolgeler[26].komsular.Add(bolgeler[28]);
            bolgeler[26].komsular.Add(bolgeler[29]);
            bolgeler[27].komsular.Add(bolgeler[21]);
            bolgeler[27].komsular.Add(bolgeler[28]);
            bolgeler[27].komsular.Add(bolgeler[32]);
            bolgeler[27].komsular.Add(bolgeler[33]);
            bolgeler[28].komsular.Add(bolgeler[21]);
            bolgeler[28].komsular.Add(bolgeler[26]);
            bolgeler[28].komsular.Add(bolgeler[29]);
            bolgeler[28].komsular.Add(bolgeler[31]);
            bolgeler[28].komsular.Add(bolgeler[27]);
            bolgeler[29].komsular.Add(bolgeler[26]);
            bolgeler[29].komsular.Add(bolgeler[28]);
            bolgeler[29].komsular.Add(bolgeler[31]);
            bolgeler[29].komsular.Add(bolgeler[30]);
            bolgeler[30].komsular.Add(bolgeler[29]);
            bolgeler[30].komsular.Add(bolgeler[31]);
            bolgeler[30].komsular.Add(bolgeler[38]);
            bolgeler[31].komsular.Add(bolgeler[30]);
            bolgeler[31].komsular.Add(bolgeler[29]);
            bolgeler[31].komsular.Add(bolgeler[28]);
            bolgeler[31].komsular.Add(bolgeler[32]);
            bolgeler[32].komsular.Add(bolgeler[37]);
            bolgeler[32].komsular.Add(bolgeler[31]);
            bolgeler[32].komsular.Add(bolgeler[27]);
            bolgeler[32].komsular.Add(bolgeler[33]);
            bolgeler[32].komsular.Add(bolgeler[35]);
            bolgeler[32].komsular.Add(bolgeler[36]);
            bolgeler[33].komsular.Add(bolgeler[27]);
            bolgeler[33].komsular.Add(bolgeler[32]);
            bolgeler[33].komsular.Add(bolgeler[35]);
            bolgeler[33].komsular.Add(bolgeler[34]);
            bolgeler[34].komsular.Add(bolgeler[33]);
            bolgeler[34].komsular.Add(bolgeler[35]);
            bolgeler[34].komsular.Add(bolgeler[36]);
            bolgeler[35].komsular.Add(bolgeler[33]);
            bolgeler[35].komsular.Add(bolgeler[34]);
            bolgeler[35].komsular.Add(bolgeler[36]);
            bolgeler[35].komsular.Add(bolgeler[32]);
            bolgeler[36].komsular.Add(bolgeler[37]);
            bolgeler[36].komsular.Add(bolgeler[32]);
            bolgeler[36].komsular.Add(bolgeler[35]);
            bolgeler[36].komsular.Add(bolgeler[34]);
            bolgeler[36].komsular.Add(bolgeler[0]);
            bolgeler[37].komsular.Add(bolgeler[32]);
            bolgeler[37].komsular.Add(bolgeler[36]);
            bolgeler[38].komsular.Add(bolgeler[30]);
            bolgeler[38].komsular.Add(bolgeler[41]);
            bolgeler[38].komsular.Add(bolgeler[39]);
            bolgeler[39].komsular.Add(bolgeler[40]);
            bolgeler[39].komsular.Add(bolgeler[41]);
            bolgeler[39].komsular.Add(bolgeler[38]);
            bolgeler[40].komsular.Add(bolgeler[39]);
            bolgeler[40].komsular.Add(bolgeler[41]);
            bolgeler[41].komsular.Add(bolgeler[38]);
            bolgeler[41].komsular.Add(bolgeler[39]);
            bolgeler[41].komsular.Add(bolgeler[40]);
            int k=1;
            foreach (Bolge bb in bolgeler)
            {
                bb.number = k;
                bb.index = k - 1;
                k++;
            }
            for (int i = 0; i <= 9; i++)
            {
                Player p = new Player("Player"+(i+1).ToString(),false,false);
                p.number = i + 1;
                players.Add(p);
            }
            players[0].color = Color.Blue;
            players[1].color = Color.Red;
            players[2].color = Color.Yellow;
            players[3].color = Color.Lime;
            players[4].color = Color.Turquoise;
            players[5].color = Color.Green;
            players[6].color = Color.HotPink;
            players[7].color = Color.DarkOrange;
            players[8].color = Color.Purple;
            players[9].color = Color.DarkRed;
            Bitmap bmr = new Bitmap(pictureBox1.Image);
            foreach (Bolge b in bolgeler)
            {
                foreach (Nokta n in b.noktalar)
                {
                    bmr.SetPixel(n.point.X, n.point.Y, Color.AliceBlue);
                }
            }
            foreach (Player pl in players)
            {
                pl.ilkAskerSayisi = ilkAskerSayisi;
                pl.isHuman = false;
                pl.aiId = 1;
                pl.isActive = true;
            }
            players[0].isHuman = true;
            players[1].aiId = 2;
            players[2].aiId = 3;
            players[3].aiId = 4;
            pictureBox1.Image = bmr;
            Continent c1 = new Continent("N. America", 5);
            c1.bolgeler.Add(bolgeler[0]);
            c1.bolgeler.Add(bolgeler[1]);
            c1.bolgeler.Add(bolgeler[2]);
            c1.bolgeler.Add(bolgeler[3]);
            c1.bolgeler.Add(bolgeler[4]);
            c1.bolgeler.Add(bolgeler[5]);
            c1.bolgeler.Add(bolgeler[6]);
            c1.bolgeler.Add(bolgeler[7]);
            c1.bolgeler.Add(bolgeler[8]);
            Continent c2 = new Continent("S. America", 2);
            c2.bolgeler.Add(bolgeler[9]);
            c2.bolgeler.Add(bolgeler[10]);
            c2.bolgeler.Add(bolgeler[11]);
            c2.bolgeler.Add(bolgeler[12]);
            Continent c3 = new Continent("Africa",3);
            c3.bolgeler.Add(bolgeler[13]);
            c3.bolgeler.Add(bolgeler[14]);
            c3.bolgeler.Add(bolgeler[15]);
            c3.bolgeler.Add(bolgeler[16]);
            c3.bolgeler.Add(bolgeler[17]);
            c3.bolgeler.Add(bolgeler[18]);
            Continent c4 = new Continent("Asia",7);
            c4.bolgeler.Add(bolgeler[26]);
            c4.bolgeler.Add(bolgeler[27]);
            c4.bolgeler.Add(bolgeler[28]);
            c4.bolgeler.Add(bolgeler[29]);
            c4.bolgeler.Add(bolgeler[30]);
            c4.bolgeler.Add(bolgeler[31]);
            c4.bolgeler.Add(bolgeler[32]);
            c4.bolgeler.Add(bolgeler[33]);
            c4.bolgeler.Add(bolgeler[34]);
            c4.bolgeler.Add(bolgeler[35]);
            c4.bolgeler.Add(bolgeler[36]);
            c4.bolgeler.Add(bolgeler[37]);
            Continent c5 = new Continent("Europe",5);
            c5.bolgeler.Add(bolgeler[19]);
            c5.bolgeler.Add(bolgeler[20]);
            c5.bolgeler.Add(bolgeler[21]);
            c5.bolgeler.Add(bolgeler[22]);
            c5.bolgeler.Add(bolgeler[23]);
            c5.bolgeler.Add(bolgeler[24]);
            c5.bolgeler.Add(bolgeler[25]);
            Continent c6 = new Continent("Australia",2);
            c6.bolgeler.Add(bolgeler[38]);
            c6.bolgeler.Add(bolgeler[39]);
            c6.bolgeler.Add(bolgeler[40]);
            c6.bolgeler.Add(bolgeler[41]);
            kitalar.Add(c1);
            kitalar.Add(c2);
            kitalar.Add(c3);
            kitalar.Add(c4);
            kitalar.Add(c5);
            kitalar.Add(c6);
            this.Height = 602;
            //this.Width = 793;
            //hideStatisticsToolStripMenuItem.Enabled = false;
            showStatisticsToolStripMenuItem_Click(sender, e);
            //Labelleri hepsini tek bir listeye atacam
            labels.Add(label1);
            labels.Add(label2);
            labels.Add(label3);
            labels.Add(label4);
            labels.Add(label5);
            labels.Add(label6);
            labels.Add(label7);
            labels.Add(label8);
            labels.Add(label9);
            labels.Add(label10);
            labels.Add(label11);
            labels.Add(label12);
            labels.Add(label13);
            labels.Add(label14);
            labels.Add(label15);
            labels.Add(label16);
            labels.Add(label17);
            labels.Add(label18);
            labels.Add(label19);
            labels.Add(label20);
            labels.Add(label21);
            labels.Add(label22);
            labels.Add(label23);
            labels.Add(label24);
            labels.Add(label25);
            labels.Add(label26);
            labels.Add(label27);
            labels.Add(label28);
            labels.Add(label29);
            labels.Add(label30);
            labels.Add(label31);
            labels.Add(label32);
            labels.Add(label33);
            labels.Add(label34);
            labels.Add(label35);
            labels.Add(label36);
            labels.Add(label37);
            labels.Add(label38);
            labels.Add(label39);
            labels.Add(label40);
            labels.Add(label41);
            labels.Add(label42);
            foreach (Label l in labels)
            {
                l.Visible = false;
                l.Enabled = false;
            }
            yapayzekalar.Add(ai);
            yapayzekalar.Add(ai2);
            yapayzekalar.Add(ai3);
            yapayzekalar.Add(ai4);
            changeDenizColor(Color.SlateGray);
            changeSinirColor(Color.Black);
            listView1.Visible = false;
            timer1.Start();
            timer1.Interval = 10;
            loading.Close();
        }
void Risk1.Form1.ganimetBolgseiniBildir () [inline]
Definition at line 1106 of file Form1.cs.
References Risk1.Form1.ganimetBolgesi, Risk1.Form1.label, Risk1.Form1.label1, Risk1.Form1.label10, Risk1.Form1.label11, Risk1.Form1.label12, Risk1.Form1.label13, Risk1.Form1.label14, Risk1.Form1.label15, Risk1.Form1.label16, Risk1.Form1.label17, Risk1.Form1.label18, Risk1.Form1.label19, Risk1.Form1.label2, Risk1.Form1.label20, Risk1.Form1.label21, Risk1.Form1.label22, Risk1.Form1.label23, Risk1.Form1.label24, Risk1.Form1.label25, Risk1.Form1.label26, Risk1.Form1.label27, Risk1.Form1.label28, Risk1.Form1.label29, Risk1.Form1.label3, Risk1.Form1.label30, Risk1.Form1.label31, Risk1.Form1.label32, Risk1.Form1.label33, Risk1.Form1.label34, Risk1.Form1.label35, Risk1.Form1.label36, Risk1.Form1.label37, Risk1.Form1.label38, Risk1.Form1.label39, Risk1.Form1.label4, Risk1.Form1.label40, Risk1.Form1.label41, Risk1.Form1.label42, Risk1.Form1.label5, Risk1.Form1.label6, Risk1.Form1.label7, Risk1.Form1.label8, and Risk1.Form1.label9.
Referenced by Risk1.Form1.changeTurn(), and Risk1.Form1.pictureBox1_Click().
        {
            int a=ganimetBolgesi+1;
            Color b = Color.Gold;
            Color f = Color.DimGray;
            if (a == 1)
            {
                label1.BackColor = b;
                label = label1;
            }
            else if (a == 2)
            {
                label2.BackColor = b;
                label = label2;
            }
            else if (a == 3)
            {
                label3.BackColor = b;
                label = label3;
            }
            else if (a == 4)
            {
                label4.BackColor = b;
                label = label4;
            }
            else if (a == 5)
            {
                label5.BackColor = b;
                label = label5;
            }
            else if (a == 6)
            {
                label6.BackColor = b;
                label = label6;
            }
            else if (a == 7)
            {
                label7.BackColor = b;
                label = label7;
            }
            else if (a == 8)
            {
                label8.BackColor = b;
                label = label8;
            }
            else if (a == 9)
            {
                label9.BackColor = b;
                label = label9;
            }
            else if (a == 10)
            {
                label10.BackColor = b;
                label = label10;
            }
            else if (a == 11)
            {
                label11.BackColor = b;
                label = label11;
            }
            else if (a == 12)
            {
                label12.BackColor = b;
                label = label12;
            }
            else if (a == 13)
            {
                label13.BackColor = b;
                label = label13;
            }
            else if (a == 14)
            {
                label14.BackColor = b;
                label = label14;
            }
            else if (a == 15)
            {
                label15.BackColor = b;
                label = label15;
            }
            else if (a == 16)
            {
                label16.BackColor = b;
                label = label16;
            }
            else if (a == 17)
            {
                label17.BackColor = b;
                label = label17;
            }
            else if (a == 18)
            {
                label18.BackColor = b;
                label = label18;
            }
            else if (a == 19)
            {
                label19.BackColor = b;
                label = label19;
            }
            else if (a == 20)
            {
                label20.BackColor = b;
                label = label20;
            }
            else if (a == 21)
            {
                label21.BackColor = b;
                label = label21;
            }
            else if (a == 22)
            {
                label22.BackColor = b;
                label = label22;
            }
            else if (a == 23)
            {
                label23.BackColor = b;
                label = label23;
            }
            else if (a == 24)
            {
                label24.BackColor = b;
                label = label24;
            }
            else if (a == 25)
            {
                label25.BackColor = b;
                label = label25;
            }
            else if (a == 26)
            {
                label26.BackColor = b;
                label = label26;
            }
            else if (a == 27)
            {
                label27.BackColor = b;
                label = label27;
            }
            else if (a == 28)
            {
                label28.BackColor = b;
                label = label28;
            }
            else if (a == 29)
            {
                label29.BackColor = b;
                label = label29;
            }
            else if (a == 30)
            {
                label30.BackColor = b;
                label = label30;
            }
            else if (a == 31)
            {
                label31.BackColor = b;
                label = label31;
            }
            else if (a == 32)
            {
                label32.BackColor = b;
                label = label32;
            }
            else if (a == 33)
            {
                label33.BackColor = b;
                label = label33;
            }
            else if (a == 34)
            {
                label34.BackColor = b;
                label = label34;
            }
            else if (a == 35)
            {
                label35.BackColor = b;
                label = label35;
            }
            else if (a == 36)
            {
                label36.BackColor = b;
                label = label36;
            }
            else if (a == 37)
            {
                label37.BackColor = b;
                label = label37;
            }
            else if (a == 38)
            {
                label38.BackColor = b;
                label = label38;
            }
            else if (a == 39)
            {
                label39.BackColor = b;
                label = label39;
            }
            else if (a == 40)
            {
                label40.BackColor = b;
                label = label40;
            }
            else if (a == 41)
            {
                label41.BackColor = b;
                label = label41;
            }
            else if (a == 42)
            {
                label42.BackColor = b;
                label = label42;
            }
            label.ForeColor = Color.Black;
        }
GameData Risk1.Form1.getGameData () [inline]
Definition at line 76 of file Form1.cs.
References Risk1.Form1.gameData, and Risk1.Form1.updateGameData().
Referenced by Risk1.Form1.changeTurn(), and Risk1.SaldiriEkrani.warDoORDieForAi().
        {
            updateGameData();
            return gameData;
        }
int Risk1.Form1.getNextTurn () [inline]
Definition at line 1024 of file Form1.cs.
References Risk1.Form1.players, and Risk1.Form1.turn.
Referenced by Risk1.Form1.changeTurn(), and Risk1.Form1.newGameToolStripMenuItem_Click().
        {
            if ((turn + 1) < players.Count)
            {
                return turn+1;
            }
            else
            {
                return 0;
            }
        }
bool Risk1.Form1.guneyAmerika (List< Bolge > sahipOlduguBolgeler) [inline, private]
Definition at line 962 of file Form1.cs.
References Risk1.Form1.bolgeler, and Risk1.Form1.kitalar.
Referenced by Risk1.Form1.hangiKitalaraSahip(), and Risk1.Form1.kitaKazanci().
        {
            foreach (Bolge b in kitalar[1].bolgeler)
            {
                if (!sahipOlduguBolgeler.Contains(b))
                {
                    return false;
                }
            }
            return true;
        }
void Risk1.Form1.hangiKitalaraSahip () [inline, private]
Definition at line 918 of file Form1.cs.
References Risk1.Form1.afrika(), Risk1.Form1.asya(), Risk1.Form1.avrupa(), Risk1.Form1.avustralya(), Risk1.Player.bolgeler, Risk1.Form1.guneyAmerika(), Risk1.Player.kitalar, Risk1.Form1.kuzeyAmerika(), and Risk1.Form1.players.
Referenced by Risk1.Form1.changeStatistics().
        {
            foreach (Player p in players)
            {
                p.kitalar = "";
                if (kuzeyAmerika(p.bolgeler))
                {
                    p.kitalar += "NA ";
                }
                if (guneyAmerika(p.bolgeler))
                {
                    p.kitalar += "SA ";
                }
                if (afrika(p.bolgeler))
                {
                    p.kitalar += "AF ";
                }
                if (asya(p.bolgeler))
                {
                    p.kitalar += "AS ";
                }
                if (avrupa(p.bolgeler))
                {
                    p.kitalar += "EU ";
                }
                if (avustralya(p.bolgeler))
                {
                    p.kitalar += "AU ";
                }
            }
        }
void Risk1.Form1.hideStatistics () [inline]
Definition at line 572 of file Form1.cs.
References Risk1.Form1.hideStatisticsToolStripMenuItem, Risk1.Form1.listView1, and Risk1.Form1.showStatisticsToolStripMenuItem.
        {
            this.Width = 793;
            hideStatisticsToolStripMenuItem.Enabled = false;
            showStatisticsToolStripMenuItem.Enabled = true;
            listView1.Enabled = false;
            listView1.Visible = false;
        }
void Risk1.Form1.hideStatisticsToolStripMenuItem_Click (object sender, EventArgs e) [inline, private]
Definition at line 2623 of file Form1.cs.
References Risk1.Form1.hideStatisticsToolStripMenuItem, Risk1.Form1.listView1, and Risk1.Form1.showStatisticsToolStripMenuItem.
        {
            this.Width = 793;
            hideStatisticsToolStripMenuItem.Enabled = false;
            showStatisticsToolStripMenuItem.Enabled = true;
            listView1.Enabled = false;
            listView1.Visible = false;
        }
void Risk1.Form1.InitializeComponent () [inline, private]
Required method for Designer support - do not modify the contents of this method with the code editor.
Definition at line 29 of file Form1.Designer.cs.
Referenced by Risk1.Form1.Form1().
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Form1));
            this.panel1 = new System.Windows.Forms.Panel();
            this.button2 = new System.Windows.Forms.Button();
            this.txtInfo = new System.Windows.Forms.TextBox();
            this.txtPlayer = new System.Windows.Forms.TextBox();
            this.label1 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.label5 = new System.Windows.Forms.Label();
            this.label6 = new System.Windows.Forms.Label();
            this.label7 = new System.Windows.Forms.Label();
            this.label8 = new System.Windows.Forms.Label();
            this.label9 = new System.Windows.Forms.Label();
            this.label10 = new System.Windows.Forms.Label();
            this.label11 = new System.Windows.Forms.Label();
            this.label12 = new System.Windows.Forms.Label();
            this.label13 = new System.Windows.Forms.Label();
            this.label14 = new System.Windows.Forms.Label();
            this.label15 = new System.Windows.Forms.Label();
            this.label16 = new System.Windows.Forms.Label();
            this.label17 = new System.Windows.Forms.Label();
            this.label18 = new System.Windows.Forms.Label();
            this.label19 = new System.Windows.Forms.Label();
            this.label20 = new System.Windows.Forms.Label();
            this.label21 = new System.Windows.Forms.Label();
            this.label22 = new System.Windows.Forms.Label();
            this.label23 = new System.Windows.Forms.Label();
            this.label24 = new System.Windows.Forms.Label();
            this.label25 = new System.Windows.Forms.Label();
            this.label26 = new System.Windows.Forms.Label();
            this.label27 = new System.Windows.Forms.Label();
            this.label28 = new System.Windows.Forms.Label();
            this.label29 = new System.Windows.Forms.Label();
            this.label30 = new System.Windows.Forms.Label();
            this.label31 = new System.Windows.Forms.Label();
            this.label32 = new System.Windows.Forms.Label();
            this.label33 = new System.Windows.Forms.Label();
            this.label34 = new System.Windows.Forms.Label();
            this.label35 = new System.Windows.Forms.Label();
            this.label36 = new System.Windows.Forms.Label();
            this.label37 = new System.Windows.Forms.Label();
            this.label38 = new System.Windows.Forms.Label();
            this.label39 = new System.Windows.Forms.Label();
            this.label40 = new System.Windows.Forms.Label();
            this.label41 = new System.Windows.Forms.Label();
            this.label42 = new System.Windows.Forms.Label();
            this.gameToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.newGameToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.endGameToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.exitToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.optionsToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.rulesToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.changeStyleToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.statisticsToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.showStatisticsToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.hideStatisticsToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.showHistoryToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.helpToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.aboutToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.webSiteToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.facebookPageToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.followUsOnTwitterToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.menuStrip1 = new System.Windows.Forms.MenuStrip();
            this.listView1 = new System.Windows.Forms.ListView();
            this.player = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.territories = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.armies = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.continents = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.pictureBox3 = new System.Windows.Forms.PictureBox();
            this.pictureBox2 = new System.Windows.Forms.PictureBox();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.timer1 = new System.Windows.Forms.Timer(this.components);
            this.pictureBox4 = new System.Windows.Forms.PictureBox();
            this.panel1.SuspendLayout();
            this.menuStrip1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox3)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox4)).BeginInit();
            this.SuspendLayout();
            //
            // panel1
            //
            this.panel1.BackColor = System.Drawing.Color.Black;
            this.panel1.Controls.Add(this.button2);
            this.panel1.Controls.Add(this.txtInfo);
            this.panel1.Controls.Add(this.txtPlayer);
            this.panel1.Location = new System.Drawing.Point(6, 567);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(776, 49);
            this.panel1.TabIndex = 6;
            //
            // button2
            //
            this.button2.BackColor = System.Drawing.Color.GreenYellow;
            this.button2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("button2.BackgroundImage")));
            this.button2.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.button2.Enabled = false;
            this.button2.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.button2.Location = new System.Drawing.Point(709, 9);
            this.button2.Name = "button2";
            this.button2.Size = new System.Drawing.Size(66, 27);
            this.button2.TabIndex = 2;
            this.button2.UseVisualStyleBackColor = false;
            this.button2.Click += new System.EventHandler(this.button2_Click);
            //
            // txtInfo
            //
            this.txtInfo.BackColor = System.Drawing.Color.Gainsboro;
            this.txtInfo.Font = new System.Drawing.Font("Arial", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.txtInfo.ForeColor = System.Drawing.Color.DarkSlateGray;
            this.txtInfo.Location = new System.Drawing.Point(150, 10);
            this.txtInfo.Name = "txtInfo";
            this.txtInfo.ReadOnly = true;
            this.txtInfo.Size = new System.Drawing.Size(567, 25);
            this.txtInfo.TabIndex = 1;
            this.txtInfo.Text = "Deneme";
            //
            // txtPlayer
            //
            this.txtPlayer.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtPlayer.Font = new System.Drawing.Font("Arial", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtPlayer.Location = new System.Drawing.Point(0, 10);
            this.txtPlayer.Name = "txtPlayer";
            this.txtPlayer.ReadOnly = true;
            this.txtPlayer.Size = new System.Drawing.Size(148, 25);
            this.txtPlayer.TabIndex = 0;
            this.txtPlayer.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            //
            // label1
            //
            this.label1.AutoSize = true;
            this.label1.BackColor = System.Drawing.Color.Black;
            this.label1.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.label1.ForeColor = System.Drawing.Color.White;
            this.label1.Location = new System.Drawing.Point(31, 111);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(14, 13);
            this.label1.TabIndex = 8;
            this.label1.Text = "0";
            this.label1.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.label1.Click += new System.EventHandler(this.label1_Click);
            //
            // label2
            //
            this.label2.AutoSize = true;
            this.label2.BackColor = System.Drawing.Color.Black;
            this.label2.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.label2.ForeColor = System.Drawing.Color.White;
            this.label2.Location = new System.Drawing.Point(94, 116);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(14, 13);
            this.label2.TabIndex = 9;
            this.label2.Text = "0";
            this.label2.Click += new System.EventHandler(this.label2_Click);
            //
            // label3
            //
            this.label3.AutoSize = true;
            this.label3.BackColor = System.Drawing.Color.Black;
            this.label3.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.label3.ForeColor = System.Drawing.Color.White;
            this.label3.Location = new System.Drawing.Point(271, 66);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(14, 13);
            this.label3.TabIndex = 10;
            this.label3.Text = "0";
            this.label3.Click += new System.EventHandler(this.label3_Click);
            //
            // label4
            //
            this.label4.AutoSize = true;
            this.label4.BackColor = System.Drawing.Color.Black;
            this.label4.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.label4.ForeColor = System.Drawing.Color.White;
            this.label4.Location = new System.Drawing.Point(97, 170);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(14, 13);
            this.label4.TabIndex = 11;
            this.label4.Text = "0";
            this.label4.Click += new System.EventHandler(this.label4_Click);
            //
            // label5
            //
            this.label5.AutoSize = true;
            this.label5.BackColor = System.Drawing.Color.Black;
            this.label5.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.label5.ForeColor = System.Drawing.Color.White;
            this.label5.Location = new System.Drawing.Point(149, 177);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(14, 13);
            this.label5.TabIndex = 12;
            this.label5.Text = "0";
            this.label5.Click += new System.EventHandler(this.label5_Click);
            //
            // label6
            //
            this.label6.AutoSize = true;
            this.label6.BackColor = System.Drawing.Color.Black;
            this.label6.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.label6.ForeColor = System.Drawing.Color.White;
            this.label6.Location = new System.Drawing.Point(206, 173);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(14, 13);
            this.label6.TabIndex = 13;
            this.label6.Text = "0";
            this.label6.Click += new System.EventHandler(this.label6_Click);
            //
            // label7
            //
            this.label7.AutoSize = true;
            this.label7.BackColor = System.Drawing.Color.Black;
            this.label7.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.label7.ForeColor = System.Drawing.Color.White;
            this.label7.Location = new System.Drawing.Point(118, 229);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(14, 13);
            this.label7.TabIndex = 14;
            this.label7.Text = "0";
            this.label7.Click += new System.EventHandler(this.label7_Click);
            //
            // label8
            //
            this.label8.AutoSize = true;
            this.label8.BackColor = System.Drawing.Color.Black;
            this.label8.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.label8.ForeColor = System.Drawing.Color.White;
            this.label8.Location = new System.Drawing.Point(168, 248);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(14, 13);
            this.label8.TabIndex = 15;
            this.label8.Text = "0";
            this.label8.Click += new System.EventHandler(this.label8_Click);
            //
            // label9
            //
            this.label9.AutoSize = true;
            this.label9.BackColor = System.Drawing.Color.Black;
            this.label9.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.label9.ForeColor = System.Drawing.Color.White;
            this.label9.Location = new System.Drawing.Point(140, 297);
            this.label9.Name = "label9";
            this.label9.Size = new System.Drawing.Size(14, 13);
            this.label9.TabIndex = 16;
            this.label9.Text = "0";
            this.label9.Click += new System.EventHandler(this.label9_Click);
            //
            // label10
            //
            this.label10.AutoSize = true;
            this.label10.BackColor = System.Drawing.Color.Black;
            this.label10.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.label10.ForeColor = System.Drawing.Color.White;
            this.label10.Location = new System.Drawing.Point(209, 343);
            this.label10.Name = "label10";
            this.label10.Size = new System.Drawing.Size(14, 13);
            this.label10.TabIndex = 17;
            this.label10.Text = "0";
            this.label10.Click += new System.EventHandler(this.label10_Click);
            //
            // label11
            //
            this.label11.AutoSize = true;
            this.label11.BackColor = System.Drawing.Color.Black;
            this.label11.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.label11.ForeColor = System.Drawing.Color.White;
            this.label11.Location = new System.Drawing.Point(212, 400);
            this.label11.Name = "label11";
            this.label11.Size = new System.Drawing.Size(14, 13);
            this.label11.TabIndex = 18;
            this.label11.Text = "0";
            this.label11.Click += new System.EventHandler(this.label11_Click);
            //
            // label12
            //
            this.label12.AutoSize = true;
            this.label12.BackColor = System.Drawing.Color.Black;
            this.label12.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.label12.ForeColor = System.Drawing.Color.White;
            this.label12.Location = new System.Drawing.Point(247, 385);
            this.label12.Name = "label12";
            this.label12.Size = new System.Drawing.Size(14, 13);
            this.label12.TabIndex = 19;
            this.label12.Text = "0";
            this.label12.Click += new System.EventHandler(this.label12_Click);
            //
            // label13
            //
            this.label13.AutoSize = true;
            this.label13.BackColor = System.Drawing.Color.Black;
            this.label13.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.label13.ForeColor = System.Drawing.Color.White;
            this.label13.Location = new System.Drawing.Point(215, 465);
            this.label13.Name = "label13";
            this.label13.Size = new System.Drawing.Size(14, 13);
            this.label13.TabIndex = 20;
            this.label13.Text = "0";
            this.label13.Click += new System.EventHandler(this.label13_Click);
            //
            // label14
            //
            this.label14.AutoSize = true;
            this.label14.BackColor = System.Drawing.Color.Black;
            this.label14.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.label14.ForeColor = System.Drawing.Color.White;
            this.label14.Location = new System.Drawing.Point(360, 301);
            this.label14.Name = "label14";
            this.label14.Size = new System.Drawing.Size(14, 13);
            this.label14.TabIndex = 21;
            this.label14.Text = "0";
            this.label14.Click += new System.EventHandler(this.label14_Click);
            //
            // label15
            //
            this.label15.AutoSize = true;
            this.label15.BackColor = System.Drawing.Color.Black;
            this.label15.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.label15.ForeColor = System.Drawing.Color.White;
            this.label15.Location = new System.Drawing.Point(403, 275);
            this.label15.Name = "label15";
            this.label15.Size = new System.Drawing.Size(14, 13);
            this.label15.TabIndex = 22;
            this.label15.Text = "0";
            this.label15.Click += new System.EventHandler(this.label15_Click);
            //
            // label16
            //
            this.label16.AutoSize = true;
            this.label16.BackColor = System.Drawing.Color.Black;
            this.label16.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.label16.ForeColor = System.Drawing.Color.White;
            this.label16.Location = new System.Drawing.Point(440, 338);
            this.label16.Name = "label16";
            this.label16.Size = new System.Drawing.Size(14, 13);
            this.label16.TabIndex = 23;
            this.label16.Text = "0";
            this.label16.Click += new System.EventHandler(this.label16_Click);
            //
            // label17
            //
            this.label17.AutoSize = true;
            this.label17.BackColor = System.Drawing.Color.Black;
            this.label17.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.label17.ForeColor = System.Drawing.Color.White;
            this.label17.Location = new System.Drawing.Point(411, 365);
            this.label17.Name = "label17";
            this.label17.Size = new System.Drawing.Size(14, 13);
            this.label17.TabIndex = 24;
            this.label17.Text = "0";
            this.label17.Click += new System.EventHandler(this.label17_Click);
            //
            // label18
            //
            this.label18.AutoSize = true;
            this.label18.BackColor = System.Drawing.Color.Black;
            this.label18.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.label18.ForeColor = System.Drawing.Color.White;
            this.label18.Location = new System.Drawing.Point(414, 426);
            this.label18.Name = "label18";
            this.label18.Size = new System.Drawing.Size(14, 13);
            this.label18.TabIndex = 25;
            this.label18.Text = "0";
            this.label18.Click += new System.EventHandler(this.label18_Click);
            //
            // label19
            //
            this.label19.AutoSize = true;
            this.label19.BackColor = System.Drawing.Color.Black;
            this.label19.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.label19.ForeColor = System.Drawing.Color.White;
            this.label19.Location = new System.Drawing.Point(474, 417);
            this.label19.Name = "label19";
            this.label19.Size = new System.Drawing.Size(14, 13);
            this.label19.TabIndex = 26;
            this.label19.Text = "0";
            this.label19.Click += new System.EventHandler(this.label19_Click);
            //
            // label20
            //
            this.label20.AutoSize = true;
            this.label20.BackColor = System.Drawing.Color.Black;
            this.label20.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.label20.ForeColor = System.Drawing.Color.White;
            this.label20.Location = new System.Drawing.Point(301, 121);
            this.label20.Name = "label20";
            this.label20.Size = new System.Drawing.Size(14, 13);
            this.label20.TabIndex = 27;
            this.label20.Text = "0";
            this.label20.Click += new System.EventHandler(this.label20_Click);
            //
            // label21
            //
            this.label21.AutoSize = true;
            this.label21.BackColor = System.Drawing.Color.Black;
            this.label21.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.label21.ForeColor = System.Drawing.Color.White;
            this.label21.Location = new System.Drawing.Point(395, 116);
            this.label21.Name = "label21";
            this.label21.Size = new System.Drawing.Size(14, 13);
            this.label21.TabIndex = 28;
            this.label21.Text = "0";
            this.label21.Click += new System.EventHandler(this.label21_Click);
            //
            // label22
            //
            this.label22.AutoSize = true;
            this.label22.BackColor = System.Drawing.Color.Black;
            this.label22.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.label22.ForeColor = System.Drawing.Color.White;
            this.label22.Location = new System.Drawing.Point(446, 166);
            this.label22.Name = "label22";
            this.label22.Size = new System.Drawing.Size(14, 13);
            this.label22.TabIndex = 29;
            this.label22.Text = "0";
            this.label22.Click += new System.EventHandler(this.label22_Click);
            //
            // label23
            //
            this.label23.AutoSize = true;
            this.label23.BackColor = System.Drawing.Color.Black;
            this.label23.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.label23.ForeColor = System.Drawing.Color.White;
            this.label23.Location = new System.Drawing.Point(383, 186);
            this.label23.Name = "label23";
            this.label23.Size = new System.Drawing.Size(14, 13);
            this.label23.TabIndex = 30;
            this.label23.Text = "0";
            this.label23.Click += new System.EventHandler(this.label23_Click);
            //
            // label24
            //
            this.label24.AutoSize = true;
            this.label24.BackColor = System.Drawing.Color.Black;
            this.label24.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.label24.ForeColor = System.Drawing.Color.White;
            this.label24.Location = new System.Drawing.Point(331, 177);
            this.label24.Name = "label24";
            this.label24.Size = new System.Drawing.Size(14, 13);
            this.label24.TabIndex = 31;
            this.label24.Text = "0";
            this.label24.Click += new System.EventHandler(this.label24_Click);
            //
            // label25
            //
            this.label25.AutoSize = true;
            this.label25.BackColor = System.Drawing.Color.Black;
            this.label25.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.label25.ForeColor = System.Drawing.Color.White;
            this.label25.Location = new System.Drawing.Point(349, 233);
            this.label25.Name = "label25";
            this.label25.Size = new System.Drawing.Size(14, 13);
            this.label25.TabIndex = 32;
            this.label25.Text = "0";
            this.label25.Click += new System.EventHandler(this.label25_Click);
            //
            // label26
            //
            this.label26.AutoSize = true;
            this.label26.BackColor = System.Drawing.Color.Black;
            this.label26.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.label26.ForeColor = System.Drawing.Color.White;
            this.label26.Location = new System.Drawing.Point(406, 220);
            this.label26.Name = "label26";
            this.label26.Size = new System.Drawing.Size(14, 13);
            this.label26.TabIndex = 33;
            this.label26.Text = "0";
            this.label26.Click += new System.EventHandler(this.label26_Click);
            //
            // label27
            //
            this.label27.AutoSize = true;
            this.label27.BackColor = System.Drawing.Color.Black;
            this.label27.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.label27.ForeColor = System.Drawing.Color.White;
            this.label27.Location = new System.Drawing.Point(454, 261);
            this.label27.Name = "label27";
            this.label27.Size = new System.Drawing.Size(14, 13);
            this.label27.TabIndex = 34;
            this.label27.Text = "0";
            this.label27.Click += new System.EventHandler(this.label27_Click);
            //
            // label28
            //
            this.label28.AutoSize = true;
            this.label28.BackColor = System.Drawing.Color.Black;
            this.label28.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.label28.ForeColor = System.Drawing.Color.White;
            this.label28.Location = new System.Drawing.Point(520, 146);
            this.label28.Name = "label28";
            this.label28.Size = new System.Drawing.Size(14, 13);
            this.label28.TabIndex = 35;
            this.label28.Text = "0";
            this.label28.Click += new System.EventHandler(this.label28_Click);
            //
            // label29
            //
            this.label29.AutoSize = true;
            this.label29.BackColor = System.Drawing.Color.Black;
            this.label29.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.label29.ForeColor = System.Drawing.Color.White;
            this.label29.Location = new System.Drawing.Point(504, 218);
            this.label29.Name = "label29";
            this.label29.Size = new System.Drawing.Size(14, 13);
            this.label29.TabIndex = 36;
            this.label29.Text = "0";
            this.label29.Click += new System.EventHandler(this.label29_Click);
            //
            // label30
            //
            this.label30.AutoSize = true;
            this.label30.BackColor = System.Drawing.Color.Black;
            this.label30.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.label30.ForeColor = System.Drawing.Color.White;
            this.label30.Location = new System.Drawing.Point(527, 288);
            this.label30.Name = "label30";
            this.label30.Size = new System.Drawing.Size(14, 13);
            this.label30.TabIndex = 37;
            this.label30.Text = "0";
            this.label30.Click += new System.EventHandler(this.label30_Click);
            //
            // label31
            //
            this.label31.AutoSize = true;
            this.label31.BackColor = System.Drawing.Color.Black;
            this.label31.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.label31.ForeColor = System.Drawing.Color.White;
            this.label31.Location = new System.Drawing.Point(580, 309);
            this.label31.Name = "label31";
            this.label31.Size = new System.Drawing.Size(14, 13);
            this.label31.TabIndex = 38;
            this.label31.Text = "0";
            this.label31.Click += new System.EventHandler(this.label31_Click);
            //
            // label32
            //
            this.label32.AutoSize = true;
            this.label32.BackColor = System.Drawing.Color.Black;
            this.label32.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.label32.ForeColor = System.Drawing.Color.White;
            this.label32.Location = new System.Drawing.Point(576, 255);
            this.label32.Name = "label32";
            this.label32.Size = new System.Drawing.Size(14, 13);
            this.label32.TabIndex = 39;
            this.label32.Text = "0";
            this.label32.Click += new System.EventHandler(this.label32_Click);
            //
            // label33
            //
            this.label33.AutoSize = true;
            this.label33.BackColor = System.Drawing.Color.Black;
            this.label33.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.label33.ForeColor = System.Drawing.Color.White;
            this.label33.Location = new System.Drawing.Point(607, 215);
            this.label33.Name = "label33";
            this.label33.Size = new System.Drawing.Size(14, 13);
            this.label33.TabIndex = 40;
            this.label33.Text = "0";
            this.label33.Click += new System.EventHandler(this.label33_Click);
            //
            // label34
            //
            this.label34.AutoSize = true;
            this.label34.BackColor = System.Drawing.Color.Black;
            this.label34.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.label34.ForeColor = System.Drawing.Color.White;
            this.label34.Location = new System.Drawing.Point(566, 108);
            this.label34.Name = "label34";
            this.label34.Size = new System.Drawing.Size(14, 13);
            this.label34.TabIndex = 41;
            this.label34.Text = "0";
            this.label34.Click += new System.EventHandler(this.label34_Click);
            //
            // label35
            //
            this.label35.AutoSize = true;
            this.label35.BackColor = System.Drawing.Color.Black;
            this.label35.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.label35.ForeColor = System.Drawing.Color.White;
            this.label35.Location = new System.Drawing.Point(634, 107);
            this.label35.Name = "label35";
            this.label35.Size = new System.Drawing.Size(14, 13);
            this.label35.TabIndex = 42;
            this.label35.Text = "0";
            this.label35.Click += new System.EventHandler(this.label35_Click);
            //
            // label36
            //
            this.label36.AutoSize = true;
            this.label36.BackColor = System.Drawing.Color.Black;
            this.label36.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.label36.ForeColor = System.Drawing.Color.White;
            this.label36.Location = new System.Drawing.Point(604, 169);
            this.label36.Name = "label36";
            this.label36.Size = new System.Drawing.Size(14, 13);
            this.label36.TabIndex = 43;
            this.label36.Text = "0";
            this.label36.Click += new System.EventHandler(this.label36_Click);
            //
            // label37
            //
            this.label37.AutoSize = true;
            this.label37.BackColor = System.Drawing.Color.Black;
            this.label37.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.label37.ForeColor = System.Drawing.Color.White;
            this.label37.Location = new System.Drawing.Point(724, 117);
            this.label37.Name = "label37";
            this.label37.Size = new System.Drawing.Size(14, 13);
            this.label37.TabIndex = 44;
            this.label37.Text = "0";
            this.label37.Click += new System.EventHandler(this.label37_Click);
            //
            // label38
            //
            this.label38.AutoSize = true;
            this.label38.BackColor = System.Drawing.Color.Black;
            this.label38.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.label38.ForeColor = System.Drawing.Color.White;
            this.label38.Location = new System.Drawing.Point(668, 234);
            this.label38.Name = "label38";
            this.label38.Size = new System.Drawing.Size(14, 13);
            this.label38.TabIndex = 45;
            this.label38.Text = "0";
            this.label38.Click += new System.EventHandler(this.label38_Click);
            //
            // label39
            //
            this.label39.AutoSize = true;
            this.label39.BackColor = System.Drawing.Color.Black;
            this.label39.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.label39.ForeColor = System.Drawing.Color.White;
            this.label39.Location = new System.Drawing.Point(595, 367);
            this.label39.Name = "label39";
            this.label39.Size = new System.Drawing.Size(14, 13);
            this.label39.TabIndex = 46;
            this.label39.Text = "0";
            this.label39.Click += new System.EventHandler(this.label39_Click);
            //
            // label40
            //
            this.label40.AutoSize = true;
            this.label40.BackColor = System.Drawing.Color.Black;
            this.label40.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.label40.ForeColor = System.Drawing.Color.White;
            this.label40.Location = new System.Drawing.Point(626, 425);
            this.label40.Name = "label40";
            this.label40.Size = new System.Drawing.Size(14, 13);
            this.label40.TabIndex = 47;
            this.label40.Text = "0";
            this.label40.Click += new System.EventHandler(this.label40_Click);
            //
            // label41
            //
            this.label41.AutoSize = true;
            this.label41.BackColor = System.Drawing.Color.Black;
            this.label41.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.label41.ForeColor = System.Drawing.Color.White;
            this.label41.Location = new System.Drawing.Point(669, 436);
            this.label41.Name = "label41";
            this.label41.Size = new System.Drawing.Size(14, 13);
            this.label41.TabIndex = 48;
            this.label41.Text = "0";
            this.label41.Click += new System.EventHandler(this.label41_Click);
            //
            // label42
            //
            this.label42.AutoSize = true;
            this.label42.BackColor = System.Drawing.Color.Black;
            this.label42.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.label42.ForeColor = System.Drawing.Color.White;
            this.label42.Location = new System.Drawing.Point(676, 366);
            this.label42.Name = "label42";
            this.label42.Size = new System.Drawing.Size(14, 13);
            this.label42.TabIndex = 49;
            this.label42.Text = "0";
            this.label42.Click += new System.EventHandler(this.label42_Click);
            //
            // gameToolStripMenuItem
            //
            this.gameToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.newGameToolStripMenuItem,
            this.endGameToolStripMenuItem,
            this.exitToolStripMenuItem});
            this.gameToolStripMenuItem.Name = "gameToolStripMenuItem";
            this.gameToolStripMenuItem.Size = new System.Drawing.Size(56, 20);
            this.gameToolStripMenuItem.Text = "Game";
            //
            // newGameToolStripMenuItem
            //
            this.newGameToolStripMenuItem.Name = "newGameToolStripMenuItem";
            this.newGameToolStripMenuItem.Size = new System.Drawing.Size(142, 22);
            this.newGameToolStripMenuItem.Text = "New Game";
            this.newGameToolStripMenuItem.Click += new System.EventHandler(this.newGameToolStripMenuItem_Click);
            //
            // endGameToolStripMenuItem
            //
            this.endGameToolStripMenuItem.Name = "endGameToolStripMenuItem";
            this.endGameToolStripMenuItem.Size = new System.Drawing.Size(142, 22);
            this.endGameToolStripMenuItem.Text = "End Game";
            this.endGameToolStripMenuItem.Click += new System.EventHandler(this.endGameToolStripMenuItem_Click);
            //
            // exitToolStripMenuItem
            //
            this.exitToolStripMenuItem.Name = "exitToolStripMenuItem";
            this.exitToolStripMenuItem.Size = new System.Drawing.Size(142, 22);
            this.exitToolStripMenuItem.Text = "Exit";
            this.exitToolStripMenuItem.Click += new System.EventHandler(this.exitToolStripMenuItem_Click);
            //
            // optionsToolStripMenuItem
            //
            this.optionsToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.rulesToolStripMenuItem,
            this.changeStyleToolStripMenuItem});
            this.optionsToolStripMenuItem.Name = "optionsToolStripMenuItem";
            this.optionsToolStripMenuItem.Size = new System.Drawing.Size(68, 20);
            this.optionsToolStripMenuItem.Text = "Options";
            //
            // rulesToolStripMenuItem
            //
            this.rulesToolStripMenuItem.Name = "rulesToolStripMenuItem";
            this.rulesToolStripMenuItem.Size = new System.Drawing.Size(159, 22);
            this.rulesToolStripMenuItem.Text = "Rules";
            this.rulesToolStripMenuItem.Click += new System.EventHandler(this.rulesToolStripMenuItem_Click);
            //
            // changeStyleToolStripMenuItem
            //
            this.changeStyleToolStripMenuItem.Name = "changeStyleToolStripMenuItem";
            this.changeStyleToolStripMenuItem.Size = new System.Drawing.Size(159, 22);
            this.changeStyleToolStripMenuItem.Text = "Change Style";
            this.changeStyleToolStripMenuItem.Click += new System.EventHandler(this.changeStyleToolStripMenuItem_Click);
            //
            // statisticsToolStripMenuItem
            //
            this.statisticsToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.showStatisticsToolStripMenuItem,
            this.hideStatisticsToolStripMenuItem,
            this.showHistoryToolStripMenuItem});
            this.statisticsToolStripMenuItem.Name = "statisticsToolStripMenuItem";
            this.statisticsToolStripMenuItem.Size = new System.Drawing.Size(79, 20);
            this.statisticsToolStripMenuItem.Text = "Statistics";
            //
            // showStatisticsToolStripMenuItem
            //
            this.showStatisticsToolStripMenuItem.Name = "showStatisticsToolStripMenuItem";
            this.showStatisticsToolStripMenuItem.Size = new System.Drawing.Size(172, 22);
            this.showStatisticsToolStripMenuItem.Text = "Show Statistics";
            this.showStatisticsToolStripMenuItem.Click += new System.EventHandler(this.showStatisticsToolStripMenuItem_Click);
            //
            // hideStatisticsToolStripMenuItem
            //
            this.hideStatisticsToolStripMenuItem.Name = "hideStatisticsToolStripMenuItem";
            this.hideStatisticsToolStripMenuItem.Size = new System.Drawing.Size(172, 22);
            this.hideStatisticsToolStripMenuItem.Text = "Hide Statistics";
            this.hideStatisticsToolStripMenuItem.Click += new System.EventHandler(this.hideStatisticsToolStripMenuItem_Click);
            //
            // showHistoryToolStripMenuItem
            //
            this.showHistoryToolStripMenuItem.Enabled = false;
            this.showHistoryToolStripMenuItem.Name = "showHistoryToolStripMenuItem";
            this.showHistoryToolStripMenuItem.Size = new System.Drawing.Size(172, 22);
            this.showHistoryToolStripMenuItem.Text = "Show History";
            this.showHistoryToolStripMenuItem.Click += new System.EventHandler(this.showHistoryToolStripMenuItem_Click);
            //
            // helpToolStripMenuItem
            //
            this.helpToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.aboutToolStripMenuItem,
            this.webSiteToolStripMenuItem,
            this.facebookPageToolStripMenuItem,
            this.followUsOnTwitterToolStripMenuItem});
            this.helpToolStripMenuItem.Name = "helpToolStripMenuItem";
            this.helpToolStripMenuItem.Size = new System.Drawing.Size(48, 20);
            this.helpToolStripMenuItem.Text = "Help";
            //
            // aboutToolStripMenuItem
            //
            this.aboutToolStripMenuItem.Name = "aboutToolStripMenuItem";
            this.aboutToolStripMenuItem.Size = new System.Drawing.Size(205, 22);
            this.aboutToolStripMenuItem.Text = "About";
            this.aboutToolStripMenuItem.Click += new System.EventHandler(this.aboutToolStripMenuItem_Click);
            //
            // webSiteToolStripMenuItem
            //
            this.webSiteToolStripMenuItem.Name = "webSiteToolStripMenuItem";
            this.webSiteToolStripMenuItem.Size = new System.Drawing.Size(205, 22);
            this.webSiteToolStripMenuItem.Text = "Web Site";
            this.webSiteToolStripMenuItem.Click += new System.EventHandler(this.webSiteToolStripMenuItem_Click);
            //
            // facebookPageToolStripMenuItem
            //
            this.facebookPageToolStripMenuItem.Name = "facebookPageToolStripMenuItem";
            this.facebookPageToolStripMenuItem.Size = new System.Drawing.Size(205, 22);
            this.facebookPageToolStripMenuItem.Text = "Facebook Page";
            this.facebookPageToolStripMenuItem.Click += new System.EventHandler(this.facebookPageToolStripMenuItem_Click);
            //
            // followUsOnTwitterToolStripMenuItem
            //
            this.followUsOnTwitterToolStripMenuItem.Name = "followUsOnTwitterToolStripMenuItem";
            this.followUsOnTwitterToolStripMenuItem.Size = new System.Drawing.Size(205, 22);
            this.followUsOnTwitterToolStripMenuItem.Text = "Follow us on Twitter";
            this.followUsOnTwitterToolStripMenuItem.Click += new System.EventHandler(this.followUsOnTwitterToolStripMenuItem_Click);
            //
            // menuStrip1
            //
            this.menuStrip1.BackColor = System.Drawing.Color.CadetBlue;
            this.menuStrip1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("menuStrip1.BackgroundImage")));
            this.menuStrip1.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.menuStrip1.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.gameToolStripMenuItem,
            this.optionsToolStripMenuItem,
            this.statisticsToolStripMenuItem,
            this.helpToolStripMenuItem});
            this.menuStrip1.Location = new System.Drawing.Point(0, 0);
            this.menuStrip1.Name = "menuStrip1";
            this.menuStrip1.RenderMode = System.Windows.Forms.ToolStripRenderMode.Professional;
            this.menuStrip1.Size = new System.Drawing.Size(1047, 24);
            this.menuStrip1.TabIndex = 50;
            this.menuStrip1.Text = "menuStrip1";
            //
            // listView1
            //
            this.listView1.BackColor = System.Drawing.Color.SlateGray;
            this.listView1.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.listView1.Columns.AddRange(new System.Windows.Forms.ColumnHeader[] {
            this.player,
            this.territories,
            this.armies,
            this.continents});
            this.listView1.GridLines = true;
            this.listView1.Location = new System.Drawing.Point(788, 361);
            this.listView1.Name = "listView1";
            this.listView1.Size = new System.Drawing.Size(241, 195);
            this.listView1.TabIndex = 0;
            this.listView1.UseCompatibleStateImageBehavior = false;
            this.listView1.View = System.Windows.Forms.View.Details;
            //
            // player
            //
            this.player.Text = "Player";
            this.player.Width = 78;
            //
            // territories
            //
            this.territories.Text = "Territories";
            this.territories.Width = 53;
            //
            // armies
            //
            this.armies.Text = "Armies";
            this.armies.Width = 44;
            //
            // continents
            //
            this.continents.Text = "Continents";
            this.continents.Width = 65;
            //
            // pictureBox3
            //
            this.pictureBox3.BackColor = System.Drawing.Color.Transparent;
            this.pictureBox3.Cursor = System.Windows.Forms.Cursors.Hand;
            this.pictureBox3.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox3.Image")));
            this.pictureBox3.Location = new System.Drawing.Point(999, 573);
            this.pictureBox3.Name = "pictureBox3";
            this.pictureBox3.Size = new System.Drawing.Size(36, 35);
            this.pictureBox3.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.pictureBox3.TabIndex = 52;
            this.pictureBox3.TabStop = false;
            this.pictureBox3.Click += new System.EventHandler(this.pictureBox3_Click);
            //
            // pictureBox2
            //
            this.pictureBox2.BackColor = System.Drawing.Color.Transparent;
            this.pictureBox2.Cursor = System.Windows.Forms.Cursors.Hand;
            this.pictureBox2.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox2.Image")));
            this.pictureBox2.Location = new System.Drawing.Point(947, 573);
            this.pictureBox2.Name = "pictureBox2";
            this.pictureBox2.Size = new System.Drawing.Size(37, 35);
            this.pictureBox2.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.pictureBox2.TabIndex = 51;
            this.pictureBox2.TabStop = false;
            this.pictureBox2.Click += new System.EventHandler(this.pictureBox2_Click);
            //
            // pictureBox1
            //
            this.pictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox1.Image")));
            this.pictureBox1.Location = new System.Drawing.Point(6, 31);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(776, 535);
            this.pictureBox1.TabIndex = 0;
            this.pictureBox1.TabStop = false;
            this.pictureBox1.Click += new System.EventHandler(this.pictureBox1_Click);
            this.pictureBox1.MouseMove += new System.Windows.Forms.MouseEventHandler(this.pictureBox1_MouseMove);
            //
            // timer1
            //
            this.timer1.Tick += new System.EventHandler(this.timer1_Tick);
            //
            // pictureBox4
            //
            this.pictureBox4.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.pictureBox4.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox4.Image")));
            this.pictureBox4.Location = new System.Drawing.Point(780, 31);
            this.pictureBox4.Name = "pictureBox4";
            this.pictureBox4.Size = new System.Drawing.Size(260, 535);
            this.pictureBox4.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.pictureBox4.TabIndex = 53;
            this.pictureBox4.TabStop = false;
            //
            // Form1
            //
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.Black;
            this.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.ClientSize = new System.Drawing.Size(1047, 615);
            this.Controls.Add(this.pictureBox3);
            this.Controls.Add(this.pictureBox2);
            this.Controls.Add(this.listView1);
            this.Controls.Add(this.pictureBox4);
            this.Controls.Add(this.label42);
            this.Controls.Add(this.label41);
            this.Controls.Add(this.label40);
            this.Controls.Add(this.label39);
            this.Controls.Add(this.label38);
            this.Controls.Add(this.label37);
            this.Controls.Add(this.label36);
            this.Controls.Add(this.label35);
            this.Controls.Add(this.label34);
            this.Controls.Add(this.label33);
            this.Controls.Add(this.label32);
            this.Controls.Add(this.label31);
            this.Controls.Add(this.label30);
            this.Controls.Add(this.label29);
            this.Controls.Add(this.label28);
            this.Controls.Add(this.label27);
            this.Controls.Add(this.label26);
            this.Controls.Add(this.label25);
            this.Controls.Add(this.label24);
            this.Controls.Add(this.label23);
            this.Controls.Add(this.label22);
            this.Controls.Add(this.label21);
            this.Controls.Add(this.label20);
            this.Controls.Add(this.label19);
            this.Controls.Add(this.label18);
            this.Controls.Add(this.label17);
            this.Controls.Add(this.label16);
            this.Controls.Add(this.label15);
            this.Controls.Add(this.label14);
            this.Controls.Add(this.label13);
            this.Controls.Add(this.label12);
            this.Controls.Add(this.label11);
            this.Controls.Add(this.label10);
            this.Controls.Add(this.label9);
            this.Controls.Add(this.label8);
            this.Controls.Add(this.label7);
            this.Controls.Add(this.label6);
            this.Controls.Add(this.label5);
            this.Controls.Add(this.label4);
            this.Controls.Add(this.label3);
            this.Controls.Add(this.label2);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.panel1);
            this.Controls.Add(this.pictureBox1);
            this.Controls.Add(this.menuStrip1);
            this.DoubleBuffered = true;
            this.ForeColor = System.Drawing.Color.White;
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.MainMenuStrip = this.menuStrip1;
            this.MaximizeBox = false;
            this.Name = "Form1";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Absolute Risk";
            this.Load += new System.EventHandler(this.Form1_Load);
            this.KeyDown += new System.Windows.Forms.KeyEventHandler(this.Form1_KeyDown);
            this.panel1.ResumeLayout(false);
            this.panel1.PerformLayout();
            this.menuStrip1.ResumeLayout(false);
            this.menuStrip1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox3)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox4)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();
        }
int Risk1.Form1.kitaKazanci (Player p) [inline, private]
Definition at line 853 of file Form1.cs.
References Risk1.Form1.afrika(), Risk1.Form1.asya(), Risk1.Form1.avrupa(), Risk1.Form1.avustralya(), Risk1.Form1.bolgeler, Risk1.Player.bolgeler, Risk1.Player.buTurnBirisiniOldurduMu, Risk1.Player.buTurnKacKisiOldurdu, Risk1.Form1.ganimetBolgesi, Risk1.Form1.ganimetKazanci, Risk1.Player.getNumberOfTerritories(), Risk1.Form1.guneyAmerika(), Risk1.Player.kacKisiOldurdu, Risk1.Form1.kitalar, Risk1.Player.kitalar, and Risk1.Form1.kuzeyAmerika().
Referenced by Risk1.Form1.changeTurn().
        {
            p.kitalar = "";
            int kazanc=0;
            if (kuzeyAmerika(p.bolgeler))
            {
                kazanc += kitalar[0].getirisi;
                p.kitalar += "NA ";
            }
            if (guneyAmerika(p.bolgeler))
            {
                kazanc += kitalar[1].getirisi;
                p.kitalar += "SA ";
            }
            if (afrika(p.bolgeler))
            {
                kazanc += kitalar[2].getirisi;
                p.kitalar += "AF ";
            }
            if (asya(p.bolgeler))
            {
                kazanc += kitalar[3].getirisi;
                p.kitalar += "AS ";
            }
            if (avrupa(p.bolgeler))
            {
                kazanc += kitalar[4].getirisi;
                p.kitalar += "EU ";
            }
            if (avustralya(p.bolgeler))
            {
                kazanc += kitalar[5].getirisi;
                p.kitalar += "AU ";
            }
            if (p.bolgeler.Contains(bolgeler[ganimetBolgesi]))
            {
                kazanc += ganimetKazanci;
            }
            if (p.buTurnBirisiniOldurduMu)
            {
                kazanc += 10*p.buTurnKacKisiOldurdu;
                if (p.kacKisiOldurdu == 1)
                {
                    //MessageBox.Show(p.name + " won extra " + (p.buTurnKacKisiOldurdu*10).ToString() + " armies because he sent off a player");
                }
                else
                {
                    //MessageBox.Show(p.name + " won extra " + (p.buTurnKacKisiOldurdu*10).ToString() + " armies because he sent off players");
                }
                p.buTurnBirisiniOldurduMu = false;
                p.buTurnKacKisiOldurdu = 0;
            }
            //bolge saysn 3 e blp en yakn int e yuvarladmzda bulunan say 3 ten ne kadar bykse o kadar eksatra kazan
            decimal a = p.getNumberOfTerritories();
            int aa =(int)Math.Round(a / 3);
            if (aa > 3)
            {
                kazanc += aa - 3;
            }
            return kazanc;
        }
bool Risk1.Form1.kuzeyAmerika (List< Bolge > sahipOlduguBolgeler) [inline, private]
Definition at line 950 of file Form1.cs.
References Risk1.Form1.bolgeler, and Risk1.Form1.kitalar.
Referenced by Risk1.Form1.hangiKitalaraSahip(), and Risk1.Form1.kitaKazanci().
        {
            foreach (Bolge b in kitalar[0].bolgeler)
            {
                if (!sahipOlduguBolgeler.Contains(b))
                {
                    return false;
                }
            }
            return true;
        }
void Risk1.Form1.label10_Click (object sender, EventArgs e) [inline, private]
Definition at line 2698 of file Form1.cs.
References Risk1.Form1.pictureBox1_Click().
        {
            this.pictureBox1_Click(sender, e);
        }
void Risk1.Form1.label11_Click (object sender, EventArgs e) [inline, private]
Definition at line 2703 of file Form1.cs.
References Risk1.Form1.pictureBox1_Click().
        {
            this.pictureBox1_Click(sender, e);
        }
void Risk1.Form1.label12_Click (object sender, EventArgs e) [inline, private]
Definition at line 2708 of file Form1.cs.
References Risk1.Form1.pictureBox1_Click().
        {
            this.pictureBox1_Click(sender, e);
        }
void Risk1.Form1.label13_Click (object sender, EventArgs e) [inline, private]
Definition at line 2713 of file Form1.cs.
References Risk1.Form1.pictureBox1_Click().
        {
            this.pictureBox1_Click(sender, e);
        }
void Risk1.Form1.label14_Click (object sender, EventArgs e) [inline, private]
Definition at line 2718 of file Form1.cs.
References Risk1.Form1.pictureBox1_Click().
        {
            this.pictureBox1_Click(sender, e);
        }
void Risk1.Form1.label15_Click (object sender, EventArgs e) [inline, private]
Definition at line 2723 of file Form1.cs.
References Risk1.Form1.pictureBox1_Click().
        {
            this.pictureBox1_Click(sender, e);
        }
void Risk1.Form1.label16_Click (object sender, EventArgs e) [inline, private]
Definition at line 2728 of file Form1.cs.
References Risk1.Form1.pictureBox1_Click().
        {
            this.pictureBox1_Click(sender, e);
        }
void Risk1.Form1.label17_Click (object sender, EventArgs e) [inline, private]
Definition at line 2733 of file Form1.cs.
References Risk1.Form1.pictureBox1_Click().
        {
            this.pictureBox1_Click(sender, e);
        }
void Risk1.Form1.label18_Click (object sender, EventArgs e) [inline, private]
Definition at line 2738 of file Form1.cs.
References Risk1.Form1.pictureBox1_Click().
        {
            this.pictureBox1_Click(sender, e);
        }
void Risk1.Form1.label19_Click (object sender, EventArgs e) [inline, private]
Definition at line 2743 of file Form1.cs.
References Risk1.Form1.pictureBox1_Click().
        {
            this.pictureBox1_Click(sender, e);
        }
void Risk1.Form1.label1_Click (object sender, EventArgs e) [inline, private]
Definition at line 2653 of file Form1.cs.
References Risk1.Form1.pictureBox1_Click().
        {
            this.pictureBox1_Click(sender, e);
        }
void Risk1.Form1.label20_Click (object sender, EventArgs e) [inline, private]
Definition at line 2748 of file Form1.cs.
References Risk1.Form1.pictureBox1_Click().
        {
            this.pictureBox1_Click(sender, e);
        }
void Risk1.Form1.label21_Click (object sender, EventArgs e) [inline, private]
Definition at line 2753 of file Form1.cs.
References Risk1.Form1.pictureBox1_Click().
        {
            this.pictureBox1_Click(sender, e);
        }
void Risk1.Form1.label22_Click (object sender, EventArgs e) [inline, private]
Definition at line 2758 of file Form1.cs.
References Risk1.Form1.pictureBox1_Click().
        {
            this.pictureBox1_Click(sender, e);
        }
void Risk1.Form1.label23_Click (object sender, EventArgs e) [inline, private]
Definition at line 2778 of file Form1.cs.
References Risk1.Form1.pictureBox1_Click().
        {
            this.pictureBox1_Click(sender, e);
        }
void Risk1.Form1.label24_Click (object sender, EventArgs e) [inline, private]
Definition at line 2773 of file Form1.cs.
References Risk1.Form1.pictureBox1_Click().
        {
            this.pictureBox1_Click(sender, e);
        }
void Risk1.Form1.label25_Click (object sender, EventArgs e) [inline, private]
Definition at line 2768 of file Form1.cs.
References Risk1.Form1.pictureBox1_Click().
        {
            this.pictureBox1_Click(sender, e);
        }
void Risk1.Form1.label26_Click (object sender, EventArgs e) [inline, private]
Definition at line 2763 of file Form1.cs.
References Risk1.Form1.pictureBox1_Click().
        {
            this.pictureBox1_Click(sender, e);
        }
void Risk1.Form1.label27_Click (object sender, EventArgs e) [inline, private]
Definition at line 2813 of file Form1.cs.
References Risk1.Form1.pictureBox1_Click().
        {
            this.pictureBox1_Click(sender, e);
        }
void Risk1.Form1.label28_Click (object sender, EventArgs e) [inline, private]
Definition at line 2823 of file Form1.cs.
References Risk1.Form1.pictureBox1_Click().
        {
            this.pictureBox1_Click(sender, e);
        }
void Risk1.Form1.label29_Click (object sender, EventArgs e) [inline, private]
Definition at line 2818 of file Form1.cs.
References Risk1.Form1.pictureBox1_Click().
        {
            this.pictureBox1_Click(sender, e);
        }
void Risk1.Form1.label2_Click (object sender, EventArgs e) [inline, private]
Definition at line 2658 of file Form1.cs.
References Risk1.Form1.pictureBox1_Click().
        {
            this.pictureBox1_Click(sender, e);
        }
void Risk1.Form1.label30_Click (object sender, EventArgs e) [inline, private]
Definition at line 2808 of file Form1.cs.
References Risk1.Form1.pictureBox1_Click().
        {
            this.pictureBox1_Click(sender, e);
        }
void Risk1.Form1.label31_Click (object sender, EventArgs e) [inline, private]
Definition at line 2803 of file Form1.cs.
References Risk1.Form1.pictureBox1_Click().
        {
            this.pictureBox1_Click(sender, e);
        }
void Risk1.Form1.label32_Click (object sender, EventArgs e) [inline, private]
Definition at line 2858 of file Form1.cs.
References Risk1.Form1.pictureBox1_Click().
        {
            this.pictureBox1_Click(sender, e);
        }
void Risk1.Form1.label33_Click (object sender, EventArgs e) [inline, private]
Definition at line 2848 of file Form1.cs.
References Risk1.Form1.pictureBox1_Click().
        {
            this.pictureBox1_Click(sender, e);
        }
void Risk1.Form1.label34_Click (object sender, EventArgs e) [inline, private]
Definition at line 2828 of file Form1.cs.
References Risk1.Form1.pictureBox1_Click().
        {
            this.pictureBox1_Click(sender, e);
        }
void Risk1.Form1.label35_Click (object sender, EventArgs e) [inline, private]
Definition at line 2833 of file Form1.cs.
References Risk1.Form1.pictureBox1_Click().
        {
            this.pictureBox1_Click(sender, e);
        }
void Risk1.Form1.label36_Click (object sender, EventArgs e) [inline, private]
Definition at line 2853 of file Form1.cs.
References Risk1.Form1.pictureBox1_Click().
        {
            this.pictureBox1_Click(sender, e);
        }
void Risk1.Form1.label37_Click (object sender, EventArgs e) [inline, private]
Definition at line 2838 of file Form1.cs.
References Risk1.Form1.pictureBox1_Click().
        {
            this.pictureBox1_Click(sender, e);
        }
void Risk1.Form1.label38_Click (object sender, EventArgs e) [inline, private]
Definition at line 2843 of file Form1.cs.
References Risk1.Form1.pictureBox1_Click().
        {
            this.pictureBox1_Click(sender, e);
        }
void Risk1.Form1.label39_Click (object sender, EventArgs e) [inline, private]
Definition at line 2798 of file Form1.cs.
References Risk1.Form1.pictureBox1_Click().
        {
            this.pictureBox1_Click(sender, e);
        }
void Risk1.Form1.label3_Click (object sender, EventArgs e) [inline, private]
Definition at line 2663 of file Form1.cs.
References Risk1.Form1.pictureBox1_Click().
        {
            this.pictureBox1_Click(sender, e);
        }
void Risk1.Form1.label40_Click (object sender, EventArgs e) [inline, private]
Definition at line 2788 of file Form1.cs.
References Risk1.Form1.pictureBox1_Click().
        {
            this.pictureBox1_Click(sender, e);
        }
void Risk1.Form1.label41_Click (object sender, EventArgs e) [inline, private]
Definition at line 2783 of file Form1.cs.
References Risk1.Form1.pictureBox1_Click().
        {
            this.pictureBox1_Click(sender, e);
        }
void Risk1.Form1.label42_Click (object sender, EventArgs e) [inline, private]
Definition at line 2793 of file Form1.cs.
        {
        }
void Risk1.Form1.label4_Click (object sender, EventArgs e) [inline, private]
Definition at line 2668 of file Form1.cs.
References Risk1.Form1.pictureBox1_Click().
        {
            this.pictureBox1_Click(sender, e);
        }
void Risk1.Form1.label5_Click (object sender, EventArgs e) [inline, private]
Definition at line 2673 of file Form1.cs.
References Risk1.Form1.pictureBox1_Click().
        {
            this.pictureBox1_Click(sender, e);
        }
void Risk1.Form1.label6_Click (object sender, EventArgs e) [inline, private]
Definition at line 2678 of file Form1.cs.
References Risk1.Form1.pictureBox1_Click().
        {
            this.pictureBox1_Click(sender, e);
        }
void Risk1.Form1.label7_Click (object sender, EventArgs e) [inline, private]
Definition at line 2683 of file Form1.cs.
References Risk1.Form1.pictureBox1_Click().
        {
            this.pictureBox1_Click(sender, e);
        }
void Risk1.Form1.label8_Click (object sender, EventArgs e) [inline, private]
Definition at line 2688 of file Form1.cs.
References Risk1.Form1.pictureBox1_Click().
        {
            this.pictureBox1_Click(sender, e);
        }
void Risk1.Form1.label9_Click (object sender, EventArgs e) [inline, private]
Definition at line 2693 of file Form1.cs.
References Risk1.Form1.pictureBox1_Click().
        {
            this.pictureBox1_Click(sender, e);
        }
void Risk1.Form1.newGameToolStripMenuItem_Click (object sender, EventArgs e) [inline, private]
Definition at line 2455 of file Form1.cs.
References Risk1.Form1.bolgeler, Risk1.Form1.changeLabel(), Risk1.Form1.changeStatistics(), Risk1.Form1.changeTerritoryColor(), Risk1.Form1.changeTurn(), Risk1.Form1.endGameToolStripMenuItem, Risk1.Form1.ganimetBolgesi, Risk1.Form1.getNextTurn(), Risk1.Form1.history, Risk1.Form1.ilkAskerler, Risk1.Form1.ilkAskerSayisi, Risk1.Form1.isRandom, Risk1.Form1.labels, Risk1.Form1.listView1, Risk1.Form1.newGameToolStripMenuItem, Risk1.Player.OptimizeAskerSayisiTarihi(), Risk1.Form1.panel1, Risk1.Form1.pictureBox1, Risk1.Statistics.players, Risk1.Form1.players, Risk1.Form1.rulesToolStripMenuItem, Risk1.Form1.showHistoryToolStripMenuItem, Risk1.Form1.statistics, Risk1.Form1.turn, Risk1.Form1.txtInfo, Risk1.Form1.txtPlayer, and Risk1.Form1.yeniOyunIptal.
        {
            yeniOyunIptal = false;
            Giris giris = new Giris(players,this);
            giris.ShowDialog();
            if (!yeniOyunIptal)
            {
                this.Height += 40;
                Random rand = new Random();
                ganimetBolgesi = rand.Next(0, 41);
                newGameToolStripMenuItem.Enabled = false;
                rulesToolStripMenuItem.Enabled = false;
                endGameToolStripMenuItem.Enabled = true;
                foreach (Label l in labels)
                {
                    l.Visible = true;
                    l.Enabled = true;
                }
                panel1.Visible = true;
                pictureBox1.Enabled = true;
                listView1.Visible = true;
                //Aktif olmayan playerleri player listesinden karyorum
                List<Player> silinecekler = new List<Player>();
                for (int i = 0; i <= 9; i++)
                {
                    if (!players[i].isActive)
                    {
                        silinecekler.Add(players[i]);
                    }
                }
                foreach (Player silinecek in silinecekler)
                {
                    players.Remove(silinecek);
                }
                ilkAskerler = players.Count * ilkAskerSayisi;
                if (isRandom)//Random olma durumunda bolgeler otomatik atanacak...
                {
                    List<int> sayilar = new List<int>();
                    for (int i = 0; i <= 41; i++)
                    {
                        sayilar.Add(i);
                    }
                    for (int i = 0; i <= 41; i++)
                    {
                        Random r = new Random();
                        int index = r.Next(0, sayilar.Count - 1);
                        bolgeler[sayilar[index]].sahip = players[turn];
                        bolgeler[sayilar[index]].sahipli = true;
                        players[turn].bolgeler.Add(bolgeler[sayilar[index]]);
                        changeTerritoryColor(bolgeler[sayilar[index]], players[turn]);
                        changeLabel(bolgeler[sayilar[index]]);
                        if (i == 41)
{
                            changeTurn();
                        }
                        else
{
                            txtInfo.Text = players[turn].name + " place your army " + "[" + players[turn].ilkAskerSayisi.ToString() + "]";
                            turn = getNextTurn();
                        }
                        sayilar.RemoveAt(index);
                    }
                    showHistoryToolStripMenuItem.Enabled = true;
                }
                if (!isRandom)
                {
                    if (!players[turn].isHuman)
                    {
                        changeTurn();
                    }
                    txtInfo.Text = players[turn].name + " please choose a territory";
                    txtPlayer.Text = players[turn].name;
                    txtPlayer.BackColor = players[turn].color;
                }
                changeStatistics();
                foreach (Player p in players)
                {
                    history.Add(p.OptimizeAskerSayisiTarihi());
                }
                listView1.Visible = true;
                statistics.players = players;
            }
        }
void Risk1.Form1.olduMu () [inline]
Definition at line 816 of file Form1.cs.
References Risk1.Form1.changeStatistics(), Risk1.Player.getTotalNumberOfArmies(), Risk1.Form1.ilkAskerler, Risk1.Form1.listView1, Risk1.Form1.players, Risk1.Statistics.siralama, Risk1.Form1.statistics, and Risk1.Form1.turn.
Referenced by Risk1.Form1.changeTurn(), and Risk1.Form1.pictureBox1_Click().
        {
            int index = 0;
            int silinecek = -2;
            foreach (Player p in players)
            {
                if (p.getTotalNumberOfArmies() == 0)
                {
                    silinecek = index;
                }
                index++;
            }
            if (silinecek != -2 && ilkAskerler == 0)
            {
                if (silinecek < turn)
                {
                    turn--;
                }
                statistics.siralama.Add(players[silinecek].name);
                players.RemoveAt(silinecek);
                changeStatistics();
                players[turn].buTurnBirisiniOldurduMu = true;
                players[turn].kacKisiOldurdu++;
                players[turn].buTurnKacKisiOldurdu++;
            }
            if (players.Count == 1 && ilkAskerler == 0)
            {
                statistics.siralama.Add(players[0].name);
                Galibiyet g = new Galibiyet(this);
                listView1.Visible = false;
                g.ShowDialog();
                Application.Exit();
            }
        }
void Risk1.Form1.pictureBox1_Click (object sender, EventArgs e) [inline, private]
Definition at line 91 of file Form1.cs.
References Risk1.Ordu.askerSayisi, Risk1.Form1.bolgeler, Risk1.Form1.button2, Risk1.Form1.butunBolgelerSecildiMi(), Risk1.Form1.changeInfo(), Risk1.Form1.changeLabel(), Risk1.Form1.changeStatistics(), Risk1.Form1.changeTerritoryColor(), Risk1.Form1.changeTurn(), Risk1.Form1.ganimetBolgseiniBildir(), Risk1.Form1.ilkAskerler, Risk1.Form1.ilkTiklananBolge, Risk1.Form1.isArmyMoved, Risk1.Bolge.isim, Risk1.Bolge.komsular, Risk1.Form1.label, Risk1.Bolge.noktalar, Risk1.Form1.olduMu(), Risk1.Bolge.ordu, Risk1.Form1.pictureBox1, Risk1.Form1.players, Risk1.Nokta.point, Risk1.Bolge.sahip, Risk1.Bolge.sahipli, Risk1.Form1.showHistoryToolStripMenuItem, Risk1.Form1.state, Risk1.Form1.turn, and Risk1.Form1.txtInfo.
Referenced by Risk1.Form1.label10_Click(), Risk1.Form1.label11_Click(), Risk1.Form1.label12_Click(), Risk1.Form1.label13_Click(), Risk1.Form1.label14_Click(), Risk1.Form1.label15_Click(), Risk1.Form1.label16_Click(), Risk1.Form1.label17_Click(), Risk1.Form1.label18_Click(), Risk1.Form1.label19_Click(), Risk1.Form1.label1_Click(), Risk1.Form1.label20_Click(), Risk1.Form1.label21_Click(), Risk1.Form1.label22_Click(), Risk1.Form1.label23_Click(), Risk1.Form1.label24_Click(), Risk1.Form1.label25_Click(), Risk1.Form1.label26_Click(), Risk1.Form1.label27_Click(), Risk1.Form1.label28_Click(), Risk1.Form1.label29_Click(), Risk1.Form1.label2_Click(), Risk1.Form1.label30_Click(), Risk1.Form1.label31_Click(), Risk1.Form1.label32_Click(), Risk1.Form1.label33_Click(), Risk1.Form1.label34_Click(), Risk1.Form1.label35_Click(), Risk1.Form1.label36_Click(), Risk1.Form1.label37_Click(), Risk1.Form1.label38_Click(), Risk1.Form1.label39_Click(), Risk1.Form1.label3_Click(), Risk1.Form1.label40_Click(), Risk1.Form1.label41_Click(), Risk1.Form1.label4_Click(), Risk1.Form1.label5_Click(), Risk1.Form1.label6_Click(), Risk1.Form1.label7_Click(), Risk1.Form1.label8_Click(), and Risk1.Form1.label9_Click().
        {
            if (players[turn].isHuman)
            {
                //Kodlar buraya gelecek
                //Tklanan yerin kordinatn ve rengini gsterir
                Bitmap bm = new Bitmap(pictureBox1.Image);
                Point localmousePosition = pictureBox1.PointToClient(System.Windows.Forms.Cursor.Position);
                Color col = bm.GetPixel(localmousePosition.X, localmousePosition.Y);
                //MessageBox.Show("X= " + localmousePosition.X.ToString() + "\nY= " + localmousePosition.Y.ToString() +"\nRenk:"+ col.Name);
                foreach (Bolge bol in bolgeler)
                {
                    bool broke = false;
                    foreach (Nokta n in bol.noktalar)
                    {
                        if (n.point == localmousePosition)
{
                            //MessageBox.Show(bol.isim);
                            //ncelikle Blgeler Seilecek
                            if (!butunBolgelerSecildiMi())
{
                                if (!bol.sahipli)
{
                                    bol.sahip = players[turn];
                                    bol.sahipli = true;
                                    players[turn].bolgeler.Add(bol);
                                    changeTerritoryColor(bol, players[turn]);
                                    //txtInfo.Text = players[getNextTurn()].name + " please choose a territory";
                                    if (butunBolgelerSecildiMi())
{
                                        changeInfo("Game Starts...");
                                    }
                                    changeTurn();
                                    changeLabel(bol);
                                }
                                if (butunBolgelerSecildiMi())
{
                                    //changeInfo(players[turn].name + " please place your army. [" + Math.Floor((double)(ilkAskerler / players.Count)).ToString() + "]");
                                    showHistoryToolStripMenuItem.Enabled = true;
                                }
                            }
                            else
{
                                //Kodlar Buraya Gelecek
                                if (ilkAskerler > 0)//lk Askerleri Datlmasmas bitene kadar
{
                                    if (bol.sahip == players[turn])
{
                                        ilkAskerler--;
                                        players[turn].ilkAskerSayisi--;
                                        bol.ordu.askerSayisi++;
                                        changeLabel(bol);
                                        changeTurn();
                                        //changeInfo(players[turn].name + " please place your army. [" +players[turn].ilkAskerSayisi .ToString() + "]");
                                    }
                                    if (ilkAskerler == 0)
{
                                        changeInfo("You have " + players[turn].yeniAskerler + " armies left to place [+SHIFT=place all]");
                                        ganimetBolgseiniBildir();
                                        ToolTip buttonToolTip = new ToolTip();
                                        buttonToolTip.UseFading = true;
                                        buttonToolTip.UseAnimation = true;
                                        //buttonToolTip.IsBalloon = true;
                                        buttonToolTip.ShowAlways = true;
                                        buttonToolTip.AutoPopDelay = 5000;
                                        buttonToolTip.InitialDelay = 1000;
                                        buttonToolTip.ReshowDelay = 500;
                                        buttonToolTip.Show("Gold is here!", label, 4000);
                                        //buttonToolTip.SetToolTip(label, "Gold is Here!");
                                    }
                                }//ilk Askerlerin Datlmas Bittikten Sonra
                                else
{
                                    //ncelikle her turn de verilen askerlerin yerine yerletirilmesi lazm
                                    if (players[turn].yeniAskerler > 0)
{
                                        if (bol.sahip == players[turn])
{
                                            if (Control.ModifierKeys == Keys.Shift)
{
                                                bol.ordu.askerSayisi += players[turn].yeniAskerler;
                                                players[turn].yeniAskerler = 0;
                                                changeLabel(bol);
                                                txtInfo.Text = "Attack or pass (press to spacebar)";
                                            }
                                            else
{
                                                players[turn].yeniAskerler--;
                                                bol.ordu.askerSayisi++;
                                                changeLabel(bol);
                                                changeInfo("You have " + players[turn].yeniAskerler + " armies left to place [+SHIFT=place all]");
                                            }
                                            if (players[turn].yeniAskerler == 0)
{
                                                button2.Enabled = true;
                                            }
                                        }
                                    }
                                    if (players[turn].yeniAskerler == 0)
{
                                        //Askerler Datld imdi hucum yaplabilir
                                        if (state == 0 && bol.sahip == players[turn])//lk kez kendi yerine tklyor
{
                                            state = 1;
                                            txtInfo.Text = "From " + bol.isim + ". Choose a territory to attack or move to (spacebar to pass)";
                                            ilkTiklananBolge = bol;
                                        }
                                        else if (state == 1 && bol.komsular.Contains(ilkTiklananBolge))//komusuna tklam
{
                                            if (bol.sahip == players[turn])//kendi blgesine transfer
{
                                                if (ilkTiklananBolge.ordu.askerSayisi > 1 || bol.ordu.askerSayisi > 1)
{
                                                    int b1 = ilkTiklananBolge.ordu.askerSayisi;
                                                    int b2 = bol.ordu.askerSayisi;
                                                    ArmyMove am = new ArmyMove(ilkTiklananBolge, bol, this);
                                                    am.ShowDialog();
                                                    if (isArmyMoved)
{
                                                        changeLabel(ilkTiklananBolge);
                                                        changeLabel(bol);
                                                        changeTurn();
                                                        isArmyMoved = false;
                                                    }
                                                    else
{
                                                        ilkTiklananBolge.ordu.askerSayisi = b1;
                                                        bol.ordu.askerSayisi = b2;
                                                    }
                                                }
                                                state = 0;
                                                ilkTiklananBolge = null;
                                            }
                                            else //Dman blgesine saldr
{
                                                if (ilkTiklananBolge.ordu.askerSayisi > 1)
{
                                                    SaldiriEkrani saldiriekrani = new SaldiriEkrani(ilkTiklananBolge, bol, this);
                                                    saldiriekrani.ShowDialog();
                                                    isArmyMoved = false;
                                                }
                                                ilkTiklananBolge = null;
                                                state = 0;
                                            }
                                        }
                                        else
{
                                            state = 0;
                                            ilkTiklananBolge = null;
                                        }
                                    }
                                }
                            }
                            broke = true;
                            break;
                        }
                    }
                    if (broke) break;
                }
                olduMu();
                changeStatistics();
            }
        }
void Risk1.Form1.pictureBox1_MouseMove (object sender, MouseEventArgs e) [inline, private]
Definition at line 2632 of file Form1.cs.
        {
        }
void Risk1.Form1.pictureBox2_Click (object sender, EventArgs e) [inline, private]
Definition at line 2643 of file Form1.cs.
        {
            System.Diagnostics.Process.Start("https://www.facebook.com/pages/Risk-Game/256463171079345");
        }
void Risk1.Form1.pictureBox3_Click (object sender, EventArgs e) [inline, private]
Definition at line 2648 of file Form1.cs.
        {
            System.Diagnostics.Process.Start("http://twitter.com/#!/RISKGAMEWAR");
        }
void Risk1.Form1.refreshGame () [inline]
Definition at line 513 of file Form1.cs.
References Risk1.Form1.label1, Risk1.Form1.label10, Risk1.Form1.label11, Risk1.Form1.label12, Risk1.Form1.label13, Risk1.Form1.label14, Risk1.Form1.label15, Risk1.Form1.label16, Risk1.Form1.label17, Risk1.Form1.label18, Risk1.Form1.label19, Risk1.Form1.label2, Risk1.Form1.label20, Risk1.Form1.label21, Risk1.Form1.label22, Risk1.Form1.label23, Risk1.Form1.label24, Risk1.Form1.label25, Risk1.Form1.label26, Risk1.Form1.label27, Risk1.Form1.label28, Risk1.Form1.label29, Risk1.Form1.label3, Risk1.Form1.label30, Risk1.Form1.label31, Risk1.Form1.label32, Risk1.Form1.label33, Risk1.Form1.label34, Risk1.Form1.label35, Risk1.Form1.label36, Risk1.Form1.label37, Risk1.Form1.label38, Risk1.Form1.label39, Risk1.Form1.label4, Risk1.Form1.label40, Risk1.Form1.label41, Risk1.Form1.label42, Risk1.Form1.label5, Risk1.Form1.label6, Risk1.Form1.label7, Risk1.Form1.label8, Risk1.Form1.label9, Risk1.Form1.listView1, and Risk1.Form1.pictureBox1.
Referenced by Risk1.Form1.changeTurn(), Risk1.SaldiriEkrani.warDoORDie(), and Risk1.SaldiriEkrani.warDoORDieForAi().
        {
            pictureBox1.Refresh();
            label1.Refresh();
            label2.Refresh();
            label3.Refresh();
            label4.Refresh();
            label5.Refresh();
            label6.Refresh();
            label7.Refresh();
            label8.Refresh();
            label9.Refresh();
            label10.Refresh();
            label11.Refresh();
            label12.Refresh();
            label13.Refresh();
            label14.Refresh();
            label15.Refresh();
            label16.Refresh();
            label17.Refresh();
            label18.Refresh();
            label19.Refresh();
            label20.Refresh();
            label21.Refresh();
            label22.Refresh();
            label23.Refresh();
            label24.Refresh();
            label25.Refresh();
            label26.Refresh();
            label27.Refresh();
            label28.Refresh();
            label29.Refresh();
            label30.Refresh();
            label31.Refresh();
            label32.Refresh();
            label33.Refresh();
            label34.Refresh();
            label35.Refresh();
            label36.Refresh();
            label37.Refresh();
            label38.Refresh();
            label39.Refresh();
            label40.Refresh();
            label41.Refresh();
            label42.Refresh();
            if (this.Width == 1053)
            {
                try
                {
                    listView1.Refresh();
                }
                catch
                {
                }
            }
        }
void Risk1.Form1.rulesToolStripMenuItem_Click (object sender, EventArgs e) [inline, private]
Definition at line 2591 of file Form1.cs.
References Risk1.Form1.ilkAskerSayisi, Risk1.Player.ilkAskerSayisi, and Risk1.Form1.players.
        {
            Rules rules = new Rules(this);
            rules.ShowDialog();
            foreach (Player p in players)
            {
                p.ilkAskerSayisi = ilkAskerSayisi;
            }
        }
void Risk1.Form1.showHistoryToolStripMenuItem_Click (object sender, EventArgs e) [inline, private]
Definition at line 2869 of file Form1.cs.
        {
            Chart c = new Chart(this);
            c.Show();
        }
void Risk1.Form1.showStatisticsToolStripMenuItem_Click (object sender, EventArgs e) [inline, private]
Definition at line 2611 of file Form1.cs.
References Risk1.Form1.hideStatisticsToolStripMenuItem, Risk1.Form1.listView1, Risk1.Form1.newGameToolStripMenuItem, and Risk1.Form1.showStatisticsToolStripMenuItem.
Referenced by Risk1.Form1.Form1_Load().
        {
            this.Width = 1053;
            showStatisticsToolStripMenuItem.Enabled = false;
            hideStatisticsToolStripMenuItem.Enabled = true;
            listView1.Enabled = true;
            if (!newGameToolStripMenuItem.Enabled)
            {
                listView1.Visible = true;
            }
        }
void Risk1.Form1.timer1_Tick (object sender, EventArgs e) [inline, private]
Definition at line 2880 of file Form1.cs.
        {
            Application.DoEvents();
        }
void Risk1.Form1.updateGameData () [inline]
Definition at line 66 of file Form1.cs.
References Risk1.GameData.bolgeler, Risk1.Form1.bolgeler, Risk1.Form1.gameData, Risk1.GameData.ganimetBolgesi, Risk1.Form1.ganimetBolgesi, Risk1.GameData.ganimetKazanci, Risk1.Form1.ganimetKazanci, Risk1.GameData.kitalar, Risk1.Form1.kitalar, Risk1.GameData.players, Risk1.Form1.players, Risk1.GameData.turn, and Risk1.Form1.turn.
Referenced by Risk1.Form1.getGameData().
        {
            gameData.bolgeler = bolgeler;
            gameData.players = players;
            gameData.kitalar = kitalar;
            gameData.turn = turn;
            gameData.ganimetBolgesi = ganimetBolgesi;
            gameData.ganimetKazanci = ganimetKazanci;
        }
void Risk1.Form1.webSiteToolStripMenuItem_Click (object sender, EventArgs e) [inline, private]
Definition at line 2601 of file Form1.cs.
        {
            System.Diagnostics.Process.Start("http://developersland.net/index.php/feridmovsumov/74-risk-game-ferid-movsumov.html");
        }
ArtificalIntelligence Risk1.Form1.yapayzeka () [inline, private]
Definition at line 810 of file Form1.cs.
References Risk1.Form1.players, Risk1.Form1.turn, and Risk1.Form1.yapayzekalar.
Referenced by Risk1.Form1.changeTurn().
        {
            return yapayzekalar[players[turn].aiId - 1];
        }
Member Data Documentation
System.Windows.Forms.ToolStripMenuItem Risk1.Form1.aboutToolStripMenuItem [private]
Definition at line 1077 of file Form1.Designer.cs.
AI Risk1.Form1.ai = new AI()
Definition at line 35 of file Form1.cs.
Referenced by Risk1.Form1.Form1_Load().
AI2 Risk1.Form1.ai2 = new AI2()
Definition at line 36 of file Form1.cs.
Referenced by Risk1.Form1.Form1_Load().
AI3 Risk1.Form1.ai3 = new AI3()
Definition at line 37 of file Form1.cs.
Referenced by Risk1.Form1.Form1_Load().
AI4 Risk1.Form1.ai4 = new AI4()
Definition at line 38 of file Form1.cs.
Referenced by Risk1.Form1.Form1_Load().
System.Windows.Forms.ColumnHeader Risk1.Form1.armies [private]
Definition at line 1083 of file Form1.Designer.cs.
List<Bolge> Risk1.Form1.bolgeler = new List<Bolge>()
Definition at line 24 of file Form1.cs.
Referenced by Risk1.Form1.afrika(), Risk1.Form1.asya(), Risk1.Form1.avrupa(), Risk1.Form1.avustralya(), Risk1.Form1.butunBolgelerSecildiMi(), Risk1.Form1.changeTurn(), Risk1.Form1.Form1_Load(), Risk1.Form1.guneyAmerika(), Risk1.Form1.kitaKazanci(), Risk1.Form1.kuzeyAmerika(), Risk1.Form1.newGameToolStripMenuItem_Click(), Risk1.Form1.pictureBox1_Click(), and Risk1.Form1.updateGameData().
System.Windows.Forms.Button Risk1.Form1.button2 [private]
Definition at line 1024 of file Form1.Designer.cs.
Referenced by Risk1.Form1.changeTurn(), Risk1.Form1.Form1_KeyDown(), and Risk1.Form1.pictureBox1_Click().
System.Windows.Forms.ToolStripMenuItem Risk1.Form1.changeStyleToolStripMenuItem [private]
Definition at line 1090 of file Form1.Designer.cs.
System.ComponentModel.IContainer Risk1.Form1.components = null [private]
Required designer variable.
Definition at line 8 of file Form1.Designer.cs.
System.Windows.Forms.ColumnHeader Risk1.Form1.continents
Definition at line 1086 of file Form1.Designer.cs.
List<Nokta> Risk1.Form1.deniz = new List<Nokta>()
Definition at line 41 of file Form1.cs.
Referenced by Risk1.Form1.changeDenizColor(), Risk1.ChangeStyle.ChangeStyle_Load(), and Risk1.Form1.Form1_Load().
System.Windows.Forms.ToolStripMenuItem Risk1.Form1.endGameToolStripMenuItem [private]
Definition at line 1071 of file Form1.Designer.cs.
Referenced by Risk1.Form1.Form1_Load(), and Risk1.Form1.newGameToolStripMenuItem_Click().
System.Windows.Forms.ToolStripMenuItem Risk1.Form1.exitToolStripMenuItem [private]
Definition at line 1072 of file Form1.Designer.cs.
System.Windows.Forms.ToolStripMenuItem Risk1.Form1.facebookPageToolStripMenuItem [private]
Definition at line 1087 of file Form1.Designer.cs.
System.Windows.Forms.ToolStripMenuItem Risk1.Form1.followUsOnTwitterToolStripMenuItem [private]
Definition at line 1092 of file Form1.Designer.cs.
GameData Risk1.Form1.gameData = new GameData()
Definition at line 44 of file Form1.cs.
Referenced by Risk1.Form1.getGameData(), and Risk1.Form1.updateGameData().
System.Windows.Forms.ToolStripMenuItem Risk1.Form1.gameToolStripMenuItem [private]
Definition at line 1069 of file Form1.Designer.cs.
int Risk1.Form1.ganimetBolgesi [private]
Definition at line 33 of file Form1.cs.
Referenced by Risk1.Form1.ganimetBolgseiniBildir(), Risk1.Form1.kitaKazanci(), Risk1.Form1.newGameToolStripMenuItem_Click(), and Risk1.Form1.updateGameData().
int Risk1.Form1.ganimetKazanci = 1
Definition at line 34 of file Form1.cs.
Referenced by Risk1.Rules.button1_Click(), Risk1.Form1.kitaKazanci(), Risk1.Rules.Rules_Load(), and Risk1.Form1.updateGameData().
System.Windows.Forms.ToolStripMenuItem Risk1.Form1.helpToolStripMenuItem [private]
Definition at line 1076 of file Form1.Designer.cs.
System.Windows.Forms.ToolStripMenuItem Risk1.Form1.hideStatisticsToolStripMenuItem [private]
Definition at line 1081 of file Form1.Designer.cs.
Referenced by Risk1.Form1.hideStatistics(), Risk1.Form1.hideStatisticsToolStripMenuItem_Click(), and Risk1.Form1.showStatisticsToolStripMenuItem_Click().
List<List<int> > Risk1.Form1.history = new List<List<int>>()
Definition at line 43 of file Form1.cs.
Referenced by Risk1.Form1.endGame(), and Risk1.Form1.newGameToolStripMenuItem_Click().
int Risk1.Form1.ilkAskerler = 0
Definition at line 29 of file Form1.cs.
Referenced by Risk1.Form1.changePanel(), Risk1.Form1.changeTurn(), Risk1.Form1.endGame(), Risk1.Form1.newGameToolStripMenuItem_Click(), Risk1.Form1.olduMu(), and Risk1.Form1.pictureBox1_Click().
int Risk1.Form1.ilkAskerSayisi = 15
Definition at line 30 of file Form1.cs.
Referenced by Risk1.Rules.button1_Click(), Risk1.Form1.endGame(), Risk1.Form1.Form1_Load(), Risk1.Form1.newGameToolStripMenuItem_Click(), Risk1.Rules.Rules(), and Risk1.Form1.rulesToolStripMenuItem_Click().
Bolge Risk1.Form1.ilkTiklananBolge = null [private]
Definition at line 27 of file Form1.cs.
Referenced by Risk1.Form1.button2_Click(), Risk1.Form1.endGame(), Risk1.Form1.Form1_KeyDown(), and Risk1.Form1.pictureBox1_Click().
bool Risk1.Form1.isArmyMoved = false
Definition at line 31 of file Form1.cs.
Referenced by Risk1.ArmyMove.bolge1Azalt(), Risk1.ArmyMove.bolge2Azalt(), Risk1.ArmyMove.button1_Click(), Risk1.ArmyMove.button2_Click(), Risk1.ArmyMove.button4_Click(), Risk1.Form1.endGame(), Risk1.Form1.pictureBox1_Click(), Risk1.SaldiriEkrani.warAttack(), and Risk1.SaldiriEkrani.warDoORDie().
bool Risk1.Form1.isRandom = true
Definition at line 32 of file Form1.cs.
Referenced by Risk1.Rules.button1_Click(), Risk1.Form1.changeTurn(), Risk1.Form1.newGameToolStripMenuItem_Click(), and Risk1.Rules.Rules_Load().
List<Continent> Risk1.Form1.kitalar = new List<Continent>()
Definition at line 26 of file Form1.cs.
Referenced by Risk1.Form1.afrika(), Risk1.Form1.asya(), Risk1.Form1.avrupa(), Risk1.Form1.avustralya(), Risk1.Form1.Form1_Load(), Risk1.Form1.guneyAmerika(), Risk1.Form1.kitaKazanci(), Risk1.Form1.kuzeyAmerika(), and Risk1.Form1.updateGameData().
Label Risk1.Form1.label = null [private]
Definition at line 1105 of file Form1.cs.
Referenced by Risk1.Form1.ganimetBolgseiniBildir(), and Risk1.Form1.pictureBox1_Click().
System.Windows.Forms.Label Risk1.Form1.label1 [private]
Definition at line 1027 of file Form1.Designer.cs.
Referenced by Risk1.Form1.changeLabel(), Risk1.Form1.Form1_Load(), Risk1.Form1.ganimetBolgseiniBildir(), and Risk1.Form1.refreshGame().
System.Windows.Forms.Label Risk1.Form1.label10 [private]
Definition at line 1036 of file Form1.Designer.cs.
Referenced by Risk1.Form1.changeLabel(), Risk1.Form1.Form1_Load(), Risk1.Form1.ganimetBolgseiniBildir(), and Risk1.Form1.refreshGame().
System.Windows.Forms.Label Risk1.Form1.label11 [private]
Definition at line 1037 of file Form1.Designer.cs.
Referenced by Risk1.Form1.changeLabel(), Risk1.Form1.Form1_Load(), Risk1.Form1.ganimetBolgseiniBildir(), and Risk1.Form1.refreshGame().
System.Windows.Forms.Label Risk1.Form1.label12 [private]
Definition at line 1038 of file Form1.Designer.cs.
Referenced by Risk1.Form1.changeLabel(), Risk1.Form1.Form1_Load(), Risk1.Form1.ganimetBolgseiniBildir(), and Risk1.Form1.refreshGame().
System.Windows.Forms.Label Risk1.Form1.label13 [private]
Definition at line 1039 of file Form1.Designer.cs.
Referenced by Risk1.Form1.changeLabel(), Risk1.Form1.Form1_Load(), Risk1.Form1.ganimetBolgseiniBildir(), and Risk1.Form1.refreshGame().
System.Windows.Forms.Label Risk1.Form1.label14 [private]
Definition at line 1040 of file Form1.Designer.cs.
Referenced by Risk1.Form1.changeLabel(), Risk1.Form1.Form1_Load(), Risk1.Form1.ganimetBolgseiniBildir(), and Risk1.Form1.refreshGame().
System.Windows.Forms.Label Risk1.Form1.label15 [private]
Definition at line 1041 of file Form1.Designer.cs.
Referenced by Risk1.Form1.changeLabel(), Risk1.Form1.Form1_Load(), Risk1.Form1.ganimetBolgseiniBildir(), and Risk1.Form1.refreshGame().
System.Windows.Forms.Label Risk1.Form1.label16 [private]
Definition at line 1042 of file Form1.Designer.cs.
Referenced by Risk1.Form1.changeLabel(), Risk1.Form1.Form1_Load(), Risk1.Form1.ganimetBolgseiniBildir(), and Risk1.Form1.refreshGame().
System.Windows.Forms.Label Risk1.Form1.label17 [private]
Definition at line 1043 of file Form1.Designer.cs.
Referenced by Risk1.Form1.changeLabel(), Risk1.Form1.Form1_Load(), Risk1.Form1.ganimetBolgseiniBildir(), and Risk1.Form1.refreshGame().
System.Windows.Forms.Label Risk1.Form1.label18 [private]
Definition at line 1044 of file Form1.Designer.cs.
Referenced by Risk1.Form1.changeLabel(), Risk1.Form1.Form1_Load(), Risk1.Form1.ganimetBolgseiniBildir(), and Risk1.Form1.refreshGame().
System.Windows.Forms.Label Risk1.Form1.label19 [private]
Definition at line 1045 of file Form1.Designer.cs.
Referenced by Risk1.Form1.changeLabel(), Risk1.Form1.Form1_Load(), Risk1.Form1.ganimetBolgseiniBildir(), and Risk1.Form1.refreshGame().
System.Windows.Forms.Label Risk1.Form1.label2 [private]
Definition at line 1028 of file Form1.Designer.cs.
Referenced by Risk1.Form1.changeLabel(), Risk1.Form1.Form1_Load(), Risk1.Form1.ganimetBolgseiniBildir(), and Risk1.Form1.refreshGame().
System.Windows.Forms.Label Risk1.Form1.label20 [private]
Definition at line 1046 of file Form1.Designer.cs.
Referenced by Risk1.Form1.changeLabel(), Risk1.Form1.Form1_Load(), Risk1.Form1.ganimetBolgseiniBildir(), and Risk1.Form1.refreshGame().
System.Windows.Forms.Label Risk1.Form1.label21 [private]
Definition at line 1047 of file Form1.Designer.cs.
Referenced by Risk1.Form1.changeLabel(), Risk1.Form1.Form1_Load(), Risk1.Form1.ganimetBolgseiniBildir(), and Risk1.Form1.refreshGame().
System.Windows.Forms.Label Risk1.Form1.label22 [private]
Definition at line 1048 of file Form1.Designer.cs.
Referenced by Risk1.Form1.changeLabel(), Risk1.Form1.Form1_Load(), Risk1.Form1.ganimetBolgseiniBildir(), and Risk1.Form1.refreshGame().
System.Windows.Forms.Label Risk1.Form1.label23 [private]
Definition at line 1049 of file Form1.Designer.cs.
Referenced by Risk1.Form1.changeLabel(), Risk1.Form1.Form1_Load(), Risk1.Form1.ganimetBolgseiniBildir(), and Risk1.Form1.refreshGame().
System.Windows.Forms.Label Risk1.Form1.label24 [private]
Definition at line 1050 of file Form1.Designer.cs.
Referenced by Risk1.Form1.changeLabel(), Risk1.Form1.Form1_Load(), Risk1.Form1.ganimetBolgseiniBildir(), and Risk1.Form1.refreshGame().
System.Windows.Forms.Label Risk1.Form1.label25 [private]
Definition at line 1051 of file Form1.Designer.cs.
Referenced by Risk1.Form1.changeLabel(), Risk1.Form1.Form1_Load(), Risk1.Form1.ganimetBolgseiniBildir(), and Risk1.Form1.refreshGame().
System.Windows.Forms.Label Risk1.Form1.label26 [private]
Definition at line 1052 of file Form1.Designer.cs.
Referenced by Risk1.Form1.changeLabel(), Risk1.Form1.Form1_Load(), Risk1.Form1.ganimetBolgseiniBildir(), and Risk1.Form1.refreshGame().
System.Windows.Forms.Label Risk1.Form1.label27 [private]
Definition at line 1053 of file Form1.Designer.cs.
Referenced by Risk1.Form1.changeLabel(), Risk1.Form1.Form1_Load(), Risk1.Form1.ganimetBolgseiniBildir(), and Risk1.Form1.refreshGame().
System.Windows.Forms.Label Risk1.Form1.label28 [private]
Definition at line 1054 of file Form1.Designer.cs.
Referenced by Risk1.Form1.changeLabel(), Risk1.Form1.Form1_Load(), Risk1.Form1.ganimetBolgseiniBildir(), and Risk1.Form1.refreshGame().
System.Windows.Forms.Label Risk1.Form1.label29 [private]
Definition at line 1055 of file Form1.Designer.cs.
Referenced by Risk1.Form1.changeLabel(), Risk1.Form1.Form1_Load(), Risk1.Form1.ganimetBolgseiniBildir(), and Risk1.Form1.refreshGame().
System.Windows.Forms.Label Risk1.Form1.label3 [private]
Definition at line 1029 of file Form1.Designer.cs.
Referenced by Risk1.Form1.changeLabel(), Risk1.Form1.Form1_Load(), Risk1.Form1.ganimetBolgseiniBildir(), and Risk1.Form1.refreshGame().
System.Windows.Forms.Label Risk1.Form1.label30 [private]
Definition at line 1056 of file Form1.Designer.cs.
Referenced by Risk1.Form1.changeLabel(), Risk1.Form1.Form1_Load(), Risk1.Form1.ganimetBolgseiniBildir(), and Risk1.Form1.refreshGame().
System.Windows.Forms.Label Risk1.Form1.label31 [private]
Definition at line 1057 of file Form1.Designer.cs.
Referenced by Risk1.Form1.changeLabel(), Risk1.Form1.Form1_Load(), Risk1.Form1.ganimetBolgseiniBildir(), and Risk1.Form1.refreshGame().
System.Windows.Forms.Label Risk1.Form1.label32 [private]
Definition at line 1058 of file Form1.Designer.cs.
Referenced by Risk1.Form1.changeLabel(), Risk1.Form1.Form1_Load(), Risk1.Form1.ganimetBolgseiniBildir(), and Risk1.Form1.refreshGame().
System.Windows.Forms.Label Risk1.Form1.label33 [private]
Definition at line 1059 of file Form1.Designer.cs.
Referenced by Risk1.Form1.changeLabel(), Risk1.Form1.Form1_Load(), Risk1.Form1.ganimetBolgseiniBildir(), and Risk1.Form1.refreshGame().
System.Windows.Forms.Label Risk1.Form1.label34 [private]
Definition at line 1060 of file Form1.Designer.cs.
Referenced by Risk1.Form1.changeLabel(), Risk1.Form1.Form1_Load(), Risk1.Form1.ganimetBolgseiniBildir(), and Risk1.Form1.refreshGame().
System.Windows.Forms.Label Risk1.Form1.label35 [private]
Definition at line 1061 of file Form1.Designer.cs.
Referenced by Risk1.Form1.changeLabel(), Risk1.Form1.Form1_Load(), Risk1.Form1.ganimetBolgseiniBildir(), and Risk1.Form1.refreshGame().
System.Windows.Forms.Label Risk1.Form1.label36 [private]
Definition at line 1062 of file Form1.Designer.cs.
Referenced by Risk1.Form1.changeLabel(), Risk1.Form1.Form1_Load(), Risk1.Form1.ganimetBolgseiniBildir(), and Risk1.Form1.refreshGame().
System.Windows.Forms.Label Risk1.Form1.label37 [private]
Definition at line 1063 of file Form1.Designer.cs.
Referenced by Risk1.Form1.changeLabel(), Risk1.Form1.Form1_Load(), Risk1.Form1.ganimetBolgseiniBildir(), and Risk1.Form1.refreshGame().
System.Windows.Forms.Label Risk1.Form1.label38 [private]
Definition at line 1064 of file Form1.Designer.cs.
Referenced by Risk1.Form1.changeLabel(), Risk1.Form1.Form1_Load(), Risk1.Form1.ganimetBolgseiniBildir(), and Risk1.Form1.refreshGame().
System.Windows.Forms.Label Risk1.Form1.label39 [private]
Definition at line 1065 of file Form1.Designer.cs.
Referenced by Risk1.Form1.changeLabel(), Risk1.Form1.Form1_Load(), Risk1.Form1.ganimetBolgseiniBildir(), and Risk1.Form1.refreshGame().
System.Windows.Forms.Label Risk1.Form1.label4 [private]
Definition at line 1030 of file Form1.Designer.cs.
Referenced by Risk1.Form1.changeLabel(), Risk1.Form1.Form1_Load(), Risk1.Form1.ganimetBolgseiniBildir(), and Risk1.Form1.refreshGame().
System.Windows.Forms.Label Risk1.Form1.label40 [private]
Definition at line 1066 of file Form1.Designer.cs.
Referenced by Risk1.Form1.changeLabel(), Risk1.Form1.Form1_Load(), Risk1.Form1.ganimetBolgseiniBildir(), and Risk1.Form1.refreshGame().
System.Windows.Forms.Label Risk1.Form1.label41 [private]
Definition at line 1067 of file Form1.Designer.cs.
Referenced by Risk1.Form1.changeLabel(), Risk1.Form1.Form1_Load(), Risk1.Form1.ganimetBolgseiniBildir(), and Risk1.Form1.refreshGame().
System.Windows.Forms.Label Risk1.Form1.label42 [private]
Definition at line 1068 of file Form1.Designer.cs.
Referenced by Risk1.Form1.changeLabel(), Risk1.Form1.Form1_Load(), Risk1.Form1.ganimetBolgseiniBildir(), and Risk1.Form1.refreshGame().
System.Windows.Forms.Label Risk1.Form1.label5 [private]
Definition at line 1031 of file Form1.Designer.cs.
Referenced by Risk1.Form1.changeLabel(), Risk1.Form1.Form1_Load(), Risk1.Form1.ganimetBolgseiniBildir(), and Risk1.Form1.refreshGame().
System.Windows.Forms.Label Risk1.Form1.label6 [private]
Definition at line 1032 of file Form1.Designer.cs.
Referenced by Risk1.Form1.changeLabel(), Risk1.Form1.Form1_Load(), Risk1.Form1.ganimetBolgseiniBildir(), and Risk1.Form1.refreshGame().
System.Windows.Forms.Label Risk1.Form1.label7 [private]
Definition at line 1033 of file Form1.Designer.cs.
Referenced by Risk1.Form1.changeLabel(), Risk1.Form1.Form1_Load(), Risk1.Form1.ganimetBolgseiniBildir(), and Risk1.Form1.refreshGame().
System.Windows.Forms.Label Risk1.Form1.label8 [private]
Definition at line 1034 of file Form1.Designer.cs.
Referenced by Risk1.Form1.changeLabel(), Risk1.Form1.Form1_Load(), Risk1.Form1.ganimetBolgseiniBildir(), and Risk1.Form1.refreshGame().
System.Windows.Forms.Label Risk1.Form1.label9 [private]
Definition at line 1035 of file Form1.Designer.cs.
Referenced by Risk1.Form1.changeLabel(), Risk1.Form1.Form1_Load(), Risk1.Form1.ganimetBolgseiniBildir(), and Risk1.Form1.refreshGame().
List<Label> Risk1.Form1.labels = new List<Label>() [private]
Definition at line 39 of file Form1.cs.
Referenced by Risk1.Form1.endGame(), Risk1.Form1.Form1_Load(), and Risk1.Form1.newGameToolStripMenuItem_Click().
System.Windows.Forms.ListView Risk1.Form1.listView1 [private]
Definition at line 1082 of file Form1.Designer.cs.
Referenced by Risk1.Form1.changeStatistics(), Risk1.Form1.Form1_Load(), Risk1.Form1.hideStatistics(), Risk1.Form1.hideStatisticsToolStripMenuItem_Click(), Risk1.Form1.newGameToolStripMenuItem_Click(), Risk1.Form1.olduMu(), Risk1.Form1.refreshGame(), and Risk1.Form1.showStatisticsToolStripMenuItem_Click().
System.Windows.Forms.MenuStrip Risk1.Form1.menuStrip1 [private]
Definition at line 1079 of file Form1.Designer.cs.
System.Windows.Forms.ToolStripMenuItem Risk1.Form1.newGameToolStripMenuItem [private]
Definition at line 1070 of file Form1.Designer.cs.
Referenced by Risk1.Form1.newGameToolStripMenuItem_Click(), and Risk1.Form1.showStatisticsToolStripMenuItem_Click().
List<Nokta> Risk1.Form1.noktalar = new List<Nokta>() [private]
Definition at line 23 of file Form1.cs.
Referenced by Risk1.Form1.Form1_Load().
System.Windows.Forms.ToolStripMenuItem Risk1.Form1.optionsToolStripMenuItem [private]
Definition at line 1073 of file Form1.Designer.cs.
System.Windows.Forms.Panel Risk1.Form1.panel1 [private]
Definition at line 1023 of file Form1.Designer.cs.
Referenced by Risk1.Form1.newGameToolStripMenuItem_Click().
System.Windows.Forms.PictureBox Risk1.Form1.pictureBox1 [private]
Definition at line 1022 of file Form1.Designer.cs.
Referenced by Risk1.Form1.changeDenizColor(), Risk1.Form1.changeSinirColor(), Risk1.Form1.changeTerritoryColor(), Risk1.Form1.changeTurn(), Risk1.Form1.Form1_Load(), Risk1.Form1.newGameToolStripMenuItem_Click(), Risk1.Form1.pictureBox1_Click(), and Risk1.Form1.refreshGame().
System.Windows.Forms.PictureBox Risk1.Form1.pictureBox2 [private]
Definition at line 1088 of file Form1.Designer.cs.
System.Windows.Forms.PictureBox Risk1.Form1.pictureBox3 [private]
Definition at line 1089 of file Form1.Designer.cs.
System.Windows.Forms.PictureBox Risk1.Form1.pictureBox4 [private]
Definition at line 1094 of file Form1.Designer.cs.
System.Windows.Forms.ColumnHeader Risk1.Form1.player
Definition at line 1084 of file Form1.Designer.cs.
List<Player> Risk1.Form1.players = new List<Player>()
Definition at line 25 of file Form1.cs.
Referenced by Risk1.Form1.changePanel(), Risk1.Form1.changeStatistics(), Risk1.Form1.changeTurn(), Risk1.Chart.Chart_Load(), Risk1.Form1.endGame(), Risk1.Form1.Form1_Load(), Risk1.Galibiyet.Galibiyet(), Risk1.Galibiyet.Galibiyet_Load(), Risk1.Form1.getNextTurn(), Risk1.Form1.hangiKitalaraSahip(), Risk1.Form1.newGameToolStripMenuItem_Click(), Risk1.Form1.olduMu(), Risk1.Form1.pictureBox1_Click(), Risk1.Form1.rulesToolStripMenuItem_Click(), Risk1.Form1.updateGameData(), Risk1.SaldiriEkrani.warDoORDieForAi(), and Risk1.Form1.yapayzeka().
System.Windows.Forms.ToolStripMenuItem Risk1.Form1.rulesToolStripMenuItem [private]
Definition at line 1074 of file Form1.Designer.cs.
Referenced by Risk1.Form1.newGameToolStripMenuItem_Click().
System.Windows.Forms.ToolStripMenuItem Risk1.Form1.showHistoryToolStripMenuItem [private]
Definition at line 1091 of file Form1.Designer.cs.
Referenced by Risk1.Form1.changeTurn(), Risk1.Form1.newGameToolStripMenuItem_Click(), and Risk1.Form1.pictureBox1_Click().
System.Windows.Forms.ToolStripMenuItem Risk1.Form1.showStatisticsToolStripMenuItem [private]
Definition at line 1080 of file Form1.Designer.cs.
Referenced by Risk1.Form1.hideStatistics(), Risk1.Form1.hideStatisticsToolStripMenuItem_Click(), and Risk1.Form1.showStatisticsToolStripMenuItem_Click().
List<Nokta> Risk1.Form1.sinirlar = new List<Nokta>()
Definition at line 42 of file Form1.cs.
Referenced by Risk1.Form1.changeSinirColor(), and Risk1.Form1.Form1_Load().
int Risk1.Form1.state = 0 [private]
Definition at line 89 of file Form1.cs.
Referenced by Risk1.Form1.button2_Click(), Risk1.Form1.Form1_KeyDown(), and Risk1.Form1.pictureBox1_Click().
Statistics Risk1.Form1.statistics = new Statistics()
Definition at line 45 of file Form1.cs.
Referenced by Risk1.Galibiyet.Galibiyet_Load(), Risk1.Form1.newGameToolStripMenuItem_Click(), and Risk1.Form1.olduMu().
System.Windows.Forms.ToolStripMenuItem Risk1.Form1.statisticsToolStripMenuItem [private]
Definition at line 1075 of file Form1.Designer.cs.
System.Windows.Forms.ColumnHeader Risk1.Form1.territories
Definition at line 1085 of file Form1.Designer.cs.
System.Windows.Forms.Timer Risk1.Form1.timer1 [private]
Definition at line 1093 of file Form1.Designer.cs.
Referenced by Risk1.Form1.Form1_Load().
int Risk1.Form1.turn = 0
Definition at line 28 of file Form1.cs.
Referenced by Risk1.Form1.changePanel(), Risk1.Form1.changeTurn(), Risk1.Chart.Chart_Load(), Risk1.Form1.endGame(), Risk1.Form1.getNextTurn(), Risk1.Form1.newGameToolStripMenuItem_Click(), Risk1.Form1.olduMu(), Risk1.Form1.pictureBox1_Click(), Risk1.Form1.updateGameData(), Risk1.SaldiriEkrani.warDoORDieForAi(), and Risk1.Form1.yapayzeka().
System.Windows.Forms.TextBox Risk1.Form1.txtInfo [private]
Definition at line 1025 of file Form1.Designer.cs.
Referenced by Risk1.Form1.changeInfo(), Risk1.Form1.changePanel(), Risk1.Form1.changeTurn(), Risk1.Form1.newGameToolStripMenuItem_Click(), and Risk1.Form1.pictureBox1_Click().
System.Windows.Forms.TextBox Risk1.Form1.txtPlayer [private]
Definition at line 1026 of file Form1.Designer.cs.
Referenced by Risk1.Form1.changePanel(), and Risk1.Form1.newGameToolStripMenuItem_Click().
System.Windows.Forms.ToolStripMenuItem Risk1.Form1.webSiteToolStripMenuItem [private]
Definition at line 1078 of file Form1.Designer.cs.
List<ArtificalIntelligence> Risk1.Form1.yapayzekalar = new List<ArtificalIntelligence>()
Definition at line 40 of file Form1.cs.
Referenced by Risk1.Form1.endGame(), Risk1.Form1.Form1_Load(), Risk1.Giris.Giris_Load(), Risk1.SaldiriEkrani.warDoORDieForAi(), and Risk1.Form1.yapayzeka().
bool Risk1.Form1.yeniOyunIptal = false
Definition at line 2450 of file Form1.cs.
Referenced by Risk1.Giris.button12_Click(), and Risk1.Form1.newGameToolStripMenuItem_Click().
The documentation for this class was generated from the following files:
Risk1/Form1.cs
Risk1/Form1.Designer.cs