ANKARISK: Risk1.ArmyMove Class Reference
Risk1.ArmyMove Class Reference
Public Member Functions
ArmyMove (Bolge b1, Bolge b2, Form1 f1)
void bolge1Azalt (int number)
void bolge2Azalt (int number)
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void ArmyMove_Load (object sender, EventArgs e)
void button3_Click (object sender, EventArgs e)
void button5_Click (object sender, EventArgs e)
void button6_Click (object sender, EventArgs e)
void button8_Click (object sender, EventArgs e)
void button7_Click (object sender, EventArgs e)
void button9_Click (object sender, EventArgs e)
void button4_Click (object sender, EventArgs e)
void button2_Click (object sender, EventArgs e)
void button1_Click (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
Bolge bolge11 = null
Bolge bolge22 = null
Bolge bolge1 = new Bolge()
Bolge bolge2 = new Bolge()
Form1 form1 = null
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.Panel panel2
System.Windows.Forms.TextBox textBox1
System.Windows.Forms.TextBox textBox3
System.Windows.Forms.Panel panel1
System.Windows.Forms.TextBox textBox4
System.Windows.Forms.TextBox textBox2
System.Windows.Forms.Button button2
System.Windows.Forms.Button button1
System.Windows.Forms.Button button4
System.Windows.Forms.Button button3
System.Windows.Forms.Button button5
System.Windows.Forms.Button button6
System.Windows.Forms.Button button7
System.Windows.Forms.Button button8
System.Windows.Forms.Button button9
Detailed Description
Definition at line 12 of file ArmyMove.cs.
Constructor & Destructor Documentation
Risk1.ArmyMove.ArmyMove (Bolge b1, Bolge b2, Form1 f1) [inline]
Definition at line 19 of file ArmyMove.cs.
References Risk1.ArmyMove.bolge1, Risk1.ArmyMove.bolge11, Risk1.ArmyMove.bolge2, Risk1.ArmyMove.bolge22, Risk1.ArmyMove.form1, and Risk1.ArmyMove.InitializeComponent().
        {
            InitializeComponent();
            bolge11 = b1;
            bolge22 = b2;
            bolge1 = b1;
            bolge2 = b2;
            form1 = f1;
        }
Member Function Documentation
void Risk1.ArmyMove.ArmyMove_Load (object sender, EventArgs e) [inline, private]
Definition at line 29 of file ArmyMove.cs.
References Risk1.Ordu.askerSayisi, Risk1.ArmyMove.bolge1, Risk1.ArmyMove.bolge2, Risk1.ArmyMove.button4, Risk1.Player.color, Risk1.Bolge.isim, Risk1.Bolge.ordu, Risk1.ArmyMove.panel1, Risk1.ArmyMove.panel2, Risk1.Bolge.sahip, Risk1.ArmyMove.textBox1, Risk1.ArmyMove.textBox2, Risk1.ArmyMove.textBox3, and Risk1.ArmyMove.textBox4.
        {
            panel1.BackColor = bolge1.sahip.color;
            panel2.BackColor = bolge2.sahip.color;
            textBox4.Text = bolge1.isim;
            textBox1.Text = bolge2.isim;
            textBox2.Text = bolge1.ordu.askerSayisi.ToString();
            textBox3.Text = bolge2.ordu.askerSayisi.ToString();
            this.ActiveControl = button4;
        }
void Risk1.ArmyMove.bolge1Azalt (int number) [inline]
Definition at line 44 of file ArmyMove.cs.
References Risk1.Ordu.askerSayisi, Risk1.ArmyMove.bolge1, Risk1.ArmyMove.bolge2, Risk1.ArmyMove.form1, Risk1.Form1.isArmyMoved, Risk1.Bolge.ordu, Risk1.ArmyMove.textBox2, and Risk1.ArmyMove.textBox3.
Referenced by Risk1.ArmyMove.button3_Click(), Risk1.ArmyMove.button7_Click(), and Risk1.ArmyMove.button9_Click().
        {
            if ((bolge1.ordu.askerSayisi - number) > 0)
            {
                bolge2.ordu.askerSayisi += number;
                bolge1.ordu.askerSayisi -= number;
                textBox2.Text = bolge1.ordu.askerSayisi.ToString();
                textBox3.Text = bolge2.ordu.askerSayisi.ToString();
                form1.isArmyMoved = false;
            }
        }
void Risk1.ArmyMove.bolge2Azalt (int number) [inline]
Definition at line 55 of file ArmyMove.cs.
References Risk1.Ordu.askerSayisi, Risk1.ArmyMove.bolge1, Risk1.ArmyMove.bolge2, Risk1.ArmyMove.form1, Risk1.Form1.isArmyMoved, Risk1.Bolge.ordu, Risk1.ArmyMove.textBox2, and Risk1.ArmyMove.textBox3.
Referenced by Risk1.ArmyMove.button5_Click(), Risk1.ArmyMove.button6_Click(), and Risk1.ArmyMove.button8_Click().
        {
            if ((bolge2.ordu.askerSayisi - number) > 0)
            {
                bolge1.ordu.askerSayisi += number;
                bolge2.ordu.askerSayisi -= number;
                textBox2.Text = bolge1.ordu.askerSayisi.ToString();
                textBox3.Text = bolge2.ordu.askerSayisi.ToString();
                form1.isArmyMoved = false;
            }
        }
void Risk1.ArmyMove.button1_Click (object sender, EventArgs e) [inline, private]
Definition at line 115 of file ArmyMove.cs.
References Risk1.Ordu.askerSayisi, Risk1.ArmyMove.bolge1, Risk1.ArmyMove.bolge2, Risk1.ArmyMove.form1, Risk1.Form1.isArmyMoved, Risk1.Bolge.ordu, Risk1.ArmyMove.textBox2, and Risk1.ArmyMove.textBox3.
        {
            int toplam = bolge1.ordu.askerSayisi + bolge2.ordu.askerSayisi;
            if ((toplam % 2) == 0)
            {
                bolge1.ordu.askerSayisi = toplam / 2;
                bolge2.ordu.askerSayisi = toplam / 2;
                textBox2.Text = bolge1.ordu.askerSayisi.ToString();
                textBox3.Text = bolge2.ordu.askerSayisi.ToString();
            }
            else
            {
                bolge1.ordu.askerSayisi=toplam/2;
                bolge2.ordu.askerSayisi=(toplam/2)+1;
                textBox2.Text = bolge1.ordu.askerSayisi.ToString();
                textBox3.Text = bolge2.ordu.askerSayisi.ToString();
            }
            //bolge11 = bolge1;
            //bolge22 = bolge2;
            form1.isArmyMoved = true;
            this.Close();
        }
void Risk1.ArmyMove.button2_Click (object sender, EventArgs e) [inline, private]
Definition at line 101 of file ArmyMove.cs.
References Risk1.Ordu.askerSayisi, Risk1.ArmyMove.bolge1, Risk1.ArmyMove.bolge2, Risk1.ArmyMove.form1, Risk1.Form1.isArmyMoved, Risk1.Bolge.ordu, Risk1.ArmyMove.textBox2, and Risk1.ArmyMove.textBox3.
        {
            bolge2.ordu.askerSayisi += (bolge1.ordu.askerSayisi - 1);
            bolge1.ordu.askerSayisi = 1;
            textBox2.Text = bolge1.ordu.askerSayisi.ToString();
            textBox3.Text = bolge2.ordu.askerSayisi.ToString();
            form1.isArmyMoved = true;
            //bolge11 = bolge1;
            //bolge22 = bolge2;
            this.Close();
        }
void Risk1.ArmyMove.button3_Click (object sender, EventArgs e) [inline, private]
Definition at line 40 of file ArmyMove.cs.
References Risk1.ArmyMove.bolge1Azalt().
        {
            bolge1Azalt(1);
        }
void Risk1.ArmyMove.button4_Click (object sender, EventArgs e) [inline, private]
Definition at line 92 of file ArmyMove.cs.
References Risk1.ArmyMove.form1, and Risk1.Form1.isArmyMoved.
        {
            //bolge11 = bolge1;
            //bolge22 = bolge2;
            form1.isArmyMoved = true;
            Close();
        }
void Risk1.ArmyMove.button5_Click (object sender, EventArgs e) [inline, private]
Definition at line 67 of file ArmyMove.cs.
References Risk1.ArmyMove.bolge2Azalt().
        {
            bolge2Azalt(1);
        }
void Risk1.ArmyMove.button6_Click (object sender, EventArgs e) [inline, private]
Definition at line 72 of file ArmyMove.cs.
References Risk1.ArmyMove.bolge2Azalt().
        {
            bolge2Azalt(10);
        }
void Risk1.ArmyMove.button7_Click (object sender, EventArgs e) [inline, private]
Definition at line 82 of file ArmyMove.cs.
References Risk1.ArmyMove.bolge1Azalt().
        {
            bolge1Azalt(10);
        }
void Risk1.ArmyMove.button8_Click (object sender, EventArgs e) [inline, private]
Definition at line 77 of file ArmyMove.cs.
References Risk1.ArmyMove.bolge2Azalt().
        {
            bolge2Azalt(25);
        }
void Risk1.ArmyMove.button9_Click (object sender, EventArgs e) [inline, private]
Definition at line 87 of file ArmyMove.cs.
References Risk1.ArmyMove.bolge1Azalt().
        {
            bolge1Azalt(25);
        }
override void Risk1.ArmyMove.Dispose (bool disposing) [inline, protected]
Clean up any resources being used.
Parameters:
disposing true if managed resources should be disposed; otherwise, false.
Definition at line 14 of file ArmyMove.Designer.cs.
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }
void Risk1.ArmyMove.InitializeComponent () [inline, private]
Required method for Designer support - do not modify the contents of this method with the code editor.
Definition at line 29 of file ArmyMove.Designer.cs.
Referenced by Risk1.ArmyMove.ArmyMove().
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(ArmyMove));
            this.panel2 = new System.Windows.Forms.Panel();
            this.textBox1 = new System.Windows.Forms.TextBox();
            this.textBox3 = new System.Windows.Forms.TextBox();
            this.panel1 = new System.Windows.Forms.Panel();
            this.textBox4 = new System.Windows.Forms.TextBox();
            this.textBox2 = new System.Windows.Forms.TextBox();
            this.button2 = new System.Windows.Forms.Button();
            this.button1 = new System.Windows.Forms.Button();
            this.button4 = new System.Windows.Forms.Button();
            this.button3 = new System.Windows.Forms.Button();
            this.button5 = new System.Windows.Forms.Button();
            this.button6 = new System.Windows.Forms.Button();
            this.button7 = new System.Windows.Forms.Button();
            this.button8 = new System.Windows.Forms.Button();
            this.button9 = new System.Windows.Forms.Button();
            this.panel2.SuspendLayout();
            this.panel1.SuspendLayout();
            this.SuspendLayout();
            //
            // panel2
            //
            this.panel2.BackColor = System.Drawing.Color.Transparent;
            this.panel2.Controls.Add(this.textBox1);
            this.panel2.Controls.Add(this.textBox3);
            this.panel2.Location = new System.Drawing.Point(265, 1);
            this.panel2.Name = "panel2";
            this.panel2.Size = new System.Drawing.Size(142, 97);
            this.panel2.TabIndex = 3;
            //
            // textBox1
            //
            this.textBox1.BackColor = System.Drawing.Color.Black;
            this.textBox1.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.textBox1.ForeColor = System.Drawing.Color.White;
            this.textBox1.Location = new System.Drawing.Point(0, 15);
            this.textBox1.Name = "textBox1";
            this.textBox1.ReadOnly = true;
            this.textBox1.Size = new System.Drawing.Size(142, 20);
            this.textBox1.TabIndex = 3;
            this.textBox1.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            //
            // textBox3
            //
            this.textBox3.BackColor = System.Drawing.Color.DimGray;
            this.textBox3.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.textBox3.ForeColor = System.Drawing.Color.White;
            this.textBox3.Location = new System.Drawing.Point(48, 56);
            this.textBox3.Name = "textBox3";
            this.textBox3.ReadOnly = true;
            this.textBox3.Size = new System.Drawing.Size(56, 21);
            this.textBox3.TabIndex = 2;
            this.textBox3.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            //
            // panel1
            //
            this.panel1.BackColor = System.Drawing.Color.Transparent;
            this.panel1.Controls.Add(this.textBox4);
            this.panel1.Controls.Add(this.textBox2);
            this.panel1.Location = new System.Drawing.Point(1, 0);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(142, 98);
            this.panel1.TabIndex = 2;
            //
            // textBox4
            //
            this.textBox4.BackColor = System.Drawing.Color.Black;
            this.textBox4.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.textBox4.ForeColor = System.Drawing.Color.White;
            this.textBox4.Location = new System.Drawing.Point(0, 15);
            this.textBox4.Name = "textBox4";
            this.textBox4.ReadOnly = true;
            this.textBox4.Size = new System.Drawing.Size(142, 20);
            this.textBox4.TabIndex = 4;
            this.textBox4.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            //
            // textBox2
            //
            this.textBox2.BackColor = System.Drawing.Color.DimGray;
            this.textBox2.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.textBox2.ForeColor = System.Drawing.Color.White;
            this.textBox2.Location = new System.Drawing.Point(40, 56);
            this.textBox2.Name = "textBox2";
            this.textBox2.ReadOnly = true;
            this.textBox2.Size = new System.Drawing.Size(56, 21);
            this.textBox2.TabIndex = 1;
            this.textBox2.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            //
            // button2
            //
            this.button2.BackColor = System.Drawing.Color.Transparent;
            this.button2.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.button2.ForeColor = System.Drawing.Color.Blue;
            this.button2.Location = new System.Drawing.Point(31, 124);
            this.button2.Name = "button2";
            this.button2.Size = new System.Drawing.Size(100, 30);
            this.button2.TabIndex = 7;
            this.button2.Text = "ALL";
            this.button2.UseVisualStyleBackColor = false;
            this.button2.Click += new System.EventHandler(this.button2_Click);
            //
            // button1
            //
            this.button1.BackColor = System.Drawing.Color.Transparent;
            this.button1.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.button1.ForeColor = System.Drawing.Color.Red;
            this.button1.Location = new System.Drawing.Point(152, 124);
            this.button1.Name = "button1";
            this.button1.Size = new System.Drawing.Size(100, 30);
            this.button1.TabIndex = 8;
            this.button1.Text = "BALANCE";
            this.button1.UseVisualStyleBackColor = false;
            this.button1.Click += new System.EventHandler(this.button1_Click);
            //
            // button4
            //
            this.button4.BackColor = System.Drawing.Color.Transparent;
            this.button4.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.button4.ForeColor = System.Drawing.Color.Green;
            this.button4.Location = new System.Drawing.Point(282, 124);
            this.button4.Name = "button4";
            this.button4.Size = new System.Drawing.Size(100, 30);
            this.button4.TabIndex = 10;
            this.button4.Text = "OK";
            this.button4.UseVisualStyleBackColor = false;
            this.button4.Click += new System.EventHandler(this.button4_Click);
            //
            // button3
            //
            this.button3.Location = new System.Drawing.Point(212, 17);
            this.button3.Name = "button3";
            this.button3.Size = new System.Drawing.Size(44, 23);
            this.button3.TabIndex = 11;
            this.button3.Text = "1 >";
            this.button3.UseVisualStyleBackColor = true;
            this.button3.Click += new System.EventHandler(this.button3_Click);
            //
            // button5
            //
            this.button5.Location = new System.Drawing.Point(149, 17);
            this.button5.Name = "button5";
            this.button5.Size = new System.Drawing.Size(44, 23);
            this.button5.TabIndex = 12;
            this.button5.Text = "< 1";
            this.button5.UseVisualStyleBackColor = true;
            this.button5.Click += new System.EventHandler(this.button5_Click);
            //
            // button6
            //
            this.button6.Location = new System.Drawing.Point(149, 46);
            this.button6.Name = "button6";
            this.button6.Size = new System.Drawing.Size(44, 23);
            this.button6.TabIndex = 14;
            this.button6.Text = "< 10";
            this.button6.UseVisualStyleBackColor = true;
            this.button6.Click += new System.EventHandler(this.button6_Click);
            //
            // button7
            //
            this.button7.Location = new System.Drawing.Point(212, 46);
            this.button7.Name = "button7";
            this.button7.Size = new System.Drawing.Size(44, 23);
            this.button7.TabIndex = 13;
            this.button7.Text = "10 >";
            this.button7.UseVisualStyleBackColor = true;
            this.button7.Click += new System.EventHandler(this.button7_Click);
            //
            // button8
            //
            this.button8.Location = new System.Drawing.Point(149, 75);
            this.button8.Name = "button8";
            this.button8.Size = new System.Drawing.Size(44, 23);
            this.button8.TabIndex = 16;
            this.button8.Text = "< 25";
            this.button8.UseVisualStyleBackColor = true;
            this.button8.Click += new System.EventHandler(this.button8_Click);
            //
            // button9
            //
            this.button9.Location = new System.Drawing.Point(212, 75);
            this.button9.Name = "button9";
            this.button9.Size = new System.Drawing.Size(44, 23);
            this.button9.TabIndex = 15;
            this.button9.Text = "25 >";
            this.button9.UseVisualStyleBackColor = true;
            this.button9.Click += new System.EventHandler(this.button9_Click);
            //
            // ArmyMove
            //
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.DarkGray;
            this.ClientSize = new System.Drawing.Size(407, 164);
            this.Controls.Add(this.button8);
            this.Controls.Add(this.button9);
            this.Controls.Add(this.button6);
            this.Controls.Add(this.button7);
            this.Controls.Add(this.button5);
            this.Controls.Add(this.button3);
            this.Controls.Add(this.button4);
            this.Controls.Add(this.button1);
            this.Controls.Add(this.button2);
            this.Controls.Add(this.panel2);
            this.Controls.Add(this.panel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "ArmyMove";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = "Move Army";
            this.Load += new System.EventHandler(this.ArmyMove_Load);
            this.panel2.ResumeLayout(false);
            this.panel2.PerformLayout();
            this.panel1.ResumeLayout(false);
            this.panel1.PerformLayout();
            this.ResumeLayout(false);
        }
Member Data Documentation
Bolge Risk1.ArmyMove.bolge1 = new Bolge() [private]
Definition at line 16 of file ArmyMove.cs.
Referenced by Risk1.ArmyMove.ArmyMove(), Risk1.ArmyMove.ArmyMove_Load(), Risk1.ArmyMove.bolge1Azalt(), Risk1.ArmyMove.bolge2Azalt(), Risk1.ArmyMove.button1_Click(), and Risk1.ArmyMove.button2_Click().
Bolge Risk1.ArmyMove.bolge11 = null [private]
Definition at line 14 of file ArmyMove.cs.
Referenced by Risk1.ArmyMove.ArmyMove().
Bolge Risk1.ArmyMove.bolge2 = new Bolge() [private]
Definition at line 17 of file ArmyMove.cs.
Referenced by Risk1.ArmyMove.ArmyMove(), Risk1.ArmyMove.ArmyMove_Load(), Risk1.ArmyMove.bolge1Azalt(), Risk1.ArmyMove.bolge2Azalt(), Risk1.ArmyMove.button1_Click(), and Risk1.ArmyMove.button2_Click().
Bolge Risk1.ArmyMove.bolge22 = null [private]
Definition at line 15 of file ArmyMove.cs.
Referenced by Risk1.ArmyMove.ArmyMove().
System.Windows.Forms.Button Risk1.ArmyMove.button1 [private]
Definition at line 260 of file ArmyMove.Designer.cs.
System.Windows.Forms.Button Risk1.ArmyMove.button2 [private]
Definition at line 259 of file ArmyMove.Designer.cs.
System.Windows.Forms.Button Risk1.ArmyMove.button3 [private]
Definition at line 262 of file ArmyMove.Designer.cs.
System.Windows.Forms.Button Risk1.ArmyMove.button4 [private]
Definition at line 261 of file ArmyMove.Designer.cs.
Referenced by Risk1.ArmyMove.ArmyMove_Load().
System.Windows.Forms.Button Risk1.ArmyMove.button5 [private]
Definition at line 263 of file ArmyMove.Designer.cs.
System.Windows.Forms.Button Risk1.ArmyMove.button6 [private]
Definition at line 264 of file ArmyMove.Designer.cs.
System.Windows.Forms.Button Risk1.ArmyMove.button7 [private]
Definition at line 265 of file ArmyMove.Designer.cs.
System.Windows.Forms.Button Risk1.ArmyMove.button8 [private]
Definition at line 266 of file ArmyMove.Designer.cs.
System.Windows.Forms.Button Risk1.ArmyMove.button9 [private]
Definition at line 267 of file ArmyMove.Designer.cs.
System.ComponentModel.IContainer Risk1.ArmyMove.components = null [private]
Required designer variable.
Definition at line 8 of file ArmyMove.Designer.cs.
Form1 Risk1.ArmyMove.form1 = null [private]
Definition at line 18 of file ArmyMove.cs.
Referenced by Risk1.ArmyMove.ArmyMove(), Risk1.ArmyMove.bolge1Azalt(), Risk1.ArmyMove.bolge2Azalt(), Risk1.ArmyMove.button1_Click(), Risk1.ArmyMove.button2_Click(), and Risk1.ArmyMove.button4_Click().
System.Windows.Forms.Panel Risk1.ArmyMove.panel1 [private]
Definition at line 256 of file ArmyMove.Designer.cs.
Referenced by Risk1.ArmyMove.ArmyMove_Load().
System.Windows.Forms.Panel Risk1.ArmyMove.panel2 [private]
Definition at line 253 of file ArmyMove.Designer.cs.
Referenced by Risk1.ArmyMove.ArmyMove_Load().
System.Windows.Forms.TextBox Risk1.ArmyMove.textBox1 [private]
Definition at line 254 of file ArmyMove.Designer.cs.
Referenced by Risk1.ArmyMove.ArmyMove_Load().
System.Windows.Forms.TextBox Risk1.ArmyMove.textBox2 [private]
Definition at line 258 of file ArmyMove.Designer.cs.
Referenced by Risk1.ArmyMove.ArmyMove_Load(), Risk1.ArmyMove.bolge1Azalt(), Risk1.ArmyMove.bolge2Azalt(), Risk1.ArmyMove.button1_Click(), and Risk1.ArmyMove.button2_Click().
System.Windows.Forms.TextBox Risk1.ArmyMove.textBox3 [private]
Definition at line 255 of file ArmyMove.Designer.cs.
Referenced by Risk1.ArmyMove.ArmyMove_Load(), Risk1.ArmyMove.bolge1Azalt(), Risk1.ArmyMove.bolge2Azalt(), Risk1.ArmyMove.button1_Click(), and Risk1.ArmyMove.button2_Click().
System.Windows.Forms.TextBox Risk1.ArmyMove.textBox4 [private]
Definition at line 257 of file ArmyMove.Designer.cs.
Referenced by Risk1.ArmyMove.ArmyMove_Load().
The documentation for this class was generated from the following files:
Risk1/ArmyMove.cs
Risk1/ArmyMove.Designer.cs