ANKARISK: Risk1.Chart Class Reference
Risk1.Chart Class Reference
Public Member Functions
Chart (Form1 form1)
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void Chart_Load (object sender, EventArgs e)
void chart1_Click (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
Form1 f1
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.DataVisualization.Charting.Chart chart1
Detailed Description
Definition at line 13 of file Chart.cs.
Constructor & Destructor Documentation
Risk1.Chart.Chart (Form1 form1) [inline]
Definition at line 16 of file Chart.cs.
References Risk1.Chart.f1, and Risk1.Chart.InitializeComponent().
        {
            InitializeComponent();
            f1 = form1;
        }
Member Function Documentation
void Risk1.Chart.chart1_Click (object sender, EventArgs e) [inline, private]
Definition at line 62 of file Chart.cs.
        {
        }
void Risk1.Chart.Chart_Load (object sender, EventArgs e) [inline, private]
Definition at line 22 of file Chart.cs.
References Risk1.Chart.chart1, Risk1.Player.color, Risk1.Chart.f1, Risk1.Player.number, Risk1.Player.OptimizeAskerSayisiTarihi(), Risk1.Form1.players, and Risk1.Form1.turn.
        {
            List<int> tumSayilar = new List<int>();
            foreach (Player p in f1.players)
            {
                foreach (int i in p.OptimizeAskerSayisiTarihi())
                {
                    tumSayilar.Add(i);
                }
            }
            chart1.ChartAreas.Add("area");
            chart1.ChartAreas["area"].AxisX.Minimum = 1;
            chart1.ChartAreas["area"].AxisX.Maximum = f1.players[f1.turn].OptimizeAskerSayisiTarihi().Count;
            chart1.ChartAreas["area"].AxisX.Interval = 1;
            chart1.ChartAreas["area"].AxisY.Minimum = 0;
            chart1.ChartAreas["area"].AxisY.Maximum = tumSayilar.Max();
            chart1.ChartAreas["area"].AxisY.Interval = 10;
            foreach (Player p in f1.players)
            {
                chart1.Series.Add(p.number.ToString());
                chart1.Series[p.number.ToString()].Color = p.color;
                chart1.Series[p.number.ToString()].ChartType = SeriesChartType.Line;
                int k = 1;
                foreach (int i in p.OptimizeAskerSayisiTarihi())
                {
                    chart1.Series[p.number.ToString()].Points.AddXY(k, i);
                    k++;
                }
            }
        }
override void Risk1.Chart.Dispose (bool disposing) [inline, protected]
Clean up any resources being used.
Parameters:
disposing true if managed resources should be disposed; otherwise, false.
Definition at line 14 of file Chart.Designer.cs.
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }
void Risk1.Chart.InitializeComponent () [inline, private]
Required method for Designer support - do not modify the contents of this method with the code editor.
Definition at line 29 of file Chart.Designer.cs.
Referenced by Risk1.Chart.Chart().
        {
            this.chart1 = new System.Windows.Forms.DataVisualization.Charting.Chart();
            ((System.ComponentModel.ISupportInitialize)(this.chart1)).BeginInit();
            this.SuspendLayout();
            //
            // chart1
            //
            this.chart1.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
                        | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this.chart1.BackColor = System.Drawing.Color.Black;
            this.chart1.BackGradientStyle = System.Windows.Forms.DataVisualization.Charting.GradientStyle.TopBottom;
            this.chart1.BackImageWrapMode = System.Windows.Forms.DataVisualization.Charting.ChartImageWrapMode.Unscaled;
            this.chart1.BackSecondaryColor = System.Drawing.Color.WhiteSmoke;
            this.chart1.BorderlineColor = System.Drawing.Color.Black;
            this.chart1.BorderlineDashStyle = System.Windows.Forms.DataVisualization.Charting.ChartDashStyle.Dot;
            this.chart1.BorderlineWidth = 3;
            this.chart1.Location = new System.Drawing.Point(2, 1);
            this.chart1.Name = "chart1";
            this.chart1.Size = new System.Drawing.Size(815, 374);
            this.chart1.TabIndex = 0;
            this.chart1.Text = "chart1";
            this.chart1.Click += new System.EventHandler(this.chart1_Click);
            //
            // Chart
            //
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(816, 376);
            this.Controls.Add(this.chart1);
            this.Name = "Chart";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = "Chart";
            this.Load += new System.EventHandler(this.Chart_Load);
            ((System.ComponentModel.ISupportInitialize)(this.chart1)).EndInit();
            this.ResumeLayout(false);
        }
Member Data Documentation
System.Windows.Forms.DataVisualization.Charting.Chart Risk1.Chart.chart1 [private]
Definition at line 71 of file Chart.Designer.cs.
Referenced by Risk1.Chart.Chart_Load().
System.ComponentModel.IContainer Risk1.Chart.components = null [private]
Required designer variable.
Definition at line 8 of file Chart.Designer.cs.
Form1 Risk1.Chart.f1 [private]
Definition at line 15 of file Chart.cs.
Referenced by Risk1.Chart.Chart(), and Risk1.Chart.Chart_Load().
The documentation for this class was generated from the following files:
Risk1/Chart.cs
Risk1/Chart.Designer.cs